# -*- coding: utf-8 -*-
"""Phase 10 · Task 11 — the cumulative registry/catalog chain node.

Phase 10 is the product-pipeline phase (帷幄选股 A-chain + 落子买卖点 B-chain +
公共件 C). This module owns the reviewed *classification + chain* seal of that
phase — the node AFTER the Phase-9 adapter seal in the framework's linear
registry/catalog lineage (P2 → … → P8 → P9 → P10) — built as a pure ADDITION
over the sealed Phase-9 chain (never a fork, never a "latest" alias), mirroring
the ``adapters.chain`` (P9) / ``lane_catalog`` (P8) precedents:

* :data:`PHASE10_PUBLIC_MODELS` — the six public pipeline payloads the Phase-10
  cumulative registry resolves a :class:`SchemaRef` to. Five register at ``@1``
  under their own class names; the sixth,
  :class:`~guanlan_v2.orchestration.pipeline.assembly.PlanPresetRecordV2`,
  registers under the REVIEWED identity **``PlanPresetRecord@2``** (Amendment 3;
  ``assembly.PLAN_PRESET_RECORD_V2_SCHEMA_REF`` pins ``name="PlanPresetRecord"``)
  — a version bump of the Phase-7 preset-record schema family, not a new family.
  The registry keys strictly by class ``__name__``, so registration goes through
  a function-local registration identity (a 1:1 field-for-field subclass named
  ``PlanPresetRecord``) that never leaves :func:`build_phase10_registry` — the
  discovery firewall keeps seeing exactly the reviewed ``PlanPresetRecordV2``.
* :data:`PHASE10_INTERNAL_MODELS` — the reviewed ``type -> reason`` map of every
  Phase-10 ContractModel deliberately NOT registered (nine value carriers).
  ``DeepDecideBindings`` / ``MaterializedDeepDecide`` / ``CandidatePorts`` and
  the params dataclasses are plain (data)classes, invisible to the ContractModel
  firewall **by design** (the plan's Task-11 clause) — they can never be
  registered and are not listed here.
* :func:`build_phase10_registry` — a *fresh sealed* cumulative registry over the
  exact Phase-9 cumulative set + the six Phase-10 publics; the supplied base
  digest is verified against ``adapters.chain.PHASE9_REGISTRY_DIGEST`` *before
  any registration*; inherited JSON Schemas stay byte-identical to their
  Phase-<=9 goldens; :data:`PHASE10_REGISTRY_DIGEST` is frozen.
* :func:`build_phase10_catalog_snapshot` — extends the immutable Phase-9 catalog
  with exactly the three ``cand.*`` DETERMINISTIC WorkerSpecs (tier ``READER``,
  ``can_emit_decision=False``, ``selection_scope="dynamic_allowed"``, output
  ``CandidateSlate@1``) plus their three trusted handler materials and ONE
  guardrail material carrying the deep-decide preset record REFERENCE (preset
  id/version + the committed record's semantic digest + its registered schema
  key) — the catalog names the sealed preset it schedules against without ever
  duplicating the preset registry's authority. Every inherited entry passes
  through byte-identical; ``count_final_workers`` = the Phase-8 (== Phase-9)
  count + 3.

**Reviewed spec decisions (recorded for the chain test + report):**

* ``params_schema_ref=None`` on all three ``cand.*`` specs — the Task-2 params
  dual-path ruling lands on FACTORY-BOUND: the frozen ``Cand*Params`` are plain
  dataclasses (registering them would exceed the reviewed six-model surface), so
  a plan node scheduling a ``cand.*`` worker carries NO params (Phase 1 refuses
  node params without a schema ref) and the handler's ``merged_with`` node-param
  half stays dormant until a reviewed params schema lands.
* ``supported_modes=(DataMode.ONLINE,)`` — the ratified-D5 production ranking
  reader reads the LATEST ranking artifact (``v4_ranking_latest.parquet``);
  it implements no PIT discipline, so declaring ``PIT_REPLAY`` would be a lie.
* ``read_categories=("market_data",)`` mirrors the Lane-0 deterministic
  ``market.factor`` reader (the ranking artifact IS market data, reached through
  the injected :class:`~guanlan_v2.orchestration.pipeline.candidates.RankingReader`
  port, never a capability call — ``tool_calls=FORBIDDEN``).
* ``lane="quant"`` — deterministic quantitative ranking readers.

**EventType decision (explicit).** Phase 10 adds **no** ``EventType`` member and
mints **no** new Phase-3 data method id; a test pins the frozen value set.

Both goldens (``phase10_schema_manifest_v1.json`` /
``phase10_catalog_manifest_v1.json``) are hand-frozen from a one-off
verification run and never auto-regenerated by a test.
"""
from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

from guanlan_v2.orchestration.catalog import (
    CatalogError,
    ContentManifestEntry,
    EvidencePolicy,
    ExecutionSpec,
    OutputBinding,
    ResolvedTextMaterial,
    WorkerCatalogSnapshot,
    WorkerSpec,
    catalog_material_digest,
    validate_catalog_snapshot,
)
from guanlan_v2.orchestration.catalog_runtime import build_text_material
from guanlan_v2.orchestration.digest import ContractModel, DigestHex
from guanlan_v2.orchestration.enums import DataMode, ExecutionKind, Tier
from guanlan_v2.orchestration.enums import ToolCallRequirement
from guanlan_v2.orchestration.pipeline.assembly import PlanPresetRecordV2
from guanlan_v2.orchestration.pipeline.contracts import (
    CandidateEntry,
    CandidateSlate,
    EscalationReport,
    EscalationTrigger,
    RecommendationEntry,
    RecommendationSlate,
    RunSubject,
    TaSubmission,
)
from guanlan_v2.orchestration.refs import ContentRef, SchemaRef

if TYPE_CHECKING:  # pragma: no cover - typing only (avoids an import cycle)
    from guanlan_v2.orchestration.runtime_contracts import Phase2RuntimeRegistry

__all__ = [
    # registry
    "PHASE10_PUBLIC_MODELS",
    "Phase10RegistryError",
    "build_phase10_registry",
    # catalog
    "PHASE10_CATALOG_VERSION",
    "PHASE10_SOURCE_IDENTITY",
    "CAND_WORKER_IDS",
    "CAND_HANDLER_IDS",
    "DEEP_DECIDE_PRESET_REF_MATERIAL_ID",
    "build_phase10_materials",
    "build_phase10_worker_specs",
    "build_phase10_catalog_snapshot",
    "phase10_catalog_snapshot",
    # lazy (PEP 562) constants
    "PHASE10_INTERNAL_MODELS",  # noqa: F822 — lazy via module __getattr__
    "PHASE10_BASE_REGISTRY_DIGEST",  # noqa: F822 — lazy via module __getattr__
    "PHASE10_REGISTRY_DIGEST",  # noqa: F822 — lazy via module __getattr__
    "PHASE10_BASE_CATALOG_DIGEST",  # noqa: F822 — lazy via module __getattr__
    "PHASE10_CATALOG_DIGEST",  # noqa: F822 — lazy via module __getattr__
]


# =========================================================================== #
# The reviewed Phase-10 public / internal contract partition                    #
# =========================================================================== #
#: the exactly-six registered Phase-10 payload contracts. Ordered by the
#: candidate → recommendation → escalation → inbox → subject → preset
#: consumption chain the phase reads them in. ``PlanPresetRecordV2`` registers
#: as ``PlanPresetRecord@2`` (module docstring).
PHASE10_PUBLIC_MODELS: tuple[type[ContractModel], ...] = (
    CandidateSlate,
    RecommendationSlate,
    EscalationReport,
    TaSubmission,
    RunSubject,
    PlanPresetRecordV2,
)


_R10_VALUE_OBJECT = (
    "internal nested value object / component of a registered Phase-10 payload; "
    "a structural sub-record surfaced only inside its owning slate/report's "
    "semantic projection (it carries no independent schema_version), never a "
    "standalone cross-boundary payload"
)
_R10_RANKING_CARRIER = (
    "internal deterministic ranking-read carrier (Task 2): the port-level "
    "product of a RankingReader, consumed in-process by the cand.* builders and "
    "digest-bound into the slate's source_artifact_digest — never a registered "
    "cross-boundary payload"
)
_R10_ESCALATION_CONTEXT = (
    "internal zero-LLM escalation-judge input carrier (Task 5): the pure "
    "judge's port-assembled context (tail rows, quote, strat bands, news, "
    "position), consumed in-process by judge_escalation — never a registered "
    "cross-boundary payload"
)
_R10_SCREENING_CARRIER = (
    "internal screening-batch carrier (Task 3): the lease-channel admission "
    "bookkeeping (batch identity / per-lane entries / cost preview) the human "
    "card renders from, consumed in-process by admit_screening_batch — never a "
    "registered cross-boundary payload"
)


def _phase10_internal_models() -> "dict[type, str]":
    """The reviewed ``type -> reason`` map of every Phase-10 ContractModel
    deliberately NOT registered (all nine are value carriers; the plain
    dataclasses — ``DeepDecideBindings`` etc. — are invisible to the
    ContractModel firewall by design and can never be registered)."""
    from guanlan_v2.orchestration.pipeline.candidates import (
        RankingArtifact,
        RankingRow,
    )
    from guanlan_v2.orchestration.pipeline.escalation import EscalationContext
    from guanlan_v2.orchestration.pipeline.screening import (
        ScreeningBatch,
        ScreeningCostPreview,
        ScreeningLaneEntry,
    )

    return {
        # -- nested value objects (registered payloads' components) ----------- #
        CandidateEntry: _R10_VALUE_OBJECT,
        RecommendationEntry: _R10_VALUE_OBJECT,
        EscalationTrigger: _R10_VALUE_OBJECT,
        # -- deterministic ranking-read carriers (Task 2) ---------------------- #
        RankingArtifact: _R10_RANKING_CARRIER,
        RankingRow: _R10_RANKING_CARRIER,
        # -- the zero-LLM escalation-judge context (Task 5) -------------------- #
        EscalationContext: _R10_ESCALATION_CONTEXT,
        # -- screening-batch admission carriers (Task 3) ----------------------- #
        ScreeningBatch: _R10_SCREENING_CARRIER,
        ScreeningLaneEntry: _R10_SCREENING_CARRIER,
        ScreeningCostPreview: _R10_SCREENING_CARRIER,
    }


# =========================================================================== #
# The cumulative Phase-10 schema registry (linear chain over Phase 9)           #
# =========================================================================== #
class Phase10RegistryError(Exception):
    """A Phase-10 cumulative-registry construction invariant was violated."""


def _phase9_registry_digest() -> str:
    from guanlan_v2.orchestration.adapters import chain as p9

    return p9.PHASE9_REGISTRY_DIGEST


def _phase9_catalog_digest() -> str:
    from guanlan_v2.orchestration.adapters import chain as p9

    return p9.PHASE9_CATALOG_DIGEST


def _registered_plan_preset_record_v2() -> "type[PlanPresetRecordV2]":
    """The function-local REGISTRATION identity of ``PlanPresetRecordV2``.

    The cumulative registry keys strictly by class ``__name__``
    (``runtime_contracts.Phase2RuntimeRegistry.register``), and the reviewed
    registered identity is ``PlanPresetRecord@2`` (Amendment 3;
    ``assembly.PLAN_PRESET_RECORD_V2_SCHEMA_REF``) — the v2 of the Phase-7
    schema family, NOT a new ``PlanPresetRecordV2`` family. This 1:1
    field-for-field subclass carries the base name for registration only; it
    adds no field, no validator, and never leaves
    :func:`build_phase10_registry`, so the discovery/classification firewalls
    keep seeing exactly the reviewed ``assembly.PlanPresetRecordV2``. Its JSON
    Schema is deterministic across constructions (same fields, same title), so
    the golden digest is stable.
    """
    return type(
        "PlanPresetRecord",
        (PlanPresetRecordV2,),
        {"__module__": __name__, "__doc__": PlanPresetRecordV2.__doc__},
    )


def build_phase10_registry(
    expected_phase9_digest: "DigestHex",
) -> "Phase2RuntimeRegistry":
    """Build + seal the cumulative Phase-10 registry, pinned to the Phase-9 base.

    Verifies ``expected_phase9_digest`` against the actual sealed Phase-9
    cumulative registry digest first — any other base digest is rejected
    *before any registration* — then registers the complete inherited
    cumulative set (Phase 1 → Phase 9) followed by the six Phase-10 publics
    (:data:`PHASE10_PUBLIC_MODELS`; ``PlanPresetRecordV2`` through its
    ``PlanPresetRecord@2`` registration identity) into a *fresh*
    :class:`~guanlan_v2.orchestration.runtime_contracts.Phase2RuntimeRegistry`
    and seals it. No upstream registry is mutated; inherited JSON Schemas stay
    byte-identical to their Phase-<=9 goldens; there is no "latest" alias.
    """
    from guanlan_v2.orchestration import (
        bootstrap,
        lane_catalog as p8,
        phase7_registry as p7,
        shadow,
        trial,
    )
    from guanlan_v2.orchestration.adapters import chain as p9
    from guanlan_v2.orchestration.data.schema_registry import (
        PHASE3_PUBLIC_MODELS as _DATA_PUBLIC,
    )
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_MEMORY_PUBLIC_MODELS as _MEM_PUBLIC,
    )
    from guanlan_v2.orchestration.runtime_contracts import (
        Phase2RuntimeRegistry,
        phase2_public_models,
    )

    actual = p9.PHASE9_REGISTRY_DIGEST
    if expected_phase9_digest != actual:
        raise Phase10RegistryError(
            "build_phase10_registry requires the exact Phase-9 registry digest "
            f"{actual!r}; got {expected_phase9_digest!r}"
        )
    reg = Phase2RuntimeRegistry()
    for model in (
        tuple(phase2_public_models())
        + tuple(_DATA_PUBLIC)
        + tuple(_MEM_PUBLIC)
        + tuple(trial.PHASE4_PUBLIC_MODELS)
        + tuple(bootstrap.PHASE5_PUBLIC_MODELS)
        + tuple(shadow.PHASE6_PUBLIC_MODELS)
        + tuple(p7.PHASE7_PUBLIC_MODELS)
        + tuple(p8.PHASE8_PUBLIC_MODELS)
        + tuple(p9.PHASE9_PUBLIC_MODELS)
    ):
        reg.register(model)
    for model in PHASE10_PUBLIC_MODELS:
        if model is PlanPresetRecordV2:
            reg.register(_registered_plan_preset_record_v2())
        else:
            reg.register(model)
    reg.seal()
    return reg


# =========================================================================== #
# The Phase-10 catalog: three cand.* workers + the deep-decide preset reference #
# =========================================================================== #
#: the merged cumulative Phase-10 catalog version.
PHASE10_CATALOG_VERSION = "phase10-full-v1"

#: the reviewed provenance ``LogicalId`` stamped on every Phase-10-owned
#: manifest entry (the ``adapters.chain`` P9 / ``lane_catalog`` P8 precedent).
PHASE10_SOURCE_IDENTITY = "guanlan.orchestration.phase10"

#: the three reviewed deterministic candidate workers (ids frozen by Task 2).
CAND_WORKER_IDS: tuple[str, str, str] = ("cand.lane0", "cand.model", "cand.v4")

#: worker id -> trusted handler material id.
CAND_HANDLER_IDS: dict[str, str] = {
    "cand.v4": "pipeline.cand.v4.handler",
    "cand.lane0": "pipeline.cand.lane0.handler",
    "cand.model": "pipeline.cand.model.handler",
}

#: the deep-decide preset record REFERENCE guardrail material id.
DEEP_DECIDE_PRESET_REF_MATERIAL_ID = "pipeline.deep_decide.preset_record.ref"

#: the trusted candidate-handler marker bytes (reviewed catalog material only —
#: the runtime binds the real ``candidates.cand_*_handler`` callables by this id
#: at wiring time via ``TrustedFactoryRegistry``; the bytes carry no path).
_CAND_HANDLER_BYTES: dict[str, bytes] = {
    "pipeline.cand.v4.handler": (
        b"# pipeline.cand.v4.handler v1\n"
        b"Trusted deterministic cand.v4 worker handler (candidates.cand_v4_handler).\n"
        b"Reads the production v4 ranking artifact through the injected RankingReader\n"
        b"port (ratified D5) and emits its top-N CandidateSlate@1 with provenance +\n"
        b"staleness/unmappable badges. Zero LLM, zero network, read-only; an empty\n"
        b"slate is honest (empty_slate badge), never an error.\n"
    ),
    "pipeline.cand.lane0.handler": (
        b"# pipeline.cand.lane0.handler v1\n"
        b"Trusted deterministic cand.lane0 worker handler (candidates.cand_lane0_handler).\n"
        b"v1 is the HONEST TYPED REFUSAL (ratified D4): no upstream surface carries\n"
        b"rotation leader codes, so invocation raises Lane0LeadersUnavailable and the\n"
        b"executor records an honest FAILED node - a universe is never invented.\n"
    ),
    "pipeline.cand.model.handler": (
        b"# pipeline.cand.model.handler v1\n"
        b"Trusted deterministic cand.model worker handler (candidates.cand_model_handler).\n"
        b"The cand.v4 read against a NAMED model variant (variant_id mandatory, the\n"
        b"reserved production ids refused) through the same RankingReader port; emits\n"
        b"CandidateSlate@1 with source_kind='model_variant'. Zero LLM, read-only.\n"
    ),
}

#: the registered output every candidate worker publishes.
_CANDIDATE_SLATE_SCHEMA_REF = SchemaRef(name="CandidateSlate", version="1")


def _deep_decide_preset_ref_doc() -> dict:
    """The deep-decide preset record REFERENCE document (guardrail bytes).

    Loads the committed sealed preset (``presets/v2/luozi_deep_decide_v1.json``)
    through the reviewed Phase-10 loader and binds its identity + semantic
    digest + registered schema key. The catalog thereby NAMES the exact sealed
    preset the deep lane leases against; the preset registry remains the sole
    record authority (the reference never embeds the record body).
    """
    from guanlan_v2.orchestration.pipeline.assembly import (
        PLAN_PRESET_RECORD_V2_SCHEMA_REF,
        PRODUCTION_PRESETS_DIR,
        load_phase10_preset_registry,
    )
    from guanlan_v2.orchestration.pipeline.deep_decide import (
        DEEP_DECIDE_PRESET_ID,
        DEEP_DECIDE_PRESET_VERSION,
    )

    record = load_phase10_preset_registry(PRODUCTION_PRESETS_DIR).get(
        DEEP_DECIDE_PRESET_ID)
    if not isinstance(record, PlanPresetRecordV2):
        raise CatalogError(
            f"committed preset {DEEP_DECIDE_PRESET_ID!r} is not a "
            "PlanPresetRecordV2; the catalog reference refuses to name it"
        )
    return {
        "kind": "plan_preset_record_ref",
        "preset_id": DEEP_DECIDE_PRESET_ID,
        "preset_version": DEEP_DECIDE_PRESET_VERSION,
        "record_digest": record.semantic_digest(),
        "schema_key": PLAN_PRESET_RECORD_V2_SCHEMA_REF.key,
    }


def _serialize_preset_ref_doc(doc: dict) -> bytes:
    return json.dumps(
        doc, sort_keys=True, ensure_ascii=False, separators=(",", ":")
    ).encode("utf-8")


def build_phase10_materials() -> tuple[
    dict[str, ContentRef], tuple[ResolvedTextMaterial, ...]
]:
    """Build the four Phase-10 catalog materials (three handlers + the preset ref).

    Returns ``(refs_by_id, materials)`` with digests computed from the exact
    bytes via the reviewed :func:`build_text_material` (never pinned by hand).
    """
    refs: dict[str, ContentRef] = {}
    materials: list[ResolvedTextMaterial] = []
    for material_id, raw in sorted(_CAND_HANDLER_BYTES.items()):
        ref, mat = build_text_material(
            id=material_id, version="1", kind="handler", raw=raw)
        refs[material_id] = ref
        materials.append(mat)
    ref, mat = build_text_material(
        id=DEEP_DECIDE_PRESET_REF_MATERIAL_ID, version="1", kind="guardrail",
        raw=_serialize_preset_ref_doc(_deep_decide_preset_ref_doc()))
    refs[DEEP_DECIDE_PRESET_REF_MATERIAL_ID] = ref
    materials.append(mat)
    return refs, tuple(materials)


def build_phase10_worker_specs(
    refs: dict[str, ContentRef],
) -> tuple[WorkerSpec, ...]:
    """The three reviewed ``cand.*`` DETERMINISTIC WorkerSpecs (module docstring
    records the params/mode/lane/read-category decisions)."""
    persona = {
        "cand.v4": (
            "Deterministic v4-ranking candidate reader — top-N slate, "
            "advisory-only, zero trading authority"
        ),
        "cand.lane0": (
            "Deterministic Lane-0 rotation-leader candidate reader — honest "
            "typed refusal in v1 (no upstream leader codes), zero trading authority"
        ),
        "cand.model": (
            "Deterministic model-variant candidate reader — named-variant "
            "top-N slate, advisory-only, zero trading authority"
        ),
    }
    specs = []
    for worker_id in CAND_WORKER_IDS:
        specs.append(WorkerSpec(
            id=worker_id,
            catalog_role="final",
            selection_scope="dynamic_allowed",
            lane="quant",
            persona=persona[worker_id],
            tier=Tier.READER,
            execution=ExecutionSpec(
                kind=ExecutionKind.DETERMINISTIC,
                handler_ref=refs[CAND_HANDLER_IDS[worker_id]],
            ),
            read_categories=("market_data",),
            params_schema_ref=None,
            inputs=(),
            outputs=(OutputBinding(
                name="primary", schema_ref=_CANDIDATE_SLATE_SCHEMA_REF),),
            evidence_policy=EvidencePolicy(
                tool_calls=ToolCallRequirement.FORBIDDEN,
                require_input_refs=False,
                require_number_anchors=False,
                allow_unsourced_numbers=False,
                optional_data_may_degrade=True,
            ),
            supported_modes=(DataMode.ONLINE,),
            can_emit_decision=False,
            decision_authority="none",
        ))
    return tuple(specs)


def build_phase10_catalog_snapshot(
    phase9_snapshot: "WorkerCatalogSnapshot",
    *,
    resolved_materials: tuple[ResolvedTextMaterial, ...],
) -> "WorkerCatalogSnapshot":
    """Extend the immutable Phase-9 catalog with the Phase-10 pipeline additions.

    Rejects any base whose ``catalog_digest`` differs from the canonical
    Phase-9 cumulative catalog digest (the sole legal base). Verifies the
    supplied materials are EXACTLY the four reviewed Phase-10 materials (byte
    digests recomputed, preset-reference bytes re-parsed and cross-checked
    against the committed preset registry so a preset edit without a catalog
    re-freeze is loud), builds the three ``cand.*`` WorkerSpecs over the
    verified handler refs, and merges — every inherited Phase-9 worker / skill /
    capability / content entry passes through byte-identical; new ids must not
    collide; the manifests are sorted; the cumulative ``catalog_digest`` is
    sealed and every cross-reference re-validated.
    """
    base_digest = _phase9_catalog_digest()
    if phase9_snapshot.catalog_digest != base_digest:
        raise CatalogError(
            "build_phase10_catalog_snapshot requires the canonical immutable "
            f"Phase-9 catalog ({base_digest}); got base "
            f"{phase9_snapshot.catalog_digest}"
        )

    # -- index + verify the four Phase-10 materials --------------------------- #
    expected_keys = {(mid, "1") for mid in _CAND_HANDLER_BYTES} | {
        (DEEP_DECIDE_PRESET_REF_MATERIAL_ID, "1")
    }
    by_key: dict[tuple[str, str], ResolvedTextMaterial] = {}
    for m in resolved_materials:
        if not isinstance(m, ResolvedTextMaterial):
            raise CatalogError(
                f"phase10 materials must be text materials; got {type(m).__name__}"
            )
        if m.ref_key in by_key:
            raise CatalogError(f"duplicate phase10 material {m.ref_key}")
        if catalog_material_digest(m) != m.ref.content_digest:
            raise CatalogError(
                f"phase10 material {m.ref_key} digest does not recompute from "
                "its bytes"
            )
        by_key[m.ref_key] = m
    if set(by_key) != expected_keys:
        raise CatalogError(
            "phase10 catalog takes exactly the four reviewed materials "
            f"{sorted(expected_keys)}; got {sorted(by_key)}"
        )
    for mid, raw in _CAND_HANDLER_BYTES.items():
        mat = by_key[(mid, "1")]
        if mat.kind != "handler" or mat.raw_utf8 != raw:
            raise CatalogError(
                f"phase10 handler material {mid}@1 drifted from the reviewed bytes"
            )
    pref = by_key[(DEEP_DECIDE_PRESET_REF_MATERIAL_ID, "1")]
    if pref.kind != "guardrail":
        raise CatalogError(
            "the deep-decide preset reference must be a guardrail material"
        )
    try:
        doc = json.loads(pref.raw_utf8.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise CatalogError(
            f"the deep-decide preset reference bytes are not canonical JSON: {exc}"
        ) from exc
    expected_doc = _deep_decide_preset_ref_doc()
    if doc != expected_doc:
        raise CatalogError(
            "the deep-decide preset reference does not match the committed sealed "
            f"preset (got {doc}, committed {expected_doc}); a preset change is a "
            "reviewed catalog re-freeze, never a silent drift"
        )

    # -- workers: exactly the three new cand.* finals ------------------------- #
    refs = {key[0]: m.ref for key, m in by_key.items()}
    new_workers = build_phase10_worker_specs(refs)
    base_ids = {w.id for w in phase9_snapshot.workers}
    for w in new_workers:
        if w.id in base_ids:
            raise CatalogError(
                f"new candidate worker {w.id!r} collides with an inherited "
                "Phase-9 worker id"
            )

    # -- content entries + merge (inherit byte-identical, sort, seal) ---------- #
    new_content = tuple(
        ContentManifestEntry(
            ref=by_key[key].ref,
            kind=by_key[key].kind,
            name=key[0],
            description=(
                f"phase10 pipeline material {key[0]}@{key[1]} ({by_key[key].kind})."
            ),
            source_identity=PHASE10_SOURCE_IDENTITY,
        )
        for key in sorted(by_key)
    )
    base_content_keys = {e.ref_key for e in phase9_snapshot.content_manifest}
    for e in new_content:
        if e.ref_key in base_content_keys:
            raise CatalogError(
                f"phase10 material {e.ref_key} collides with an inherited "
                "Phase-9 content entry"
            )

    content_sorted = tuple(sorted(
        tuple(phase9_snapshot.content_manifest) + new_content,
        key=lambda e: e.ref_key))
    workers_sorted = tuple(sorted(
        tuple(phase9_snapshot.workers) + new_workers, key=lambda w: w.id))

    fields: dict[str, Any] = dict(
        catalog_version=PHASE10_CATALOG_VERSION,
        content_manifest=content_sorted,
        skill_manifest=tuple(phase9_snapshot.skill_manifest),
        capability_manifest=tuple(phase9_snapshot.capability_manifest),
        workers=workers_sorted,
    )
    try:
        digest = WorkerCatalogSnapshot.digest_of_fields(projection="semantic", **fields)
    except (ValueError, TypeError, AttributeError, KeyError):
        digest = "0" * 64
    try:
        snapshot = WorkerCatalogSnapshot(**fields, catalog_digest=digest)
    except Exception as exc:  # surface structural failures as CatalogError
        raise CatalogError(f"phase10 catalog snapshot is not runnable: {exc}") from exc
    validate_catalog_snapshot(snapshot)
    return snapshot


def phase10_catalog_snapshot() -> "WorkerCatalogSnapshot":
    """The canonical cumulative Phase-10 catalog snapshot (the pipeline seal)."""
    from guanlan_v2.orchestration.adapters import chain as p9

    base = p9.phase9_catalog_snapshot()
    _refs, materials = build_phase10_materials()
    return build_phase10_catalog_snapshot(base, resolved_materials=materials)


# --------------------------------------------------------------------------- #
# Lazy canonical digests (PEP 562) — computed once, never a mutable "latest"    #
# --------------------------------------------------------------------------- #
_PHASE10_REGISTRY_DIGEST: str | None = None
_PHASE10_CATALOG_DIGEST: str | None = None
_PHASE10_INTERNAL_MODELS: "dict[type, str] | None" = None


def __getattr__(name: str) -> "Any":
    global _PHASE10_REGISTRY_DIGEST, _PHASE10_CATALOG_DIGEST
    global _PHASE10_INTERNAL_MODELS
    if name == "PHASE10_INTERNAL_MODELS":
        if _PHASE10_INTERNAL_MODELS is None:
            _PHASE10_INTERNAL_MODELS = _phase10_internal_models()
        return _PHASE10_INTERNAL_MODELS
    if name == "PHASE10_BASE_REGISTRY_DIGEST":
        return _phase9_registry_digest()
    if name == "PHASE10_REGISTRY_DIGEST":
        if _PHASE10_REGISTRY_DIGEST is None:
            _PHASE10_REGISTRY_DIGEST = build_phase10_registry(
                _phase9_registry_digest()
            ).registry_digest
        return _PHASE10_REGISTRY_DIGEST
    if name == "PHASE10_BASE_CATALOG_DIGEST":
        return _phase9_catalog_digest()
    if name == "PHASE10_CATALOG_DIGEST":
        if _PHASE10_CATALOG_DIGEST is None:
            _PHASE10_CATALOG_DIGEST = phase10_catalog_snapshot().catalog_digest
        return _PHASE10_CATALOG_DIGEST
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
