# -*- coding: utf-8 -*-
"""Phase 3 · Task 3 — ``resolve_name_to_code`` + ``resolve_limit_rule`` + the
read-only trading-calendar port + the versioned limit-rule policy golden.

This module is deliberately *self-contained*: it builds the immutable fake
``CALENDAR`` and the verified ``LIMIT_POLICY`` inline (rather than importing a
separate ``calendar_fixtures`` module) so the whole task ships as one committed
test file alongside the two source files and the reviewed golden. It covers, in
one place:

* the normative ``resolve_name_to_code`` / ``resolve_limit_rule`` cases from the
  plan (a direct code passes through, a verified name resolves, an industry /
  concept term is rejected, and every PIT / ST / listing guard returns an
  explicit ``pct=None`` with a stated reason rather than a guess);
* the trading-calendar port: deterministic session counts, holidays, immutable
  material, and a resolver that is loud on missing / drifted material or a
  calendar-ID mismatch;
* the frozen ``limit_rule_policy_v1.json`` golden, whose digest is REAL and is
  never regenerated by this test.

Run: ``pytest tests/orchestration/data/test_resolve.py -v``
"""
from __future__ import annotations

import hashlib
import json
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import pytest

from guanlan_v2.orchestration.data.calendar import (
    ImmutableTradingCalendar,
    TradingCalendarResolver,
    build_trading_calendar,
)
from guanlan_v2.orchestration.data.errors import (
    RoutingConfigurationError,
    SnapshotMismatchError,
)
from guanlan_v2.orchestration.data.symbols import (
    InstrumentMeta,
    LimitRuleEntry,
    LimitRulePolicy,
    Symbol,
    build_limit_rule_policy,
    resolve_limit_rule,
    resolve_name_to_code,
)
from guanlan_v2.orchestration.digest import canonical_json
from guanlan_v2.orchestration.refs import ContentRef

UTC = timezone.utc
GOLDEN_PATH = (
    Path(__file__).resolve().parent.parent / "golden" / "limit_rule_policy_v1.json"
)

# --------------------------------------------------------------------------- #
# Immutable fake calendar + verified versioned policy (built via the builders) #
# --------------------------------------------------------------------------- #
_CALENDAR_ID = "XSHG"
_HOLIDAY = date(2026, 7, 10)  # a weekday that is deliberately not a session


def _weekday_sessions_2026() -> tuple[date, ...]:
    """Every 2026 weekday except the single holiday — a small immutable material."""
    out: list[date] = []
    d = date(2026, 1, 1)
    while d <= date(2026, 12, 31):
        if d.weekday() < 5 and d != _HOLIDAY:
            out.append(d)
        d += timedelta(days=1)
    return tuple(out)


CALENDAR = build_trading_calendar(
    calendar_id=_CALENDAR_ID,
    sessions=_weekday_sessions_2026(),
    material_id="trading_calendar.xshg.2026",
    material_version="2026.1",
)

_ENTRY = LimitRuleEntry(
    effective_from=datetime(2020, 1, 1, tzinfo=UTC),
    effective_to=None,
    board_pct={"main": 0.10, "star": 0.20, "chinext": 0.20, "bj": 0.30},
    st_pct=0.05,
    first_session_window=5,
    first_session_pct=None,
)

LIMIT_POLICY = build_limit_rule_policy(
    policy_id="ashare.price_limit",
    policy_version="1",
    calendar=CALENDAR,
    entries=(_ENTRY,),
)

_MAP = {"贵州茅台": "600519"}  # extracted from a verified InstrumentNameRows fixture
META_AT = datetime(2026, 7, 14, tzinfo=UTC)
LISTED_AT = datetime(2001, 8, 27, tzinfo=UTC)
AS_OF = datetime(2026, 7, 15, tzinfo=UTC)


def _limit(sym, as_of, meta):
    return resolve_limit_rule(sym, as_of, meta, policy=LIMIT_POLICY, calendar=CALENDAR)


def _meta(sym, *, is_st=False, metadata_available_at=META_AT):
    return InstrumentMeta(
        symbol=sym,
        is_st=is_st,
        listed_at=LISTED_AT,
        metadata_available_at=metadata_available_at,
    )


# --------------------------------------------------------------------------- #
# resolve_name_to_code                                                         #
# --------------------------------------------------------------------------- #
def test_name_resolves_to_code():
    assert resolve_name_to_code("贵州茅台", _MAP).code == "600519"


def test_code_passthrough():
    assert resolve_name_to_code("600519.SH", _MAP).code == "600519"


def test_industry_name_rejected():
    with pytest.raises(ValueError):
        resolve_name_to_code("白酒", _MAP)


def test_name_map_value_must_itself_be_a_valid_symbol():
    # a verified map is still not trusted blindly: a bogus value is rejected, not
    # returned as if it were a code.
    with pytest.raises(ValueError):
        resolve_name_to_code("垃圾", {"垃圾": "notacode"})


def test_non_string_input_is_type_error():
    with pytest.raises(TypeError):
        resolve_name_to_code(600519, _MAP)  # type: ignore[arg-type]


# --------------------------------------------------------------------------- #
# resolve_limit_rule                                                           #
# --------------------------------------------------------------------------- #
def test_limit_rule_main_board():
    sym = Symbol(code="600519", exchange="SH", board="main")
    r = _limit(sym, AS_OF, _meta(sym))
    assert r.pct == 0.10


def test_limit_rule_star_and_st():
    star = Symbol(code="688981", exchange="SH", board="star")
    assert _limit(star, AS_OF, _meta(star)).pct == 0.20
    st = _meta(star, is_st=True)
    assert _limit(star, AS_OF, st).pct == 0.05


def test_limit_rule_unknown_st_returns_none():
    sym = Symbol(code="600519", exchange="SH", board="main")
    r = _limit(sym, AS_OF, _meta(sym, is_st=None))
    assert r.pct is None and "unknown" in r.reason.lower()


def test_limit_rule_rejects_symbol_mismatch():
    sym = Symbol(code="600519", exchange="SH", board="main")
    other = Symbol(code="000001", exchange="SZ", board="main")
    with pytest.raises(ValueError, match="symbol"):
        _limit(sym, AS_OF, _meta(other))


def test_future_metadata_is_explicit_unknown_not_current_rule():
    sym = Symbol(code="600519", exchange="SH", board="main")
    future = datetime(2026, 7, 16, tzinfo=UTC)
    rule = _limit(sym, AS_OF, _meta(sym, metadata_available_at=future))
    assert rule.pct is None and "available" in rule.reason.lower()


def test_not_yet_listed_is_explicit_unknown():
    sym = Symbol(code="600519", exchange="SH", board="main")
    meta = InstrumentMeta(
        symbol=sym,
        is_st=False,
        listed_at=datetime(2026, 7, 16, tzinfo=UTC),
        metadata_available_at=META_AT,
    )
    rule = _limit(sym, AS_OF, meta)
    assert rule.pct is None and "listed" in rule.reason.lower()


def test_limit_rule_rejects_naive_as_of():
    sym = Symbol(code="600519", exchange="SH", board="main")
    with pytest.raises((TypeError, ValueError)):
        _limit(sym, datetime(2026, 7, 15), _meta(sym))


def test_unavailable_calendar_returns_unknown_not_guess():
    # the policy carries a session-based listing-stage rule, so a missing calendar
    # cannot be papered over with a guessed percentage.
    sym = Symbol(code="600519", exchange="SH", board="main")
    rule = resolve_limit_rule(
        sym, AS_OF, _meta(sym), policy=LIMIT_POLICY, calendar=None
    )
    assert rule.pct is None and "calendar" in rule.reason.lower()


def test_mismatched_calendar_returns_unknown_not_guess():
    other = build_trading_calendar(
        calendar_id="XSHE",  # a different calendar identity
        sessions=_weekday_sessions_2026(),
        material_id="trading_calendar.xshe.2026",
        material_version="2026.1",
    )
    sym = Symbol(code="600519", exchange="SH", board="main")
    rule = resolve_limit_rule(
        sym, AS_OF, _meta(sym), policy=LIMIT_POLICY, calendar=other
    )
    assert rule.pct is None and "calendar" in rule.reason.lower()


# --------------------------------------------------------------------------- #
# resolve_limit_rule — clamped lower-bound semantics for a pre-coverage listing #
# (L2-b Task-1 review Important #1: an uncovered date is UNCOVERED, not "zero   #
# sessions" — counting across it silently undercounts and reported a seasoned   #
# main-board stock as limitless.)                                              #
# --------------------------------------------------------------------------- #
#: a calendar whose material starts mid-window (like the production 2026-only
#: material, coverage from 2026-01-05): every earlier session is UNKNOWABLE.
_CLAMP_COVERAGE_START = date(2026, 1, 5)

CLAMPED_CALENDAR = build_trading_calendar(
    calendar_id=_CALENDAR_ID,
    sessions=tuple(d for d in _weekday_sessions_2026() if d >= _CLAMP_COVERAGE_START),
    material_id="trading_calendar.xshg.2026-from-0105",
    material_version="2026.1",
)

CLAMPED_POLICY = build_limit_rule_policy(
    policy_id="ashare.price_limit.clamped",
    policy_version="1",
    calendar=CLAMPED_CALENDAR,
    entries=(_ENTRY,),
)


def _clamped(sym, as_of, meta):
    return resolve_limit_rule(
        sym, as_of, meta, policy=CLAMPED_POLICY, calendar=CLAMPED_CALENDAR
    )


def test_pre_coverage_listing_early_as_of_is_honest_refusal_not_false_no_limit():
    """Listed decades before coverage + only 4 in-coverage sessions elapsed
    (< window 5): the true elapsed count CANNOT be established from the
    material — a typed unknown refusal, never the false 'no ordinary price
    limit applies' (the review's reproduced January case)."""
    sym = Symbol(code="600519", exchange="SH", board="main")
    rule = _clamped(
        sym,
        datetime(2026, 1, 8, tzinfo=UTC),
        _meta(sym, metadata_available_at=LISTED_AT),
    )
    assert rule.pct is None
    assert "listed before calendar coverage" in rule.reason
    assert "within the initial listing sessions" not in rule.reason


def test_pre_coverage_listing_late_as_of_gets_the_ordinary_limit():
    """The lower bound (sessions counted from coverage start) >= window: the
    pre-coverage listing session itself is a real session NOT in that count,
    so the window has certainly passed — the ordinary limit applies."""
    sym = Symbol(code="600519", exchange="SH", board="main")
    rule = _clamped(sym, AS_OF, _meta(sym))
    assert rule.pct == 0.10


def test_pre_coverage_listing_late_as_of_st_still_wins():
    """The clamp only certifies the window has passed; the ST rule still
    applies after the fall-through."""
    sym = Symbol(code="600519", exchange="SH", board="main")
    rule = _clamped(sym, AS_OF, _meta(sym, is_st=True))
    assert rule.pct == 0.05


def test_in_coverage_listing_keeps_the_no_limit_window():
    """True IPO fidelity pinned: listed inside coverage, 3 elapsed sessions
    <= window 5 — the exact count governs, unchanged semantics."""
    sym = Symbol(code="600519", exchange="SH", board="main")
    listed = datetime(2026, 6, 1, tzinfo=UTC)  # a Monday session
    meta = InstrumentMeta(
        symbol=sym, is_st=False, listed_at=listed, metadata_available_at=listed
    )
    rule = _clamped(sym, datetime(2026, 6, 3, tzinfo=UTC), meta)
    assert rule.pct is None
    assert "within the initial listing sessions" in rule.reason


def test_as_of_outside_coverage_is_unknown_not_zero_sessions():
    """An as_of before coverage start or past coverage end is UNCOVERED: the
    session count is not computable, so the rule is an honest unknown."""
    sym = Symbol(code="600519", exchange="SH", board="main")
    for as_of in (
        datetime(2026, 1, 2, tzinfo=UTC),   # before the first covered session
        datetime(2027, 1, 4, tzinfo=UTC),   # past the last covered session
    ):
        rule = _clamped(sym, as_of, _meta(sym, metadata_available_at=LISTED_AT))
        assert rule.pct is None
        assert "coverage" in rule.reason.lower()


# --------------------------------------------------------------------------- #
# TradingCalendar port + resolver (folds in the plan's test_calendar.py cases) #
# --------------------------------------------------------------------------- #
def test_is_session_and_holiday():
    assert CALENDAR.is_session(date(2026, 7, 15)) is True  # a Wednesday
    assert CALENDAR.is_session(date(2026, 7, 11)) is False  # Saturday
    assert CALENDAR.is_session(_HOLIDAY) is False  # a weekday holiday


def test_sessions_between_deterministic_count():
    # Mon 07-06 .. Fri 07-17: 06,07,08,09 then 13,14,15,16,17 = 9 sessions;
    # 07-10 is the holiday and 07-11/07-12 are the weekend.
    assert CALENDAR.sessions_between(date(2026, 7, 6), date(2026, 7, 17)) == 9


def test_sessions_between_rejects_reversed_range():
    with pytest.raises(ValueError):
        CALENDAR.sessions_between(date(2026, 7, 17), date(2026, 7, 6))


def test_resolver_resolves_matching_material():
    resolver = TradingCalendarResolver([CALENDAR])
    resolved = resolver.resolve(CALENDAR.material_ref, calendar_id=_CALENDAR_ID)
    assert resolved.calendar_id == _CALENDAR_ID
    assert resolved.material_ref == CALENDAR.material_ref


def test_resolver_missing_material_is_loud():
    resolver = TradingCalendarResolver([])
    with pytest.raises(RoutingConfigurationError):
        resolver.resolve(CALENDAR.material_ref, calendar_id=_CALENDAR_ID)


def test_resolver_digest_drift_is_loud():
    resolver = TradingCalendarResolver([CALENDAR])
    drifted = ContentRef(
        id=CALENDAR.material_ref.id,
        version=CALENDAR.material_ref.version,
        content_digest="0" * 64,
    )
    with pytest.raises(SnapshotMismatchError):
        resolver.resolve(drifted, calendar_id=_CALENDAR_ID)


def test_resolver_calendar_id_mismatch_is_loud():
    resolver = TradingCalendarResolver([CALENDAR])
    with pytest.raises(SnapshotMismatchError):
        resolver.resolve(CALENDAR.material_ref, calendar_id="XSHE")


def test_material_tamper_is_loud_on_construction():
    with pytest.raises(SnapshotMismatchError):
        ImmutableTradingCalendar(
            material=CALENDAR.material,
            material_ref=ContentRef(id="x.y", version="1", content_digest="0" * 64),
        )


# --------------------------------------------------------------------------- #
# Frozen golden — a REAL digest, NEVER regenerated by this test                #
# --------------------------------------------------------------------------- #
def test_golden_policy_digest_is_real_and_recomputable():
    assert GOLDEN_PATH.exists(), f"missing golden: {GOLDEN_PATH}"
    doc = json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))
    assert doc["algorithm"] == "sha256+cjson-v1"
    # the fixture-built policy reproduces the frozen digest exactly
    assert LIMIT_POLICY.policy_digest == doc["policy_digest"]
    # the stored canonical json is exactly the policy's semantic canonical form
    assert doc["canonical_json"] == canonical_json(LIMIT_POLICY, projection="semantic")
    # and the digest is genuinely sha256(canonical_json) — not a placeholder
    assert (
        hashlib.sha256(doc["canonical_json"].encode("utf-8")).hexdigest()
        == doc["policy_digest"]
    )
    assert doc["policy_digest"] != "0" * 64
    # the referenced calendar material digest matches the fixture calendar
    assert doc["calendar_material_digest"] == CALENDAR.material_ref.content_digest
