# -*- coding: utf-8 -*-
"""Phase 9 · Task 9 — the cumulative registry/catalog chain node (the LAST node).

Phase 9 is the 完整落子/帷幄 adapter phase: the 落子 interval replay / dual-curve
driver, the 帷幄 ONLINE binding, the durable stores and the entry-point retirement
gates. This module owns the reviewed *classification + chain* seal of that phase —
the FINAL node in the framework's linear registry/catalog lineage (P2 → … → P8 →
P9) — built as a pure ADDITION over the sealed Phase-8 四车道 chain (never a fork,
never a "latest" alias), mirroring the ``phase7_registry`` / ``lane_catalog`` (P8)
chain precedents:

* :data:`PHASE9_PUBLIC_MODELS` — the nine public adapter payloads the Phase-9
  cumulative registry resolves a :class:`SchemaRef` to (Task 1 ``adapters.contracts``);
* :func:`build_phase9_registry` — a *fresh sealed* cumulative registry over the exact
  Phase-8 cumulative set + :data:`PHASE9_PUBLIC_MODELS`; the supplied base digest is
  verified against :data:`PHASE8_REGISTRY_DIGEST` *before any registration*; inherited
  JSON Schemas stay byte-identical to their Phase-<=8 goldens; :data:`PHASE9_REGISTRY_DIGEST`
  is the frozen, order-independent digest;
* :func:`build_phase9_catalog_snapshot` — extends the immutable Phase-8 27-worker
  catalog with ONLY the two adapter **source materials** (the Task-2 ``PIT_REPLAY``
  PitReader source + the Task-3 ``ONLINE`` live_client source): each a trusted handler
  material + a serialized :class:`DataSourceDescriptor` "source-config" material, bound
  **behind the EXISTING Phase-3 method / capability ids**. A worker that already holds
  the Phase-3 data capabilities reaches the new sources purely through ``DataMode``
  routing at runtime, so the catalog adds **no new method id, no new capability id, no
  worker-allowlist edit and no new worker id** — the reviewed 27-worker table is
  inherited byte-identical and its final-worker count is UNCHANGED (proven against the
  base, never a hardcoded integer — the 枚举钉旧 vaccine). No order/signal write
  capability enters the snapshot; every bound method spec is ``read_only``.

**EventType decision (explicit).** Phase 9 adds **no** ``EventType`` member and flips
**no** Phase-1 absence guard; a test pins the Phase-8 ``EventType`` value set unchanged.
The retirement / run-record durability events are Task-12 run-record concerns, not new
enum members here.

**Provenance-into-DeterministicTargetSet disposition (carried from Task 5 review).**
``DeterministicTargetSet`` is **Phase-6-owned and deliberately UNREGISTERED**: it is an
``adapters.luozi`` contract classified into the Phase-6 INTERNAL map
(``shadow.PHASE6_INTERNAL_MODELS``, reason ``_R6_DETERMINISTIC`` — "an internal
deterministic dual-curve target-set carrier … a rule-computed book record, never a
registered payload"), so it holds **no** schema-registry entry in any chain node (there
is no ``DeterministicTargetSet@1`` key in the Phase-8 or the Phase-9 manifest).
Extending it to bind provenance would therefore be a **Phase-6 contract change** —
reopening a sealed upstream phase's reviewed public/internal partition and editing its
owning module — which is out of Phase-9 scope: Phase 9 is additive over the sealed
Phase-8 chain and never edits an upstream contract. The disposition is therefore **no
contract extension**; run-level provenance binding is owned by the **Task-12 run
record**, which carries the ``factor_report_digest`` / catalog-digest / registry-digest
bindings at the run granularity where they belong. Reasoned in full — including the two
arguments explicitly REJECTED as unsound — in the task report §4.

Both goldens (``phase9_schema_manifest_v1.json`` / ``phase9_catalog_manifest_v1.json``)
are hand-frozen from a one-off verification run and never auto-regenerated by a test.
"""
from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

from guanlan_v2.orchestration.adapters.contracts import (
    DualCurveReport,
    EntryPointRetirementGate,
    MirrorHarnessCaseResult,
    MirrorHarnessReport,
    ReplayDecisionPoint,
    ReplayWakeupReceipt,
    RetirementCriterion,
    RetirementCriterionResult,
    RetirementReadinessReport,
    ShadowCurvePoint,
    ShadowCurveSeries,
    ShadowExecutionConfig,
    ShadowReplayRunState,
)
from guanlan_v2.orchestration.adapters.live_data import (
    LiveClientSource,
    build_online_live_descriptor,
)
from guanlan_v2.orchestration.adapters.luozi import ReplayRuntimeBindings
from guanlan_v2.orchestration.adapters.replay_data import (
    PitReaderRawSource,
    ReplayPointClock,
    build_pit_replay_descriptor,
)
from guanlan_v2.orchestration.adapters.weiwo import (
    WeiwoRuntimeBindings,
    WeiwoRunReceipt,
)
from guanlan_v2.orchestration.catalog import (
    CatalogError,
    ContentManifestEntry,
    ResolvedMaterial,
    ResolvedTextMaterial,
    WorkerCatalogSnapshot,
    validate_catalog_snapshot,
)
from guanlan_v2.orchestration.catalog_runtime import build_text_material
from guanlan_v2.orchestration.data.catalog import (
    data_capability_refs,
    phase3_data_surface,
)
from guanlan_v2.orchestration.data.source import DataMethodSpec, DataSourceDescriptor
from guanlan_v2.orchestration.digest import ContractModel, DigestHex
from guanlan_v2.orchestration.enums import DataMode

if TYPE_CHECKING:  # pragma: no cover - typing only (avoids an import cycle at runtime)
    from guanlan_v2.orchestration.runtime_contracts import Phase2RuntimeRegistry

__all__ = [
    # registry
    "PHASE9_PUBLIC_MODELS",
    "Phase9RegistryError",
    "build_phase9_registry",
    # catalog
    "PHASE9_CATALOG_VERSION",
    "PHASE9_SOURCE_IDENTITY",
    "build_phase9_source_materials",
    "build_phase9_catalog_snapshot",
    "phase9_catalog_snapshot",
    "serialize_source_descriptor",
    # lazy (PEP 562) constants
    "PHASE9_INTERNAL_MODELS",  # noqa: F822 — lazy via module __getattr__
    "PHASE9_BASE_REGISTRY_DIGEST",  # noqa: F822 — lazy via module __getattr__
    "PHASE9_REGISTRY_DIGEST",  # noqa: F822 — lazy via module __getattr__
    "PHASE9_BASE_CATALOG_DIGEST",  # noqa: F822 — lazy via module __getattr__
    "PHASE9_CATALOG_DIGEST",  # noqa: F822 — lazy via module __getattr__
]


# =========================================================================== #
# The reviewed Phase-9 public / internal contract partition                     #
# =========================================================================== #
#: the exactly-nine registered Phase-9 payload contracts the Phase-9 cumulative
#: registry resolves a :class:`SchemaRef` to (all owned by ``adapters.contracts``,
#: Task 1). Ordered by the replay → dual-curve → run-state → harness → retirement
#: consumption chain the phase reads them in.
PHASE9_PUBLIC_MODELS: tuple[type[ContractModel], ...] = (
    ReplayDecisionPoint,
    ShadowExecutionConfig,
    ShadowCurveSeries,
    DualCurveReport,
    ShadowReplayRunState,
    ReplayWakeupReceipt,
    MirrorHarnessReport,
    EntryPointRetirementGate,
    RetirementReadinessReport,
)


_R9_VALUE_OBJECT = (
    "internal nested value object / component of a registered Phase-9 payload; a "
    "structural sub-record surfaced only inside its owning report's semantic "
    "projection (it carries no independent schema_version), never a standalone "
    "cross-boundary payload"
)
_R9_RUN_CONTEXT_CARRIER = (
    "internal run-context binding carrier (a frozen dataclass, not a ContractModel); "
    "a per-run wiring/receipt value the driver threads between the frozen DataContext "
    "and the adapter services, never a registered cross-boundary payload"
)
_R9_SERVICE_PORT = (
    "internal service port / adapter object (not a ContractModel at all — a plain "
    "service class); the frozen replay clock / raw data-source adapters reached only "
    "behind the Phase-3 dispatch route, never a registered schema-registry payload"
)


def _phase9_internal_models() -> "dict[type, str]":
    """The reviewed ``type -> reason`` map of every Phase-9 identity deliberately NOT
    registered.

    Two categories partition it, following the Phase-1 taxonomy:

    * **value objects** — the four nested :class:`ContractModel` components of the
      registered reports (``ShadowCurvePoint`` / ``MirrorHarnessCaseResult`` /
      ``RetirementCriterion`` / ``RetirementCriterionResult``): together with
      :data:`PHASE9_PUBLIC_MODELS` they partition the discovered Phase-9 ContractModel
      surface exactly (proved by ``test_phase9_registry_chain.py``);
    * **run-context carriers + service ports** — the six non-``ContractModel`` adapter
      identities (``ReplayRuntimeBindings`` / ``WeiwoRuntimeBindings`` /
      ``WeiwoRunReceipt`` frozen dataclasses; ``ReplayPointClock`` /
      ``PitReaderRawSource`` / ``LiveClientSource`` service objects). They can never be
      registered (they are not ContractModels), and are documented here so the phase's
      unregistered surface is honestly and exhaustively reviewed.
    """
    return {
        # -- nested value objects (registered reports' components) ------------- #
        ShadowCurvePoint: _R9_VALUE_OBJECT,
        MirrorHarnessCaseResult: _R9_VALUE_OBJECT,
        RetirementCriterion: _R9_VALUE_OBJECT,
        RetirementCriterionResult: _R9_VALUE_OBJECT,
        # -- run-context carriers (frozen dataclasses) ------------------------- #
        ReplayRuntimeBindings: _R9_RUN_CONTEXT_CARRIER,
        WeiwoRuntimeBindings: _R9_RUN_CONTEXT_CARRIER,
        WeiwoRunReceipt: _R9_RUN_CONTEXT_CARRIER,
        # -- service ports (adapter objects) ----------------------------------- #
        ReplayPointClock: _R9_SERVICE_PORT,
        PitReaderRawSource: _R9_SERVICE_PORT,
        LiveClientSource: _R9_SERVICE_PORT,
    }


# =========================================================================== #
# The cumulative Phase-9 schema registry (linear chain over Phase 8)            #
# =========================================================================== #
class Phase9RegistryError(Exception):
    """A Phase-9 cumulative-registry construction invariant was violated."""


def _phase8_registry_digest() -> str:
    from guanlan_v2.orchestration import lane_catalog as p8

    return p8.PHASE8_REGISTRY_DIGEST


def _phase8_catalog_digest() -> str:
    from guanlan_v2.orchestration import lane_catalog as p8

    return p8.PHASE8_CATALOG_DIGEST


def build_phase9_registry(
    expected_phase8_digest: "DigestHex",
) -> "Phase2RuntimeRegistry":
    """Build + seal the cumulative Phase-9 registry, pinned to the Phase-8 base.

    (Return-type note: the brief writes ``-> SchemaRegistry``; the sealed cumulative
    registry every chain node from Phase 2 onward actually builds is the Phase-2
    :class:`~guanlan_v2.orchestration.runtime_contracts.Phase2RuntimeRegistry`, which is
    NOT a ``schema_registry.SchemaRegistry`` subclass — annotating ``SchemaRegistry``
    would be false. Bound to the real type, exactly like the ``get_ohlcv`` → ``ohlcv``
    method-id correction; recorded in the task report.)

    Verifies ``expected_phase8_digest`` against the actual sealed Phase-8 cumulative
    registry digest first — any other base digest is rejected *before any
    registration* — then registers the complete inherited cumulative set (Phase-1
    public + Phase-2 runtime facts + Phase-3 data + Phase-3 memory + Phase-4
    Evaluator-Optimizer + Phase-5 Bootstrap Lane 0 + Phase-6 shadow + Phase-7
    dynamic-planner + Phase-8 lane payloads) followed by :data:`PHASE9_PUBLIC_MODELS`
    into a *fresh*
    :class:`~guanlan_v2.orchestration.runtime_contracts.Phase2RuntimeRegistry` and
    seals it. No upstream registry is mutated; a fresh sealed instance is returned per
    call. Inherited JSON Schemas stay byte-identical to their Phase-<=8 goldens; there
    is no "latest" alias.
    """
    from guanlan_v2.orchestration import (
        bootstrap,
        lane_catalog as p8,
        phase7_registry as p7,
        shadow,
        trial,
    )
    from guanlan_v2.orchestration.data.schema_registry import (
        PHASE3_PUBLIC_MODELS as _DATA_PUBLIC,
    )
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_MEMORY_PUBLIC_MODELS as _MEM_PUBLIC,
    )
    from guanlan_v2.orchestration.runtime_contracts import (
        Phase2RuntimeRegistry,
        phase2_public_models,
    )

    actual = p8.PHASE8_REGISTRY_DIGEST
    if expected_phase8_digest != actual:
        raise Phase9RegistryError(
            "build_phase9_registry requires the exact Phase-8 registry digest "
            f"{actual!r}; got {expected_phase8_digest!r}"
        )
    reg = Phase2RuntimeRegistry()
    for model in (
        tuple(phase2_public_models())
        + tuple(_DATA_PUBLIC)
        + tuple(_MEM_PUBLIC)
        + tuple(trial.PHASE4_PUBLIC_MODELS)
        + tuple(bootstrap.PHASE5_PUBLIC_MODELS)
        + tuple(shadow.PHASE6_PUBLIC_MODELS)
        + tuple(p7.PHASE7_PUBLIC_MODELS)
        + tuple(p8.PHASE8_PUBLIC_MODELS)
        + PHASE9_PUBLIC_MODELS
    ):
        reg.register(model)
    reg.seal()
    return reg


# =========================================================================== #
# The Phase-9 catalog: two adapter source materials, ZERO new workers            #
# =========================================================================== #
#: the merged cumulative Phase-9 catalog version.
PHASE9_CATALOG_VERSION = "phase9-full-v1"

#: the reviewed provenance ``LogicalId`` stamped on every Phase-9-owned manifest entry
#: (a single reviewed source identity, mirroring the ``lane_catalog`` Phase-8
#: ``_PHASE8_SOURCE_IDENTITY`` and Phase-7 ``PLANNER_SOURCE_IDENTITY`` precedents).
PHASE9_SOURCE_IDENTITY = "guanlan.orchestration.phase9"

#: the two adapter source materials' logical ids (handler bytes + serialized descriptor).
_PIT_REPLAY_HANDLER_ID = "data.source.pit_replay"
_PIT_REPLAY_DESCRIPTOR_ID = "data.source.pit_replay.descriptor"
_ONLINE_HANDLER_ID = "data.source.online_live"
_ONLINE_DESCRIPTOR_ID = "data.source.online_live.descriptor"

#: the trusted source-adapter handler marker bytes. These are reviewed catalog
#: material only (the runtime binds the real ``PitReaderRawSource`` / ``LiveClientSource``
#: service object by id at wiring time — Task 10); the bytes never carry credentials
#: or physical paths, exactly like the Phase-3 ``data.source.guanlan_datafeed`` handler.
_PIT_REPLAY_HANDLER_BYTES = (
    b"# data.source.pit_replay v1\n"
    b"Trusted PIT_REPLAY raw data-source adapter handler (engine PitReader).\n"
    b"Reads the frozen pit_store at a decision point's decision_as_of; every row is\n"
    b"forwarded to the Phase-3 dispatch PitGuard (never pre-filtered by time). Bound\n"
    b"behind the existing ohlcv/news method ids; PIT_REPLAY-only, PIT_STORE backend.\n"
)
_ONLINE_HANDLER_BYTES = (
    b"# data.source.online_live v1\n"
    b"Trusted ONLINE raw data-source adapter handler (guanlan datafeed live_client).\n"
    b"Reads the live portal at the run's start-frozen as_of; every row is forwarded to\n"
    b"the Phase-3 dispatch PitGuard (a pulled_at after run start is refused). Bound\n"
    b"behind the existing verified_snapshot/news/ohlcv method ids; ONLINE-only, LIVE\n"
    b"backend. Registers no order/signal write capability.\n"
)

#: the existing Phase-3 method ids each adapter binds (no new id is ever minted).
_PIT_REPLAY_METHOD_IDS = frozenset({"ohlcv", "news"})
_ONLINE_METHOD_IDS = frozenset({"verified_snapshot", "news", "ohlcv"})


def serialize_source_descriptor(descriptor: DataSourceDescriptor) -> bytes:
    """Serialize a :class:`DataSourceDescriptor` to deterministic canonical material bytes.

    Mirrors ``data.catalog.serialize_prefetch_binding`` — a sorted-key, ASCII-safe
    canonical JSON dump so the "source-config" catalog material's bytes (and therefore
    its content digest) are stable and reviewable, and encode the descriptor's own
    ``descriptor_digest``.
    """
    return json.dumps(
        descriptor.model_dump(mode="json"),
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")


def build_phase9_source_materials() -> tuple[
    DataSourceDescriptor, DataSourceDescriptor, tuple[ResolvedTextMaterial, ...]
]:
    """Build the two adapter :class:`DataSourceDescriptor`\\ s + their catalog materials.

    Resolves the existing Phase-3 data method specs, builds each adapter's trusted
    handler material, binds the descriptor behind the EXISTING method / capability ids
    (:func:`~guanlan_v2.orchestration.adapters.replay_data.build_pit_replay_descriptor`
    / :func:`~guanlan_v2.orchestration.adapters.live_data.build_online_live_descriptor`,
    each rejecting any minted id), and serializes the descriptor into a "source-config"
    guardrail material. Returns ``(replay_descriptor, live_descriptor, (four materials))``
    — two handler materials + two serialized-descriptor materials.
    """
    method_specs = phase3_data_surface().method_specs

    replay_handler_ref, replay_handler_mat = build_text_material(
        id=_PIT_REPLAY_HANDLER_ID, version="1", kind="handler",
        raw=_PIT_REPLAY_HANDLER_BYTES)
    online_handler_ref, online_handler_mat = build_text_material(
        id=_ONLINE_HANDLER_ID, version="1", kind="handler",
        raw=_ONLINE_HANDLER_BYTES)

    replay_desc = build_pit_replay_descriptor(
        method_specs=method_specs, handler_ref=replay_handler_ref)
    live_desc = build_online_live_descriptor(
        method_specs=method_specs, handler_ref=online_handler_ref)

    _replay_cfg_ref, replay_cfg_mat = build_text_material(
        id=_PIT_REPLAY_DESCRIPTOR_ID, version="1", kind="guardrail",
        raw=serialize_source_descriptor(replay_desc))
    _online_cfg_ref, online_cfg_mat = build_text_material(
        id=_ONLINE_DESCRIPTOR_ID, version="1", kind="guardrail",
        raw=serialize_source_descriptor(live_desc))

    return replay_desc, live_desc, (
        replay_handler_mat, replay_cfg_mat, online_handler_mat, online_cfg_mat,
    )


def _verify_source_descriptor(
    descriptor: DataSourceDescriptor,
    *,
    expected_mode: DataMode,
    expected_method_ids: frozenset[str],
    spec_by_ref: dict[tuple[str, str, str], DataMethodSpec],
    known_caps: set,
) -> None:
    """Reject any descriptor that mints a new method / capability id or a write method.

    * ``supported_modes`` must be exactly ``(expected_mode,)`` — the structural mode
      exclusion (a PIT_REPLAY read can never resolve the ONLINE source, and vice versa).
    * every ``method_ref`` must cross-resolve to an EXISTING Phase-3 data method spec
      whose ``read_only`` is ``True`` (no order/signal write capability); the bound set
      must equal ``expected_method_ids`` — no new ``DataMethodSpec`` id is minted.
    * every ``method_capability_ref`` must be one of the EXISTING Phase-3 data
      capabilities — no new capability id is minted.
    """
    if descriptor.supported_modes != (expected_mode,):
        raise CatalogError(
            f"source {descriptor.source_id!r} supported_modes "
            f"{descriptor.supported_modes} != the reviewed exclusive ({expected_mode},)"
        )
    bound_ids: set[str] = set()
    for mref in descriptor.method_refs:
        spec = spec_by_ref.get((mref.id, mref.version, mref.content_digest))
        if spec is None:
            raise CatalogError(
                f"source {descriptor.source_id!r} references a method "
                f"{mref.id}@{mref.version} that is not an existing Phase-3 data method "
                "spec (no new DataMethodSpec id may be minted)"
            )
        if not spec.read_only:
            raise CatalogError(
                f"source {descriptor.source_id!r} binds non-read method {mref.id!r} — "
                "the adapter sources register no order/signal write capability"
            )
        bound_ids.add(spec.method_id)
    if bound_ids != set(expected_method_ids):
        raise CatalogError(
            f"source {descriptor.source_id!r} binds method ids {sorted(bound_ids)} != "
            f"the reviewed existing set {sorted(expected_method_ids)}"
        )
    for cref in descriptor.method_capability_refs:
        if cref not in known_caps:
            raise CatalogError(
                f"source {descriptor.source_id!r} references capability "
                f"{cref.id}@{cref.version} that is not an existing Phase-3 data "
                "capability (no new capability id may be minted)"
            )


def _source_content_entries(
    descriptor: DataSourceDescriptor,
    handler_id: str,
    descriptor_id: str,
    materials_by_key: dict[tuple[str, str], ResolvedTextMaterial],
) -> tuple[ContentManifestEntry, ContentManifestEntry]:
    """Derive one source's (handler, source-config) manifest entries + verify materials.

    The descriptor's ``handler_ref`` must resolve to the handler material (kind
    ``handler``, digest match); the serialized-descriptor material (kind ``guardrail``)
    must encode this exact descriptor's bytes. Both become materials-without-worker
    content manifest entries stamped with the Phase-9 provenance identity.
    """
    handler_mat = materials_by_key.get((handler_id, "1"))
    if handler_mat is None or handler_mat.kind != "handler":
        raise CatalogError(
            f"source {descriptor.source_id!r} handler material {handler_id}@1 is "
            "missing or not a handler material"
        )
    if (descriptor.handler_ref.id, descriptor.handler_ref.version) != (handler_id, "1"):
        raise CatalogError(
            f"source {descriptor.source_id!r} handler_ref does not name {handler_id}@1"
        )
    if descriptor.handler_ref.content_digest != handler_mat.ref.content_digest:
        raise CatalogError(
            f"source {descriptor.source_id!r} handler_ref digest does not match its "
            "resolved handler material"
        )

    cfg_mat = materials_by_key.get((descriptor_id, "1"))
    if cfg_mat is None or cfg_mat.kind != "guardrail":
        raise CatalogError(
            f"source {descriptor.source_id!r} source-config material {descriptor_id}@1 "
            "is missing or not a guardrail material"
        )
    if cfg_mat.raw_utf8 != serialize_source_descriptor(descriptor):
        raise CatalogError(
            f"source {descriptor.source_id!r} source-config material does not encode "
            "the reviewed descriptor bytes"
        )

    handler_entry = ContentManifestEntry(
        ref=handler_mat.ref, kind="handler", name=handler_id,
        description=f"phase9 adapter source handler material: {handler_id}",
        source_identity=PHASE9_SOURCE_IDENTITY)
    cfg_entry = ContentManifestEntry(
        ref=cfg_mat.ref, kind="guardrail", name=descriptor_id,
        description=(
            f"phase9 adapter source-config (serialized DataSourceDescriptor "
            f"{descriptor.source_id}@{descriptor.source_version}, digest "
            f"{descriptor.descriptor_digest[:12]}…): {descriptor_id}"),
        source_identity=PHASE9_SOURCE_IDENTITY)
    return handler_entry, cfg_entry


def build_phase9_catalog_snapshot(
    phase8_snapshot: "WorkerCatalogSnapshot",
    *,
    replay_source_descriptor: DataSourceDescriptor,
    live_source_descriptor: DataSourceDescriptor,
    resolved_materials: tuple[ResolvedMaterial, ...],
) -> "WorkerCatalogSnapshot":
    """Extend the immutable Phase-8 catalog with the two adapter source materials.

    Rejects any base whose ``catalog_digest`` differs from the canonical Phase-8
    cumulative catalog digest (the sole legal base). Cross-checks both descriptors
    against the EXISTING Phase-3 data surface (no new method / capability id; every
    bound method ``read_only``; the structural PIT_REPLAY/ONLINE mode exclusion), then
    adds ONLY each source's handler + serialized-descriptor content materials — **no**
    ``WorkerSpec``, **no** capability, **no** worker-allowlist edit. Every inherited
    Phase-8 worker / skill / capability / content entry passes through byte-identical;
    the final-worker count is therefore unchanged. The merge rejects any id collision,
    sorts the set-like manifests, seals the cumulative ``catalog_digest`` and
    re-validates every cross-reference.
    """
    base_digest = _phase8_catalog_digest()
    if phase8_snapshot.catalog_digest != base_digest:
        raise CatalogError(
            "build_phase9_catalog_snapshot requires the canonical immutable Phase-8 "
            f"catalog ({base_digest}); got base {phase8_snapshot.catalog_digest}"
        )

    # -- cross-check the two descriptors against the existing Phase-3 surface -- #
    surface = phase3_data_surface()
    spec_by_ref = {
        (s.method_id, s.method_version, s.spec_digest): s for s in surface.method_specs
    }
    known_caps = set(data_capability_refs().values())
    _verify_source_descriptor(
        replay_source_descriptor, expected_mode=DataMode.PIT_REPLAY,
        expected_method_ids=_PIT_REPLAY_METHOD_IDS, spec_by_ref=spec_by_ref,
        known_caps=known_caps)
    _verify_source_descriptor(
        live_source_descriptor, expected_mode=DataMode.ONLINE,
        expected_method_ids=_ONLINE_METHOD_IDS, spec_by_ref=spec_by_ref,
        known_caps=known_caps)

    # -- index + verify the four source materials ---------------------------- #
    materials_by_key: dict[tuple[str, str], ResolvedTextMaterial] = {}
    for m in resolved_materials:
        if not isinstance(m, ResolvedTextMaterial):
            raise CatalogError(
                f"phase9 source materials must be text materials; got {type(m).__name__}"
            )
        if m.ref_key in materials_by_key:
            raise CatalogError(f"duplicate phase9 source material {m.ref_key}")
        materials_by_key[m.ref_key] = m

    replay_handler_e, replay_cfg_e = _source_content_entries(
        replay_source_descriptor, _PIT_REPLAY_HANDLER_ID, _PIT_REPLAY_DESCRIPTOR_ID,
        materials_by_key)
    online_handler_e, online_cfg_e = _source_content_entries(
        live_source_descriptor, _ONLINE_HANDLER_ID, _ONLINE_DESCRIPTOR_ID,
        materials_by_key)
    new_content = (replay_handler_e, replay_cfg_e, online_handler_e, online_cfg_e)

    expected_new = {
        (_PIT_REPLAY_HANDLER_ID, "1"), (_PIT_REPLAY_DESCRIPTOR_ID, "1"),
        (_ONLINE_HANDLER_ID, "1"), (_ONLINE_DESCRIPTOR_ID, "1"),
    }
    if set(materials_by_key) != expected_new:
        extra = sorted(set(materials_by_key) - expected_new)
        raise CatalogError(
            f"phase9 catalog received unreviewed extra source material(s): {extra}"
        )

    # -- merge: inherit everything byte-identical + add the four new entries -- #
    base_content_keys = {e.ref_key for e in phase8_snapshot.content_manifest}
    for e in new_content:
        if e.ref_key in base_content_keys:
            raise CatalogError(
                f"phase9 source material {e.ref_key} collides with an inherited "
                "Phase-8 content entry (a new source material must carry a fresh id)"
            )

    content_sorted = tuple(sorted(
        tuple(phase8_snapshot.content_manifest) + new_content, key=lambda e: e.ref_key))
    skill_sorted = tuple(phase8_snapshot.skill_manifest)
    cap_sorted = tuple(phase8_snapshot.capability_manifest)
    workers_sorted = tuple(phase8_snapshot.workers)

    fields: dict[str, Any] = dict(
        catalog_version=PHASE9_CATALOG_VERSION,
        content_manifest=content_sorted,
        skill_manifest=skill_sorted,
        capability_manifest=cap_sorted,
        workers=workers_sorted,
    )
    try:
        digest = WorkerCatalogSnapshot.digest_of_fields(projection="semantic", **fields)
    except (ValueError, TypeError, AttributeError, KeyError):
        digest = "0" * 64
    try:
        snapshot = WorkerCatalogSnapshot(**fields, catalog_digest=digest)
    except Exception as exc:  # surface structural failures as CatalogError
        raise CatalogError(f"phase9 catalog snapshot is not runnable: {exc}") from exc
    validate_catalog_snapshot(snapshot)
    return snapshot


def phase9_catalog_snapshot() -> "WorkerCatalogSnapshot":
    """The canonical cumulative Phase-9 catalog snapshot (the final adapter seal).

    Rebuilds the reviewed Phase-8 catalog the same way its owning module assembles it,
    builds the two adapter source descriptors + materials, and merges them through
    :func:`build_phase9_catalog_snapshot`.
    """
    from guanlan_v2.orchestration import lane_catalog as p8

    base = p8.phase8_catalog_snapshot()
    replay_desc, live_desc, materials = build_phase9_source_materials()
    return build_phase9_catalog_snapshot(
        base,
        replay_source_descriptor=replay_desc,
        live_source_descriptor=live_desc,
        resolved_materials=materials,
    )


# --------------------------------------------------------------------------- #
# Lazy canonical digests (PEP 562) — computed once, never a mutable "latest"    #
# --------------------------------------------------------------------------- #
_PHASE9_REGISTRY_DIGEST: str | None = None
_PHASE9_CATALOG_DIGEST: str | None = None
_PHASE9_INTERNAL_MODELS: "dict[type, str] | None" = None


def __getattr__(name: str) -> "Any":
    global _PHASE9_REGISTRY_DIGEST, _PHASE9_CATALOG_DIGEST, _PHASE9_INTERNAL_MODELS
    if name == "PHASE9_INTERNAL_MODELS":
        if _PHASE9_INTERNAL_MODELS is None:
            _PHASE9_INTERNAL_MODELS = _phase9_internal_models()
        return _PHASE9_INTERNAL_MODELS
    if name == "PHASE9_BASE_REGISTRY_DIGEST":
        return _phase8_registry_digest()
    if name == "PHASE9_REGISTRY_DIGEST":
        if _PHASE9_REGISTRY_DIGEST is None:
            _PHASE9_REGISTRY_DIGEST = build_phase9_registry(
                _phase8_registry_digest()
            ).registry_digest
        return _PHASE9_REGISTRY_DIGEST
    if name == "PHASE9_BASE_CATALOG_DIGEST":
        return _phase8_catalog_digest()
    if name == "PHASE9_CATALOG_DIGEST":
        if _PHASE9_CATALOG_DIGEST is None:
            _PHASE9_CATALOG_DIGEST = phase9_catalog_snapshot().catalog_digest
        return _PHASE9_CATALOG_DIGEST
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
