# -*- coding: utf-8 -*-
"""Phase 6 · Task 10 — cumulative Phase-6 registry / catalog chain + goldens.

Locks the linear registry/catalog chain the shadow-consumer phase contributes,
built as a pure ADDITION over the sealed Phase-5 chain (never a fork, never a
"latest" alias):

* ``build_phase6_registry(expected_phase5_digest)`` builds a *fresh sealed*
  cumulative registry over the exact Phase-5 cumulative set (Phase-1 public +
  Phase-2 runtime facts + Phase-3 data + Phase-3 memory + Phase-4
  Evaluator-Optimizer + Phase-5 Bootstrap Lane 0) plus the reviewed
  :data:`PHASE6_PUBLIC_MODELS` (the ten shadow-consumer payloads); a wrong base
  digest is rejected before any registration; inherited entries stay
  byte-identical to their Phase-≤5 goldens; the digest is registration-order
  independent and matches the hand-reviewed golden;
* ``build_phase6_catalog_snapshot(phase5_snapshot, expected_phase5_digest)`` is
  the **explicit identity chain node** — Phase 6 adds ZERO workers and ZERO
  capabilities (a red-line fact: no live order/signal write tool enters through
  this phase). It verifies its base and returns the snapshot unchanged;
  ``PHASE6_CATALOG_DIGEST`` is RECORDED equal to ``PHASE5_CATALOG_DIGEST`` (never
  aliased);
* the Phase-6 public/internal partition over the two Phase-6 contract modules
  (``shadow`` + ``adapters.luozi``) is exhaustive and disjoint — ``TrancheTrigger``
  is a nested frozen sub-model (no independent ``schema_version``) classified
  INTERNAL, entering the registry only through ``TargetPosition@1``'s JSON schema;
* the sink-authorization invariant now bites for real: a ``PlanDraft`` whose
  sink's primary output schema is ``PortfolioTargetProposal@1`` (resolvable in the
  Phase-6 registry) validates only when the emitting worker has
  ``can_emit_decision=True`` — otherwise Phase-1 ``validate_plan_draft`` reports
  ``unauthorized_decision_sink`` with ZERO ``spec.py`` changes;
* old Plans binding any upstream digest stay resolvable side-by-side through the
  ``SchemaRegistryResolver`` — no reinterpretation, no "latest".

Goldens are NEVER auto-regenerated by tests: a changed manifest is a reviewed
contract change regenerated by hand and re-reviewed.

Run: ``pytest tests/orchestration/test_phase6_registry.py -v``
"""
from __future__ import annotations

import hashlib
import importlib
import inspect
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

import pytest

from guanlan_v2.orchestration import bootstrap, shadow, trial
from guanlan_v2.orchestration.catalog import (
    ContentManifestEntry,
    EvidencePolicy,
    ExecutionSpec,
    OutputBinding,
    ResolvedTextMaterial,
    WorkerSpec,
    build_catalog_snapshot,
    catalog_material_digest,
    count_final_workers,
)
from guanlan_v2.orchestration.context import (
    ClockSpec,
    ContextSnapshot,
    DataContext,
    build_empty_memory_binding,
)
from guanlan_v2.orchestration.digest import (
    CJSON_VERSION,
    ContractModel,
    DigestModel,
    content_digest,
)
from guanlan_v2.orchestration.enums import (
    ApprovalPolicy,
    DataBackend,
    DataMode,
    ExecutionKind,
    PlanSource,
    Tier,
)
from guanlan_v2.orchestration.refs import ContentRef, PayloadRef, SchemaRef, TypedPayloadRef
from guanlan_v2.orchestration.spec import (
    OrchestrationRequest,
    PlanDraft,
    PlanNode,
    validate_plan_draft,
)

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
SCHEMA_GOLDEN = GOLDEN_DIR / "phase6_schema_manifest_v1.json"
CATALOG_GOLDEN = GOLDEN_DIR / "phase6_catalog_manifest_v1.json"

#: sha256 pins of the upstream goldens — Phase 6 never regenerates any of them.
UPSTREAM_GOLDEN_SHA256 = {
    "schema_manifest_v1.json":
        "5de22e4727f874c4b1c53d1da6a82bb8666a2a85ae97a5b551280c687cae92d8",
    "phase5_schema_manifest_v1.json":
        "879c91c02e967930b8dfc6ddb49683f09d1607e12c39e83be2dd5b07fe294d99",
    "phase5_catalog_manifest_v1.json":
        "6cc05be9ebefc019e7b64e399ad4ca906424f067fe4725716529d04b7707fc88",
}

#: the two Phase-6 contract modules the completeness firewall governs.
PHASE6_CONTRACT_MODULES = (
    "guanlan_v2.orchestration.shadow",
    "guanlan_v2.orchestration.adapters.luozi",
)

#: the ten reviewed names the registered Phase-6 surface must equal (CRIB order).
EXPECTED_PUBLIC_NAMES = frozenset({
    "TargetPosition", "PortfolioTargetProposal", "TargetPortfolioIntent",
    "DecisionSchedule", "ShadowTargetApplyRecord", "ShadowOrderRecord",
    "ShadowFillRecord", "ShadowRejectRecord", "ShadowRunResult",
    "CorporateActionEvent",
})

#: the ten reviewed INTERNAL Phase-6 contract names (TrancheTrigger nested +
#: nine luozi carriers) the partition must equal.
EXPECTED_INTERNAL_NAMES = frozenset({
    "TrancheTrigger",
    "ShadowOrderPlanEntry", "ShadowOrderSkip", "ShadowOrderPlan",
    "DeterministicTargetSet", "CorporateActionApplication",
    "CompatSignal", "CompatClock", "CompatTrade", "CompatibilityRunResult",
})

#: the four Phase-6 payload names whose deferred-absence guards Task 10 flips.
FLIPPED_DEFERRED_NAMES = (
    "TargetPosition", "PortfolioTargetProposal", "TargetPortfolioIntent",
    "DecisionSchedule",
)

#: still-deferred Phase-8 payloads — absent from every registry in the chain.
STILL_DEFERRED_NAMES = ("DebateMessage",)


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _discover_phase6_contract_models() -> set[type]:
    found: set[type] = set()
    for module_name in PHASE6_CONTRACT_MODULES:
        module = importlib.import_module(module_name)
        for obj in vars(module).values():
            if (
                inspect.isclass(obj)
                and issubclass(obj, ContractModel)
                and obj not in (ContractModel, DigestModel)
                and obj.__module__ == module_name
                and not obj.__name__.startswith("_")
            ):
                found.add(obj)
    return found


# =========================================================================== #
# Point 1 — build rejects a wrong base; the correct base seals the right digest #
# =========================================================================== #
def test_build_phase6_registry_rejects_a_wrong_expected_digest():
    with pytest.raises(shadow.Phase6RegistryError):
        shadow.build_phase6_registry("0" * 64)


def test_build_phase6_registry_seals_and_matches_the_frozen_digest():
    reg = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    assert reg.sealed is True
    assert reg.registry_digest == shadow.PHASE6_REGISTRY_DIGEST
    # a fresh sealed instance per call (never a shared mutable singleton).
    other = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    assert other is not reg
    assert other.registry_digest == reg.registry_digest


def test_phase6_base_registry_digest_is_the_phase5_digest():
    assert shadow.PHASE6_BASE_REGISTRY_DIGEST == bootstrap.PHASE5_REGISTRY_DIGEST
    assert shadow.PHASE6_REGISTRY_DIGEST != shadow.PHASE6_BASE_REGISTRY_DIGEST


# =========================================================================== #
# Point 2 — golden equality; inherited byte-identical; upstream goldens frozen   #
# =========================================================================== #
def test_registry_matches_the_frozen_golden_entry_for_entry():
    assert SCHEMA_GOLDEN.exists(), f"missing golden: {SCHEMA_GOLDEN}"
    doc = _load_json(SCHEMA_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION == "sha256+cjson-v1"
    assert doc["base_registry_digest"] == bootstrap.PHASE5_REGISTRY_DIGEST
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    reg = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    assert set(manifest) == set(golden), (
        "phase6 registry key set drifted from phase6_schema_manifest_v1.json; "
        "regenerate + re-review by hand if intended"
    )
    for key in sorted(golden):
        assert manifest[key] == golden[key], f"JSON-schema digest drift for {key}"
    assert reg.registry_digest == doc["registry_digest"]


def test_inherited_entries_are_byte_identical_to_the_phase5_golden():
    phase5_doc = _load_json(GOLDEN_DIR / "phase5_schema_manifest_v1.json")
    phase5 = {e["key"]: e["json_schema_digest"] for e in phase5_doc["entries"]}
    reg = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    # every Phase-5 (cumulative) key is inherited byte-identical …
    for key, digest in phase5.items():
        assert manifest[key] == digest, f"inherited schema {key} drifted in phase6"
    # … and the only new keys are exactly the ten Phase-6 public contracts.
    new_keys = set(manifest) - set(phase5)
    assert {k.split("@")[0] for k in new_keys} == EXPECTED_PUBLIC_NAMES
    assert len(new_keys) == 10


def test_new_public_contract_digests_are_recomputable_from_the_models():
    doc = _load_json(SCHEMA_GOLDEN)
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    for model in shadow.PHASE6_PUBLIC_MODELS:
        key = f"{model.__name__}@{model.model_fields['schema_version'].default}"
        assert golden[key] == content_digest(model.model_json_schema())


def test_upstream_goldens_are_byte_unchanged():
    for fname, sha in UPSTREAM_GOLDEN_SHA256.items():
        raw = (GOLDEN_DIR / fname).read_bytes()
        assert hashlib.sha256(raw).hexdigest() == sha, (
            f"upstream golden {fname} changed — Phase 6 must never regenerate it"
        )


# =========================================================================== #
# Point 3 — registration-order independence                                     #
# =========================================================================== #
def test_registration_order_independence():
    from guanlan_v2.orchestration.data.schema_registry import (
        PHASE3_PUBLIC_MODELS as DATA_PUBLIC,
    )
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_MEMORY_PUBLIC_MODELS as MEM_PUBLIC,
    )
    from guanlan_v2.orchestration.runtime_contracts import (
        Phase2RuntimeRegistry,
        phase2_public_models,
    )

    canonical = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    reversed_reg = Phase2RuntimeRegistry()
    for model in reversed(
        tuple(phase2_public_models())
        + tuple(DATA_PUBLIC)
        + tuple(MEM_PUBLIC)
        + tuple(trial.PHASE4_PUBLIC_MODELS)
        + tuple(bootstrap.PHASE5_PUBLIC_MODELS)
        + tuple(shadow.PHASE6_PUBLIC_MODELS)
    ):
        reversed_reg.register(model)
    reversed_reg.seal()
    assert reversed_reg.manifest() == canonical.manifest()
    assert reversed_reg.registry_digest == canonical.registry_digest


# =========================================================================== #
# Point 4 — Phase-6 completeness firewall (exhaustive + disjoint)               #
# =========================================================================== #
def test_public_tuple_shape_and_names():
    assert isinstance(shadow.PHASE6_PUBLIC_MODELS, tuple)
    assert len(shadow.PHASE6_PUBLIC_MODELS) == 10
    assert len(set(shadow.PHASE6_PUBLIC_MODELS)) == 10
    names = {m.__name__ for m in shadow.PHASE6_PUBLIC_MODELS}
    assert names == EXPECTED_PUBLIC_NAMES
    for model in shadow.PHASE6_PUBLIC_MODELS:
        assert issubclass(model, ContractModel)


def test_internal_map_is_a_contract_model_reason_map():
    assert isinstance(shadow.PHASE6_INTERNAL_MODELS, dict)
    names = {m.__name__ for m in shadow.PHASE6_INTERNAL_MODELS}
    assert names == EXPECTED_INTERNAL_NAMES
    for model, reason in shadow.PHASE6_INTERNAL_MODELS.items():
        assert isinstance(model, type) and issubclass(model, ContractModel)
        assert isinstance(reason, str) and reason.strip()


def test_tranche_trigger_is_a_nested_internal_not_registered():
    # TrancheTrigger has no independent schema_version — it versions/digests only
    # through TargetPosition@1, so it is INTERNAL (nested) and never registered.
    assert shadow.TrancheTrigger in shadow.PHASE6_INTERNAL_MODELS
    assert shadow.TrancheTrigger not in shadow.PHASE6_PUBLIC_MODELS
    assert "schema_version" not in shadow.TrancheTrigger.model_fields
    reason = shadow.PHASE6_INTERNAL_MODELS[shadow.TrancheTrigger].lower()
    assert "nested" in reason
    p6 = {
        e.schema_ref.name
        for e in shadow.build_phase6_registry(
            shadow.PHASE6_BASE_REGISTRY_DIGEST
        ).manifest()
    }
    assert "TrancheTrigger" not in p6
    # it DOES enter the registry through TargetPosition@1's JSON schema.
    tp_schema = json.dumps(shadow.TargetPosition.model_json_schema())
    assert "TrancheTrigger" in tp_schema


def test_public_and_internal_partition_the_two_module_surface_exactly():
    discovered = _discover_phase6_contract_models()
    public = set(shadow.PHASE6_PUBLIC_MODELS)
    internal = set(shadow.PHASE6_INTERNAL_MODELS)
    classified = public | internal
    assert not (public & internal), "a Phase-6 contract cannot be both registered and internal"
    unclassified = discovered - classified
    assert not unclassified, (
        "unreviewed Phase-6 public contracts: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in unclassified))
    )
    phantom = classified - discovered
    assert not phantom, (
        "classified models not discovered in the two Phase-6 modules: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in phantom))
    )
    assert classified == discovered
    assert len(public) + len(internal) == len(discovered)


def test_every_public_member_has_a_closed_schema_version():
    for model in shadow.PHASE6_PUBLIC_MODELS:
        field = model.model_fields.get("schema_version")
        assert field is not None
        assert isinstance(field.default, str) and field.default, model.__name__


def test_default_registry_does_not_register_any_phase6_public_model():
    from guanlan_v2.orchestration.schema_registry import default_registry
    registered = {e.schema_ref.name for e in default_registry().manifest()}
    for model in shadow.PHASE6_PUBLIC_MODELS:
        assert model.__name__ not in registered, model.__name__


# =========================================================================== #
# Point 5 — catalog: the identity chain node (zero workers, zero capabilities)   #
# =========================================================================== #
def test_build_phase6_catalog_rejects_a_non_canonical_base():
    from guanlan_v2.orchestration.catalog import CatalogError

    # a Phase-4 catalog is not the legal Phase-5 base for the identity node.
    with pytest.raises(CatalogError):
        shadow.build_phase6_catalog_snapshot(
            trial.phase4_catalog_snapshot(),
            expected_phase5_digest=bootstrap.PHASE5_CATALOG_DIGEST,
        )
    # the canonical Phase-5 snapshot with a WRONG expected digest is also rejected.
    with pytest.raises(CatalogError):
        shadow.build_phase6_catalog_snapshot(
            bootstrap.phase5_catalog_snapshot(), expected_phase5_digest="0" * 64
        )


def test_phase6_catalog_is_the_identity_node():
    base = bootstrap.phase5_catalog_snapshot()
    snap = shadow.build_phase6_catalog_snapshot(
        base, expected_phase5_digest=bootstrap.PHASE5_CATALOG_DIGEST
    )
    # identity: the very same snapshot passes through unchanged.
    assert snap is base
    assert snap.catalog_digest == shadow.PHASE6_CATALOG_DIGEST
    # Phase 6 adds ZERO workers and ZERO capabilities (the red-line emptiness).
    assert count_final_workers(snap) == count_final_workers(base)
    assert snap.workers == base.workers
    assert snap.capability_manifest == base.capability_manifest
    assert snap.content_manifest == base.content_manifest
    assert snap.skill_manifest == base.skill_manifest


def test_phase6_catalog_digest_recorded_equal_to_phase5_not_aliased():
    # RECORDED equal (a re-derived constant), never aliased to the Phase-5 name.
    assert shadow.PHASE6_CATALOG_DIGEST == bootstrap.PHASE5_CATALOG_DIGEST
    assert shadow.PHASE6_BASE_CATALOG_DIGEST == bootstrap.PHASE5_CATALOG_DIGEST


def test_phase6_catalog_matches_the_frozen_golden():
    assert CATALOG_GOLDEN.exists(), f"missing golden: {CATALOG_GOLDEN}"
    doc = _load_json(CATALOG_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION
    assert doc["base_catalog_digest"] == bootstrap.PHASE5_CATALOG_DIGEST
    assert doc["result_catalog_digest"] == shadow.PHASE6_CATALOG_DIGEST
    assert doc["result_catalog_digest"] == doc["base_catalog_digest"]
    assert doc["workers_added"] == 0
    assert doc["capabilities_added"] == 0


# =========================================================================== #
# Point 6 — sink authorization bites for real (both directions), zero spec edits #
# =========================================================================== #
UTC = timezone.utc
_D = {c: c * 64 for c in "abcd"}


def _dt() -> datetime:
    return datetime(2026, 7, 15, 1, 30, tzinfo=UTC)


def _text_material(id: str, kind: str):
    raw = f"You are {id}.".encode("utf-8")
    tmp = ResolvedTextMaterial(
        ref=ContentRef(id=id, version="1", content_digest="0" * 64), kind=kind, raw_utf8=raw
    )
    digest = catalog_material_digest(tmp)
    ref = ContentRef(id=id, version="1", content_digest=digest)
    return ref, ResolvedTextMaterial(ref=ref, kind=kind, raw_utf8=raw)


def _decision_catalog(*, can_emit_decision: bool):
    pref, pmat = _text_material("dec.worker.prompt", "prompt")
    pentry = ContentManifestEntry(
        ref=pref, kind="prompt", name="dec.worker", description="d", source_identity="gl.src"
    )
    worker = WorkerSpec(
        id="dec.worker",
        catalog_role="final",
        selection_scope="dynamic_allowed",
        lane="decision",
        persona="p",
        tier=Tier.WRITER,
        execution=ExecutionSpec(kind=ExecutionKind.LLM, model_tier="reasoner"),
        system_prompt_ref=pref,
        inputs=(),
        outputs=(OutputBinding(
            name="primary",
            schema_ref=SchemaRef(name="PortfolioTargetProposal", version="1"),
        ),),
        evidence_policy=EvidencePolicy(),
        supported_modes=(DataMode.ONLINE,),
        can_emit_decision=can_emit_decision,
        decision_authority="advisory_only" if can_emit_decision else "none",
    )
    return build_catalog_snapshot(
        catalog_version="cat.v1",
        content_manifest=(pentry,),
        skill_manifest=(),
        capability_manifest=(),
        workers=(worker,),
        resolved_material=(pmat,),
    )


def _context() -> ContextSnapshot:
    binding = build_empty_memory_binding()
    clock = ClockSpec(as_of=_dt(), timezone="Asia/Shanghai", calendar_id="cn_a_share")
    dc = DataContext(
        as_of=_dt(), clock=clock, mode=DataMode.ONLINE, backend=DataBackend.LIVE,
        strict_pit=False, calendar_id="cn_a_share",
        resolved_vendor_chains={"prices": ("tushare",)},
        source_config_digest=_D["a"], source_registry_digest=_D["b"],
        routing_snapshot_digest=_D["c"], data_snapshot_id="snap-1",
        data_snapshot_content_digest=_D["d"], built_at=_dt(),
    )
    return ContextSnapshot.build(
        snapshot_id="ctx-1", data_context=dc, memory_snapshot_id="ms-1",
        memory_snapshot_hash=binding.snapshot_hash,
        past_context_hash=binding.past_context_hash,
        memory_snapshot_ref=binding.memory_snapshot_ref,
        memory_selection_ref=binding.memory_selection_ref,
        runtime_requirements_ref=None, built_at=_dt(),
    )


def _request() -> OrchestrationRequest:
    return OrchestrationRequest(
        request_id="req-1", goal="g", workflow="orchestrate_only",
        approval_policy=ApprovalPolicy.REQUIRED,
    )


def _decision_draft(catalog, registry, context) -> PlanDraft:
    node = PlanNode(id="dec", worker_id="dec.worker", writes_slot="sd")
    ref = PayloadRef(
        namespace="main", object_id="ctx-obj", content_digest=context.content_digest
    )
    return PlanDraft(
        id="plan.x", run_id="run-1", request_id="req-1", phase="main",
        source=PlanSource.DYNAMIC, goal="g", as_of=_dt(), mode=DataMode.ONLINE,
        context_snapshot_ref=ref, nodes=(node,), sink_node_ids=("dec",),
        catalog_version=catalog.catalog_version, catalog_digest=catalog.catalog_digest,
        schema_registry_digest=registry.registry_digest,
        approval_policy=ApprovalPolicy.REQUIRED,
    )


def test_unauthorized_decision_sink_bites_under_the_phase6_registry():
    registry = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    # PortfolioTargetProposal@1 resolves in the Phase-6 registry (the class name was
    # frozen in spec._DECISION_CLASS_SCHEMAS for exactly this — zero spec.py edits).
    registry.resolve(SchemaRef(name="PortfolioTargetProposal", version="1"))
    context = _context()
    catalog = _decision_catalog(can_emit_decision=False)
    draft = _decision_draft(catalog, registry, context)
    report = validate_plan_draft(
        draft, request=_request(), context=context, catalog=catalog,
        schema_registry=registry,
    )
    codes = {i.code for i in report.issues}
    assert not report.valid and "unauthorized_decision_sink" in codes


def test_authorized_decision_sink_accepted_under_the_phase6_registry():
    registry = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    context = _context()
    catalog = _decision_catalog(can_emit_decision=True)
    draft = _decision_draft(catalog, registry, context)
    report = validate_plan_draft(
        draft, request=_request(), context=context, catalog=catalog,
        schema_registry=registry,
    )
    codes = {i.code for i in report.issues}
    assert "unauthorized_decision_sink" not in codes
    assert report.valid, report.issues


# =========================================================================== #
# Point 7 — resolver resolves all seven chain digests without reinterpretation   #
# =========================================================================== #
def test_resolver_resolves_all_chain_digests_without_reinterpretation():
    from guanlan_v2.orchestration.eventstore import SchemaRegistryResolver
    from guanlan_v2.orchestration.schema_registry import default_registry
    from guanlan_v2.orchestration.runtime_contracts import (
        PHASE2_BASE_REGISTRY_DIGEST,
        phase2_runtime_registry,
    )
    from guanlan_v2.orchestration.data.schema_registry import build_phase3_registry
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_FULL_BASE_REGISTRY_DIGEST,
        build_phase3_full_registry,
    )

    p1 = default_registry()
    p2 = phase2_runtime_registry(PHASE2_BASE_REGISTRY_DIGEST)
    p3_data = build_phase3_registry(p2.registry_digest)
    p3_full = build_phase3_full_registry(PHASE3_FULL_BASE_REGISTRY_DIGEST)
    p4 = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)
    p5 = bootstrap.build_phase5_registry(bootstrap.PHASE5_BASE_REGISTRY_DIGEST)
    p6 = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)

    digests = {
        "p1": p1.registry_digest, "p2": p2.registry_digest,
        "p3_data": p3_data.registry_digest, "p3_full": p3_full.registry_digest,
        "p4": p4.registry_digest, "p5": p5.registry_digest, "p6": p6.registry_digest,
    }
    # all seven chain digests are distinct — no "latest" alias collapsed them.
    assert len(set(digests.values())) == 7

    resolver = SchemaRegistryResolver()
    for reg in (p1, p2, p3_data, p3_full, p4, p5, p6):
        resolver.register(reg)
    # a Plan bound to any upstream digest resolves to that exact registry.
    assert resolver.resolve(digests["p1"]) is p1
    assert resolver.resolve(digests["p5"]) is p5
    assert resolver.resolve(digests["p6"]) is p6
    # a Phase-<=5 Plan never reinterprets to the Phase-6 registry.
    assert resolver.resolve(digests["p1"]) is not p6
    assert resolver.resolve(digests["p5"]) is not p6


def test_no_latest_style_alias_in_the_shadow_module_namespace():
    for name in vars(shadow):
        assert "latest" not in name.lower(), (
            f"a 'latest'-style alias leaked into shadow.py: {name}"
        )


# =========================================================================== #
# Point 8 — old Plans binding upstream digests stay resolvable side-by-side       #
# =========================================================================== #
def test_still_deferred_phase8_names_absent_everywhere():
    p6 = {
        e.schema_ref.name
        for e in shadow.build_phase6_registry(
            shadow.PHASE6_BASE_REGISTRY_DIGEST
        ).manifest()
    }
    for name in STILL_DEFERRED_NAMES:
        assert name not in p6, f"{name} is a Phase 8 deferral, absent from Phase 6"


def test_phase6_payloads_register_at_v1_only():
    reg = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    keys = {e.key for e in reg.manifest()}
    for name in EXPECTED_PUBLIC_NAMES:
        assert f"{name}@1" in keys, f"{name} must register at @1"
