# -*- coding: utf-8 -*-
"""Phase 8 · Task 11 — cumulative Phase-8 registry/catalog chain + final-27 seal.

Locks the linear registry/catalog chain the 四车道 lane-worker phase contributes,
built as a pure ADDITION over the sealed Phase-7 chain (never a fork, never a
"latest" alias):

* ``build_phase8_registry(expected_phase7_digest)`` builds a *fresh sealed*
  cumulative registry over the exact Phase-7 cumulative set plus the reviewed 27
  :data:`PHASE8_PUBLIC_MODELS`; a wrong base digest is rejected before any
  registration; inherited entries stay byte-identical to their Phase-<=7 goldens; the
  digest is registration-order independent and matches the hand-reviewed golden; the
  ``DebateMessage`` payload flips from a pure Phase-1-absence deferral to
  present-in-Phase-8 while staying absent from every upstream registry.
* ``build_phase8_catalog_snapshot(...)`` seals the FULL 27-worker catalog: the D5
  final-27 = 3 Lane-0 + #25 + 3 pilots-updated + 20 authored; ``dec.pm`` is the sole
  ``reasoner_deep`` seat; no ``compat.*`` id counts; every SKILL-bearing final worker's
  skill digest equals its tree digest (the lint re-point proves it system-wide); the 3
  superseded pilot skill materials are retired; the shared guardrails / pattern
  dictionary are each registered ONCE.
* the Phase-8 public/internal partition over the nine Phase-8 contract modules is
  exhaustive and disjoint (27 public + 18 internal == 45 discovered).

Goldens are NEVER auto-regenerated by tests: a changed manifest is a reviewed contract
change regenerated by hand and re-reviewed.

Run: ``pytest tests/orchestration/test_phase8_registry_catalog.py -v``
"""
from __future__ import annotations

import hashlib
import importlib
import inspect
import json
from datetime import datetime, timezone
from pathlib import Path

import pytest
from pydantic import ValidationError

from guanlan_v2.orchestration import bootstrap, phase7_registry as p7, shadow, trial
from guanlan_v2.orchestration import lane_catalog as lc
from guanlan_v2.orchestration import skilltree
from guanlan_v2.orchestration.catalog import CatalogError, count_final_workers
from guanlan_v2.orchestration.digest import (
    CJSON_VERSION,
    ContractModel,
    DigestModel,
    content_digest,
)

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
SCHEMA_GOLDEN = GOLDEN_DIR / "phase8_schema_manifest_v1.json"
CATALOG_GOLDEN = GOLDEN_DIR / "phase8_catalog_manifest_v1.json"

#: sha256 pins of the immediate upstream goldens — Phase 8 never regenerates them.
UPSTREAM_GOLDEN_SHA256 = {
    "phase7_schema_manifest_v1.json":
        "dd2dce36b05cb5a02673bf87347bbd4c98e741d6e8655054131c0b55f4fe935d",
    "phase7_catalog_manifest_v1.json":
        "d37f16e3d2f0525565869c1cf9a34ab0665e5d48ab3f46b41b44ddbb1e1b3f83",
}

#: the nine Phase-8 contract modules the completeness firewall governs (mirrors
#: ``test_contract_completeness.PHASE8_MODULES``).
PHASE8_CONTRACT_MODULES = (
    "guanlan_v2.orchestration.capability_manifest",
    "guanlan_v2.orchestration.skilltree",
    "guanlan_v2.orchestration.pattern_registry",
    "guanlan_v2.orchestration.decision_inputs",
    "guanlan_v2.orchestration.honesty",
    "guanlan_v2.orchestration.model_tiers",
    "guanlan_v2.orchestration.lane_payloads",
    "guanlan_v2.orchestration.lane_catalog",
    "guanlan_v2.orchestration.debate",
)

#: the 27 reviewed names the registered Phase-8 surface must equal.
EXPECTED_PUBLIC_NAMES = frozenset({
    "HonestyReport", "ModelTierMap", "DebateMessage", "DebateTranscript",
    "PatternDictionary", "UpstreamRatingsExtract", "AllowedActions",
    "AnnouncementRiskFlags", "NewsDigestReport", "ResearchReportExtract", "PolicyReport",
    "MacroPulseReport", "PriceActionFeatureReport", "TechnicalReport",
    "MicrostructureReport", "PatternLifecycleProposal", "FactorICReport",
    "ModelPredictionReport", "BacktestEvidenceReport", "FundamentalsReport",
    "MinedFactorDraft", "FactorLifecycleProposal", "DataQualityGrade", "BullCase",
    "BearCase", "RiskDebateStance", "RiskDebateParams",
})

#: the 18 reviewed INTERNAL Phase-8 contract names the partition must equal.
EXPECTED_INTERNAL_NAMES = frozenset({
    "NewsDigestItem", "ExtractedClaim", "PolicyEntry", "PredictionMarketRead",
    "IndicatorReading", "FactorICRow", "ModelScoreRow", "QualityComponent",
    "HonestyIssue", "ModelTierBinding", "PatternDefinition", "PatternReplayStats",
    "GapFillStats", "UpstreamRatingRow", "SymbolAllowance", "AnnouncementFlag",
    "CapabilityInterfaceRow", "CapabilityManifest",
})

#: the D5 final-27 roster + its lane partition.
FINAL_27 = frozenset({
    "market.factor", "market.regime", "market.rotation", "market.factor_miner",
    "quant.factor", "quant.model", "quant.backtest", "quant.fundamentals",
    "quant.factor_miner", "quant.curator",
    "pv.price_action", "pv.technical", "pv.microstructure", "pv.curator",
    "text.news", "text.sentiment", "text.research_report", "text.policy", "text.macro",
    "dec.bull", "dec.bear", "dec.research_mgr", "dec.risk_debate", "dec.pm", "dec.trader",
    "x.quality_gate", "x.number_critic",
})
LANE_COUNTS = {"market": 4, "quant": 6, "pv": 4, "text": 5, "decision": 6, "xcut": 2}
PILOTS_UPDATED = frozenset({"text.sentiment", "dec.research_mgr", "dec.pm"})
LANE0_PLUS_MINER = frozenset(
    {"market.factor", "market.regime", "market.rotation", "market.factor_miner"})
RETIRED_PILOT_SKILLS = frozenset({"skill.sentiment@1", "skill.research_mgr@1", "skill.pm@1"})


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _discover_phase8_contract_models() -> set[type]:
    found: set[type] = set()
    for module_name in PHASE8_CONTRACT_MODULES:
        module = importlib.import_module(module_name)
        for obj in vars(module).values():
            if (
                inspect.isclass(obj)
                and issubclass(obj, ContractModel)
                and obj not in (ContractModel, DigestModel)
                and obj.__module__ == module_name
                and not obj.__name__.startswith("_")
            ):
                found.add(obj)
    return found


# =========================================================================== #
# Point 1 — build rejects a wrong base; the correct base seals the right digest #
# =========================================================================== #
def test_build_phase8_registry_rejects_a_wrong_expected_digest():
    with pytest.raises(lc.Phase8RegistryError):
        lc.build_phase8_registry("0" * 64)
    # the Phase-6 digest is NOT the Phase-7 base either (no "latest" collapse).
    with pytest.raises(lc.Phase8RegistryError):
        lc.build_phase8_registry(shadow.PHASE6_REGISTRY_DIGEST)
    # Phase 8's own digest is not its own base (wrong-base rejection, other direction).
    with pytest.raises(lc.Phase8RegistryError):
        lc.build_phase8_registry(lc.PHASE8_REGISTRY_DIGEST)


def test_build_phase8_registry_seals_and_matches_the_frozen_digest():
    reg = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)
    assert reg.sealed is True
    assert reg.registry_digest == lc.PHASE8_REGISTRY_DIGEST
    # a fresh sealed instance per call (never a shared mutable singleton).
    other = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)
    assert other is not reg
    assert other.registry_digest == reg.registry_digest


def test_phase8_base_registry_digest_is_the_phase7_digest():
    assert lc.PHASE8_BASE_REGISTRY_DIGEST == p7.PHASE7_REGISTRY_DIGEST
    assert lc.PHASE8_REGISTRY_DIGEST != lc.PHASE8_BASE_REGISTRY_DIGEST


# =========================================================================== #
# Point 2 — golden equality; inherited byte-identical; upstream goldens frozen   #
# =========================================================================== #
def test_registry_matches_the_frozen_golden_entry_for_entry():
    assert SCHEMA_GOLDEN.exists(), f"missing golden: {SCHEMA_GOLDEN}"
    doc = _load_json(SCHEMA_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION == "sha256+cjson-v1"
    assert doc["base_registry_digest"] == p7.PHASE7_REGISTRY_DIGEST
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    reg = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    assert set(manifest) == set(golden), (
        "phase8 registry key set drifted from phase8_schema_manifest_v1.json; "
        "regenerate + re-review by hand if intended"
    )
    for key in sorted(golden):
        assert manifest[key] == golden[key], f"JSON-schema digest drift for {key}"
    assert reg.registry_digest == doc["registry_digest"]


def test_inherited_entries_are_byte_identical_to_the_phase7_golden():
    phase7_doc = _load_json(GOLDEN_DIR / "phase7_schema_manifest_v1.json")
    phase7 = {e["key"]: e["json_schema_digest"] for e in phase7_doc["entries"]}
    reg = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    # every Phase-7 (cumulative) key is inherited byte-identical …
    for key, digest in phase7.items():
        assert manifest[key] == digest, f"inherited schema {key} drifted in phase8"
    # … and the only new keys are exactly the 27 Phase-8 public contracts.
    new_keys = set(manifest) - set(phase7)
    assert {k.split("@")[0] for k in new_keys} == EXPECTED_PUBLIC_NAMES
    assert len(new_keys) == 27


def test_inherited_entries_are_byte_identical_across_every_upstream_manifest():
    """Walk ALL phase schema goldens — every inherited key stays byte-identical."""
    reg = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    upstream_goldens = (
        "schema_manifest_v1.json",
        "runtime_schema_manifest_v1.json",
        "data_schema_manifest_v1.json",
        "phase3_full_schema_manifest_v1.json",
        "phase4_schema_manifest_v1.json",
        "phase5_schema_manifest_v1.json",
        "phase6_schema_manifest_v1.json",
        "phase7_schema_manifest_v1.json",
    )
    for fname in upstream_goldens:
        path = GOLDEN_DIR / fname
        if not path.exists():
            continue
        doc = _load_json(path)
        for e in doc.get("entries", []):
            key = e["key"]
            if key in manifest:
                assert manifest[key] == e["json_schema_digest"], (
                    f"inherited schema {key} drifted from {fname} in phase8"
                )


def test_new_public_contract_digests_are_recomputable_from_the_models():
    doc = _load_json(SCHEMA_GOLDEN)
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    for model in lc.PHASE8_PUBLIC_MODELS:
        key = f"{model.__name__}@{model.model_fields['schema_version'].default}"
        assert golden[key] == content_digest(model.model_json_schema())


def test_upstream_goldens_are_byte_unchanged():
    for fname, sha in UPSTREAM_GOLDEN_SHA256.items():
        raw = (GOLDEN_DIR / fname).read_bytes()
        assert hashlib.sha256(raw).hexdigest() == sha, (
            f"upstream golden {fname} changed — Phase 8 must never regenerate it"
        )


def test_registry_entry_count_is_the_cumulative_191():
    reg = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)
    # Phase-7 = 164 inherited entries + 27 new Phase-8 publics = 191.
    assert len(reg.manifest()) == 164 + 27 == 191


# =========================================================================== #
# Point 3 — registration-order independence                                     #
# =========================================================================== #
def test_registration_order_independence():
    from guanlan_v2.orchestration.data.schema_registry import (
        PHASE3_PUBLIC_MODELS as DATA_PUBLIC,
    )
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_MEMORY_PUBLIC_MODELS as MEM_PUBLIC,
    )
    from guanlan_v2.orchestration.runtime_contracts import (
        Phase2RuntimeRegistry,
        phase2_public_models,
    )

    canonical = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)
    reversed_reg = Phase2RuntimeRegistry()
    for model in reversed(
        tuple(phase2_public_models())
        + tuple(DATA_PUBLIC)
        + tuple(MEM_PUBLIC)
        + tuple(trial.PHASE4_PUBLIC_MODELS)
        + tuple(bootstrap.PHASE5_PUBLIC_MODELS)
        + tuple(shadow.PHASE6_PUBLIC_MODELS)
        + tuple(p7.PHASE7_PUBLIC_MODELS)
        + tuple(lc.PHASE8_PUBLIC_MODELS)
    ):
        reversed_reg.register(model)
    reversed_reg.seal()
    assert reversed_reg.manifest() == canonical.manifest()
    assert reversed_reg.registry_digest == canonical.registry_digest


# =========================================================================== #
# Point 4 — Phase-8 completeness firewall (exhaustive + disjoint)               #
# =========================================================================== #
def test_public_tuple_shape_and_names():
    assert isinstance(lc.PHASE8_PUBLIC_MODELS, tuple)
    assert len(lc.PHASE8_PUBLIC_MODELS) == 27
    assert len(set(lc.PHASE8_PUBLIC_MODELS)) == 27
    names = {m.__name__ for m in lc.PHASE8_PUBLIC_MODELS}
    assert names == EXPECTED_PUBLIC_NAMES
    for model in lc.PHASE8_PUBLIC_MODELS:
        assert issubclass(model, ContractModel)


def test_internal_map_is_a_contract_model_reason_map():
    assert isinstance(lc.PHASE8_INTERNAL_MODELS, dict)
    names = {m.__name__ for m in lc.PHASE8_INTERNAL_MODELS}
    assert names == EXPECTED_INTERNAL_NAMES
    for model, reason in lc.PHASE8_INTERNAL_MODELS.items():
        assert isinstance(model, type) and issubclass(model, ContractModel)
        assert isinstance(reason, str) and reason.strip()


def test_public_and_internal_partition_the_module_surface_exactly():
    discovered = _discover_phase8_contract_models()
    public = set(lc.PHASE8_PUBLIC_MODELS)
    internal = set(lc.PHASE8_INTERNAL_MODELS)
    classified = public | internal
    assert not (public & internal), "a Phase-8 contract cannot be both registered and internal"
    unclassified = discovered - classified
    assert not unclassified, (
        "unreviewed Phase-8 public contracts: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in unclassified))
    )
    phantom = classified - discovered
    assert not phantom, (
        "classified models not discovered in the nine Phase-8 modules: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in phantom))
    )
    assert classified == discovered
    assert len(public) + len(internal) == len(discovered) == 45


def test_every_public_member_has_a_closed_schema_version():
    for model in lc.PHASE8_PUBLIC_MODELS:
        field = model.model_fields.get("schema_version")
        assert field is not None
        assert isinstance(field.default, str) and field.default, model.__name__


def test_default_registry_does_not_register_any_phase8_public_model():
    from guanlan_v2.orchestration.schema_registry import default_registry
    registered = {e.schema_ref.name for e in default_registry().manifest()}
    for model in lc.PHASE8_PUBLIC_MODELS:
        assert model.__name__ not in registered, model.__name__


def test_phase8_payloads_register_at_v1_only():
    reg = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)
    keys = {e.key for e in reg.manifest()}
    for name in EXPECTED_PUBLIC_NAMES:
        assert f"{name}@1" in keys, f"{name} must register at @1"


# =========================================================================== #
# Point 5 — DebateMessage flip + params schema resolvable                       #
# =========================================================================== #
def test_debate_message_flips_present_in_phase8_absent_upstream():
    p8keys = {
        e.schema_ref.name
        for e in lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST).manifest()
    }
    # presence half: DebateMessage + DebateTranscript now register in Phase 8.
    assert "DebateMessage" in p8keys
    assert "DebateTranscript" in p8keys
    # absence-from-upstream half: never in the Phase-7 / Phase-6 / Phase-1 registries.
    p7keys = {e.schema_ref.name for e in p7.build_phase7_registry(
        p7.PHASE7_BASE_REGISTRY_DIGEST).manifest()}
    assert "DebateMessage" not in p7keys
    p6keys = {e.schema_ref.name for e in shadow.build_phase6_registry(
        shadow.PHASE6_BASE_REGISTRY_DIGEST).manifest()}
    assert "DebateMessage" not in p6keys
    from guanlan_v2.orchestration.schema_registry import default_registry
    assert "DebateMessage" not in {e.schema_ref.name for e in default_registry().manifest()}


def test_risk_debate_params_schema_resolves_for_params_validation():
    from guanlan_v2.orchestration.refs import SchemaRef
    reg = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)
    resolved = reg.resolve(SchemaRef(name="RiskDebateParams", version="1"))
    assert resolved is not None


def test_still_deferred_debate_message_stays_in_test_contract_completeness_absence_guard():
    tcc = importlib.import_module("tests.orchestration.test_contract_completeness")
    # the Phase-1 absence guard is untouched: DebateMessage stays listed as a deferral
    # (absent from Phase 1) even though Phase 8 now registers it (the flip is additive).
    assert "DebateMessage" in tcc.DEFERRED_PHASE_PAYLOADS


# =========================================================================== #
# Point 6 — resolver resolves all chain digests without reinterpretation         #
# =========================================================================== #
def test_resolver_resolves_all_chain_digests_without_reinterpretation():
    from guanlan_v2.orchestration.eventstore import SchemaRegistryResolver
    from guanlan_v2.orchestration.schema_registry import default_registry
    from guanlan_v2.orchestration.runtime_contracts import (
        PHASE2_BASE_REGISTRY_DIGEST,
        phase2_runtime_registry,
    )
    from guanlan_v2.orchestration.data.schema_registry import build_phase3_registry
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_FULL_BASE_REGISTRY_DIGEST,
        build_phase3_full_registry,
    )

    p1 = default_registry()
    p2 = phase2_runtime_registry(PHASE2_BASE_REGISTRY_DIGEST)
    p3_data = build_phase3_registry(p2.registry_digest)
    p3_full = build_phase3_full_registry(PHASE3_FULL_BASE_REGISTRY_DIGEST)
    p4 = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)
    p5 = bootstrap.build_phase5_registry(bootstrap.PHASE5_BASE_REGISTRY_DIGEST)
    p6 = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    p7reg = p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST)
    p8 = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)

    regs = (p1, p2, p3_data, p3_full, p4, p5, p6, p7reg, p8)
    digests = [r.registry_digest for r in regs]
    # all nine chain digests are distinct — no "latest" alias collapsed them.
    assert len(set(digests)) == 9

    resolver = SchemaRegistryResolver()
    for reg in regs:
        resolver.register(reg)
    # a Plan bound to any upstream digest resolves to that exact registry.
    assert resolver.resolve(p7reg.registry_digest) is p7reg
    assert resolver.resolve(p8.registry_digest) is p8
    # a Phase-<=7 Plan never reinterprets to the Phase-8 registry.
    assert resolver.resolve(p1.registry_digest) is not p8
    assert resolver.resolve(p7reg.registry_digest) is not p8


def test_no_latest_style_alias_in_the_phase8_chain_namespace():
    for name in vars(lc):
        if name.startswith("PHASE8") or "phase8" in name.lower():
            assert "latest" not in name.lower(), (
                f"a 'latest'-style alias leaked into the phase8 chain: {name}"
            )


# =========================================================================== #
# Point 7 — the FULL 27-worker catalog seal + final-27 reconciliation (D5)        #
# =========================================================================== #
def test_phase8_catalog_base_digest_is_the_phase7_digest():
    assert lc.PHASE8_BASE_CATALOG_DIGEST == p7.PHASE7_CATALOG_DIGEST
    assert lc.PHASE8_CATALOG_DIGEST != lc.PHASE8_BASE_CATALOG_DIGEST


def test_build_phase8_catalog_rejects_a_non_canonical_base():
    # a Phase-6 catalog (a genuinely different digest) is not the legal Phase-7 base.
    lane_specs, updates = lc.phase8_final_worker_specs()
    with pytest.raises(CatalogError):
        lc.build_phase8_catalog_snapshot(
            shadow.phase6_catalog_snapshot(),
            lane_worker_specs=lane_specs,
            reviewed_worker_updates=updates,
            resolved_materials=lc.load_phase8_lane_materials(),
        )


def test_final_27_reconciliation_matrix():
    snap = lc.phase8_catalog_snapshot()
    assert snap.catalog_digest == lc.PHASE8_CATALOG_DIGEST
    # count_final_workers == 27 (D5); no compat.* counted.
    assert count_final_workers(snap) == lc.FINAL_WORKER_COUNT == 27
    finals = {w.id for w in snap.workers if w.catalog_role == "final"}
    assert finals == FINAL_27
    assert not any(w.id.startswith("compat.") for w in snap.workers if w.catalog_role == "final")
    # D5 accounting: 3 Lane-0 + #25 + 3 pilots-updated + 20 authored == 27.
    lane_specs, updates = lc.phase8_final_worker_specs()
    assert {w.id for w in updates} == PILOTS_UPDATED
    assert len(lane_specs) == 20
    assert LANE0_PLUS_MINER <= finals
    assert (FINAL_27 - PILOTS_UPDATED - LANE0_PLUS_MINER) == {w.id for w in lane_specs}
    # every lane count matches the reviewed roster.
    from collections import Counter
    lane_counts = Counter(w.lane for w in snap.workers if w.catalog_role == "final")
    assert dict(lane_counts) == LANE_COUNTS
    assert sum(LANE_COUNTS.values()) == 27


def test_dec_pm_is_the_sole_reasoner_deep_across_the_full_27():
    snap = lc.phase8_catalog_snapshot()
    deep = {
        w.id for w in snap.workers
        if w.catalog_role == "final" and w.execution.model_tier == "reasoner_deep"
    }
    assert deep == {"dec.pm"}


def test_phase8_catalog_matches_the_frozen_golden():
    assert CATALOG_GOLDEN.exists(), f"missing golden: {CATALOG_GOLDEN}"
    doc = _load_json(CATALOG_GOLDEN)
    snap = lc.phase8_catalog_snapshot()
    assert doc["algorithm"] == CJSON_VERSION
    assert doc["base_catalog_digest"] == p7.PHASE7_CATALOG_DIGEST
    assert doc["result_catalog_digest"] == snap.catalog_digest == lc.PHASE8_CATALOG_DIGEST
    assert doc["result_catalog_digest"] != doc["base_catalog_digest"]
    assert doc["final_worker_count"] == 27
    assert set(doc["final_worker_ids"]) == FINAL_27
    assert doc["lane_counts"] == LANE_COUNTS
    assert doc["sole_reasoner_deep"] == ["dec.pm"]
    assert set(doc["updated_worker_ids"]) == PILOTS_UPDATED
    assert len(doc["new_worker_ids"]) == 20
    assert set(doc["retired_skill_materials"]) == RETIRED_PILOT_SKILLS
    # per-worker semantic digests match the frozen seal.
    got = {
        w.id: w.semantic_digest()
        for w in snap.workers if w.catalog_role == "final"
    }
    assert got == doc["final_worker_semantic_digests"]
    # per-skill manifest digests match the frozen seal.
    got_skills = {
        f"{e.ref.id}@{e.ref.version}": e.ref.content_digest
        for e in snap.skill_manifest
    }
    assert got_skills == doc["skill_manifest_digests"]


# =========================================================================== #
# Point 8 — the supersession seal: pilots retired + lint re-point goes clean      #
# =========================================================================== #
def test_superseded_pilot_skills_are_retired_and_new_skills_bound():
    base = p7.phase7_catalog_snapshot()
    snap = lc.phase8_catalog_snapshot()
    base_skills = {e.ref_key for e in base.skill_manifest}
    snap_skills = {e.ref_key for e in snap.skill_manifest}
    retired = {f"{i}@{v}" for (i, v) in base_skills - snap_skills}
    assert retired == RETIRED_PILOT_SKILLS
    # the updated pilots bind the NEW tree install skills (a superseding digest).
    by_id = {w.id: w for w in snap.workers}
    assert by_id["text.sentiment"].skills[0].skill_ref.id == "skill.text.sentiment"
    assert by_id["dec.research_mgr"].skills[0].skill_ref.id == "skill.dec.research_mgr"
    assert by_id["dec.pm"].skills[0].skill_ref.id == "skill.dec.pm"
    # the Lane-0 + #25 finals pass through byte-identical (digest-preserving relocation).
    for wid in LANE0_PLUS_MINER:
        assert by_id[wid].semantic_digest() == {
            w.id: w.semantic_digest() for w in base.workers}[wid]


def test_skilltree_lint_is_clean_against_the_phase8_catalog():
    """The Task-11 re-point: every SKILL-bearing final worker's skill digest equals its
    tree digest, so the real-tree cross-check against the Phase-8 catalog is CLEAN with
    ZERO sanctioned exceptions (the SUPERSEDED_IN_PHASE8 transitional state is closed)."""
    tree = skilltree.load_skill_tree(skilltree.DEFAULT_TREE_ROOT)
    issues = skilltree.lint_drift(
        tree, materials_root=skilltree.DEFAULT_MATERIALS_ROOT,
        catalog=lc.phase8_catalog_snapshot())
    assert issues == (), f"phase8 catalog cross-check drifted: {issues}"


def test_every_skill_bearing_final_worker_digest_equals_its_tree_digest():
    snap = lc.phase8_catalog_snapshot()
    tree = {s.skill_id: s for s in skilltree.load_skill_tree(skilltree.DEFAULT_TREE_ROOT)}
    for w in snap.workers:
        if w.catalog_role != "final" or not w.skills:
            continue
        if w.id not in tree:
            continue
        assert w.skills[0].skill_ref.content_digest == skilltree._skill_digest(tree[w.id]), (
            f"{w.id}: catalog skill digest != tree digest"
        )


# =========================================================================== #
# Point 9 — capability 承诺-供给 catalog-wide sweep (Task 0b lint)                 #
# =========================================================================== #
def test_capability_promise_supply_lint_clean_across_every_seat():
    from guanlan_v2.orchestration.capability_manifest import (
        generate_capability_manifest,
        lint_skill_supply,
    )
    import guanlan_v2.console.tools as ct

    manifest = generate_capability_manifest(ct.WW_TOOL_TABLE)
    snap = lc.phase8_catalog_snapshot()
    tree_root = skilltree.DEFAULT_TREE_ROOT
    swept = 0
    for w in snap.workers:
        if w.catalog_role != "final" or not w.skills:
            continue
        skill_path = tree_root / w.id / "SKILL.md"
        if not skill_path.exists():
            continue
        swept += 1
        issues = lint_skill_supply(
            manifest=manifest, skill_text=skill_path.read_text(encoding="utf-8"),
            capability_allowlist=w.capability_allowlist)
        assert issues == (), f"{w.id} promise/supply lint: {issues}"
    assert swept >= 20, "the sweep must cover the SKILL-bearing final workers"


# =========================================================================== #
# Point 10 — material dedup: shared guardrails / pattern dict registered once     #
# =========================================================================== #
def test_shared_materials_are_registered_exactly_once():
    snap = lc.phase8_catalog_snapshot()
    # the whole catalog is set-like: no ref_key appears twice in any manifest.
    for mani, label in (
        (snap.content_manifest, "content"),
        (snap.skill_manifest, "skill"),
        (snap.capability_manifest, "capability"),
    ):
        keys = [e.ref_key for e in mani]
        assert len(keys) == len(set(keys)), f"{label} manifest has a duplicate ref_key"
    # the shared guardrails + the pattern dictionary each resolve to exactly one entry.
    content_ids = [e.ref.id for e in snap.content_manifest]
    for shared in (
        "guardrail.number_provenance", "guardrail.untrusted_input_isolation",
        "guardrail.draft_only_advisory", "guardrail.revision_throttle",
        "guardrail.pattern_dictionary", "debate.transcript_reducer",
        "guardrail.model_tier_map",
    ):
        assert content_ids.count(shared) == 1, f"{shared} must be registered exactly once"


def test_load_phase8_materials_dedups_and_a_digest_conflict_raises():
    mats = lc.load_phase8_lane_materials()
    keys = [m.ref_key for m in mats]
    assert len(keys) == len(set(keys)), "load_phase8_lane_materials must dedup by ref_key"
    # a divergent digest under a shared ref_key is a real conflict (not a shared reuse).
    from guanlan_v2.orchestration.catalog_runtime import build_text_material
    good = {m.ref_key: m for m in mats}["guardrail.number_provenance", "1"]
    _ref, clash = build_text_material(
        id="guardrail.number_provenance", version="1", kind="guardrail",
        raw=good.raw_utf8 + b"\ntampered\n")
    with pytest.raises(CatalogError):
        lc._dedup_materials(mats + (clash,))


# =========================================================================== #
# Point 11 — market.rotation single-writer resolution (grounding-map gotcha 2)    #
# =========================================================================== #
def _rotation_draft(nodes, sinks):
    from guanlan_v2.orchestration.spec import PlanDraft
    from guanlan_v2.orchestration.enums import DataMode
    from guanlan_v2.orchestration.presets import PlanSource
    from guanlan_v2.orchestration.refs import PayloadRef

    snap = lc.phase8_catalog_snapshot()
    reg = lc.build_phase8_registry(lc.PHASE8_BASE_REGISTRY_DIGEST)
    ref = PayloadRef(namespace="main", object_id="ctx", content_digest="0" * 64)
    return PlanDraft(
        id="plan.rotation", run_id="run-rot", request_id="req-rot", phase="main",
        source=PlanSource.DYNAMIC, goal="rotation dual-slot", as_of=datetime(2026, 7, 1, tzinfo=timezone.utc),
        mode=DataMode.ONLINE, context_snapshot_ref=ref, nodes=tuple(nodes),
        sink_node_ids=tuple(sinks), catalog_version=snap.catalog_version,
        catalog_digest=snap.catalog_digest, schema_registry_digest=reg.registry_digest,
        budget_request_tokens=1000, budget_request_llm_invocations=2, max_concurrency=2)


def test_market_rotation_is_one_multi_instance_spec_not_two():
    snap = lc.phase8_catalog_snapshot()
    rotation = [w for w in snap.workers if w.id == "market.rotation"]
    assert len(rotation) == 1, "market.rotation is ONE multi-instance spec (spec §3), not two"
    assert rotation[0].catalog_role == "final" and rotation[0].lane == "market"


def test_market_rotation_two_distinct_slots_pass_structure_validation():
    from guanlan_v2.orchestration.spec import PlanNode, validate_plan_structure
    # the frozen resolution: two market.rotation instances writing DISTINCT slots — no
    # shared slot, hence no reducer and no single-writer (unreduced_multi_write) violation.
    draft = _rotation_draft(
        [PlanNode(id="rot-mainline", worker_id="market.rotation",
                  writes_slot="slot.mainline_rotation"),
         PlanNode(id="rot-sector", worker_id="market.rotation",
                  writes_slot="slot.sector_rotation")],
        ["rot-mainline", "rot-sector"])
    validate_plan_structure(draft)  # passes — the single-writer rule owns writes_slot


def test_market_rotation_shared_slot_without_reducer_is_rejected():
    from guanlan_v2.orchestration.spec import PlanNode
    # the explicitly-rejected alternative (one slot + a reducer that would FUSE two
    # distinct evidence streams): a shared slot with two writers and no reducer is an
    # unreduced_multi_write — the strict PlanDraft model rejects it at construction.
    with pytest.raises(ValidationError):
        _rotation_draft(
            [PlanNode(id="rot-a", worker_id="market.rotation", writes_slot="slot.rotation"),
             PlanNode(id="rot-b", worker_id="market.rotation", writes_slot="slot.rotation")],
            ["rot-a", "rot-b"])
