# -*- coding: utf-8 -*-
"""Phase 5 · Task 9 — cumulative Phase-5 registry / catalog chain + goldens.

Locks the linear registry/catalog chain that later phases consume as their base:

* ``build_phase5_registry(expected_phase4_digest)`` builds a *fresh sealed*
  cumulative registry over the exact Phase-4 cumulative set (Phase-1 public +
  Phase-2 runtime facts + Phase-3 data + Phase-3 memory + the 16
  Evaluator-Optimizer contracts) plus the reviewed :data:`PHASE5_PUBLIC_MODELS`
  (17 registered Bootstrap Lane 0 contracts); a wrong base digest is rejected
  before any registration; inherited entries stay byte-identical to their
  Phase-≤4 goldens; the digest is registration-order independent and matches the
  hand-reviewed golden;
* ``phase5_catalog_snapshot()`` extends *only* the canonical Phase-4 catalog with
  the three Lane 0 finals plus the #25 ``market.factor_miner`` placeholder
  (``count_final_workers`` +4) and the Lane 0 experience capability/bridge + #25
  prompt/skill materials; ``compat.*`` and every inherited entry pass through
  byte-identical; a wrong base is rejected;
* the Phase-5 public/internal partition over the three Phase-5 contract modules
  is exhaustive and disjoint (the completeness-firewall pattern, scoped to
  Phase 5);
* old Plans binding the Phase 1 / Phase 2 / Phase 3 data / Phase 3 full / Phase 4
  digests stay resolvable side-by-side with the Phase 5 digest through the
  ``SchemaRegistryResolver`` — no "latest" alias, no reinterpretation;
* the two bootstrap payload models (``BootstrapPlan`` /
  ``BootstrapContextManifest``) are schema-frozen here so the registry freeze
  covers them (Task 10 builds only the runtime glue on top).

Goldens are NEVER auto-regenerated by tests: a changed manifest is a reviewed
contract change regenerated by hand and re-reviewed.

Run: ``pytest tests/orchestration/test_phase5_registry.py -v``
"""
from __future__ import annotations

import hashlib
import importlib
import inspect
import json
from pathlib import Path

import pytest

from guanlan_v2.orchestration import bootstrap, trial
from guanlan_v2.orchestration.catalog import count_final_workers
from guanlan_v2.orchestration.digest import (
    CJSON_VERSION,
    ContractModel,
    DigestModel,
    content_digest,
)
from guanlan_v2.orchestration.refs import PayloadRef, SchemaRef, TypedPayloadRef

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
SCHEMA_GOLDEN = GOLDEN_DIR / "phase5_schema_manifest_v1.json"
CATALOG_GOLDEN = GOLDEN_DIR / "phase5_catalog_manifest_v1.json"

#: sha256 pins of the upstream goldens — Phase 5 never regenerates any of them.
UPSTREAM_GOLDEN_SHA256 = {
    "schema_manifest_v1.json":
        "5de22e4727f874c4b1c53d1da6a82bb8666a2a85ae97a5b551280c687cae92d8",
    "phase4_schema_manifest_v1.json":
        None,  # filled at load time from disk (only its inherited entries matter)
}

#: the three Phase-5 contract modules the completeness firewall governs.
PHASE5_CONTRACT_MODULES = (
    "guanlan_v2.orchestration.market.factors",
    "guanlan_v2.orchestration.memory.experience",
    "guanlan_v2.orchestration.bootstrap",
)

#: the 17 reviewed names the registered Phase-5 surface must equal.
EXPECTED_PUBLIC_NAMES = frozenset({
    "MarketFactorValue", "MarketFactorSetSpec", "MarketFactorReport",
    "RegimeReport", "RotationReport",
    "RegimeCase", "RealizedRegime", "CaseMatured", "CaseReviewed",
    "RegimeGraderSpec", "ExperienceScalerSnapshot", "ExperienceQuery",
    "ExperienceSelection",
    "ExperiencePrefetchBinding", "BootstrapRuntimeProfile", "BootstrapPlan",
    "BootstrapContextManifest",
})

#: the five Phase-5 payload names whose deferred-absence guards Task 9 flips.
FLIPPED_DEFERRED_NAMES = (
    "MarketFactorValue", "MarketFactorReport", "RegimeReport",
    "RealizedRegime", "RotationReport",
)

#: still-deferred Phase 6/8 payloads — absent from every registry in the chain.
STILL_DEFERRED_NAMES = (
    "TargetPosition", "PortfolioTargetProposal", "TargetPortfolioIntent",
    "DecisionSchedule", "DebateMessage",
)


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _discover_phase5_contract_models() -> set[type]:
    found: set[type] = set()
    for module_name in PHASE5_CONTRACT_MODULES:
        module = importlib.import_module(module_name)
        for obj in vars(module).values():
            if (
                inspect.isclass(obj)
                and issubclass(obj, ContractModel)
                and obj not in (ContractModel, DigestModel)
                and obj.__module__ == module_name
                and not obj.__name__.startswith("_")
            ):
                found.add(obj)
    return found


# =========================================================================== #
# Point 1 — build rejects a wrong base; the correct base seals the right digest #
# =========================================================================== #
def test_build_phase5_registry_rejects_a_wrong_expected_digest():
    with pytest.raises(bootstrap.Phase5RegistryError):
        bootstrap.build_phase5_registry("0" * 64)


def test_build_phase5_registry_seals_and_matches_the_frozen_digest():
    reg = bootstrap.build_phase5_registry(bootstrap.PHASE5_BASE_REGISTRY_DIGEST)
    assert reg.sealed is True
    assert reg.registry_digest == bootstrap.PHASE5_REGISTRY_DIGEST
    # a fresh sealed instance per call (never a shared mutable singleton).
    other = bootstrap.build_phase5_registry(bootstrap.PHASE5_BASE_REGISTRY_DIGEST)
    assert other is not reg
    assert other.registry_digest == reg.registry_digest


def test_phase5_base_registry_digest_is_the_phase4_digest():
    assert bootstrap.PHASE5_BASE_REGISTRY_DIGEST == trial.PHASE4_REGISTRY_DIGEST
    assert bootstrap.PHASE5_REGISTRY_DIGEST != bootstrap.PHASE5_BASE_REGISTRY_DIGEST


# =========================================================================== #
# Point 2 — golden equality; inherited byte-identical; upstream goldens frozen   #
# =========================================================================== #
def test_registry_matches_the_frozen_golden_entry_for_entry():
    assert SCHEMA_GOLDEN.exists(), f"missing golden: {SCHEMA_GOLDEN}"
    doc = _load_json(SCHEMA_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION == "sha256+cjson-v1"
    assert doc["base_registry_digest"] == trial.PHASE4_REGISTRY_DIGEST
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    reg = bootstrap.build_phase5_registry(bootstrap.PHASE5_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    assert set(manifest) == set(golden), (
        "phase5 registry key set drifted from phase5_schema_manifest_v1.json; "
        "regenerate + re-review by hand if intended"
    )
    for key in sorted(golden):
        assert manifest[key] == golden[key], f"JSON-schema digest drift for {key}"
    assert reg.registry_digest == doc["registry_digest"]


def test_inherited_entries_are_byte_identical_to_the_phase4_golden():
    phase4_doc = _load_json(GOLDEN_DIR / "phase4_schema_manifest_v1.json")
    phase4 = {e["key"]: e["json_schema_digest"] for e in phase4_doc["entries"]}
    reg = bootstrap.build_phase5_registry(bootstrap.PHASE5_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    # every Phase-4 (cumulative) key is inherited byte-identical …
    for key, digest in phase4.items():
        assert manifest[key] == digest, f"inherited schema {key} drifted in phase5"
    # … and the only new keys are exactly the 17 Phase-5 public contracts.
    new_keys = set(manifest) - set(phase4)
    assert {k.split("@")[0] for k in new_keys} == EXPECTED_PUBLIC_NAMES
    assert len(new_keys) == 17


def test_new_public_contract_digests_are_recomputable_from_the_models():
    doc = _load_json(SCHEMA_GOLDEN)
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    for model in bootstrap.PHASE5_PUBLIC_MODELS:
        key = f"{model.__name__}@{model.model_fields['schema_version'].default}"
        assert golden[key] == content_digest(model.model_json_schema())


def test_upstream_phase1_golden_is_byte_unchanged():
    raw = (GOLDEN_DIR / "schema_manifest_v1.json").read_bytes()
    assert hashlib.sha256(raw).hexdigest() == UPSTREAM_GOLDEN_SHA256[
        "schema_manifest_v1.json"
    ], "Phase 1 golden changed — Phase 5 must never regenerate it"


# =========================================================================== #
# Point 3 — registration-order independence                                     #
# =========================================================================== #
def test_registration_order_independence():
    from guanlan_v2.orchestration.runtime_contracts import (
        Phase2RuntimeRegistry,
        phase2_public_models,
    )
    from guanlan_v2.orchestration.data.schema_registry import (
        PHASE3_PUBLIC_MODELS as DATA_PUBLIC,
    )
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_MEMORY_PUBLIC_MODELS as MEM_PUBLIC,
    )

    canonical = bootstrap.build_phase5_registry(bootstrap.PHASE5_BASE_REGISTRY_DIGEST)
    reversed_reg = Phase2RuntimeRegistry()
    for model in reversed(
        tuple(phase2_public_models())
        + tuple(DATA_PUBLIC)
        + tuple(MEM_PUBLIC)
        + tuple(trial.PHASE4_PUBLIC_MODELS)
        + tuple(bootstrap.PHASE5_PUBLIC_MODELS)
    ):
        reversed_reg.register(model)
    reversed_reg.seal()
    assert reversed_reg.manifest() == canonical.manifest()
    assert reversed_reg.registry_digest == canonical.registry_digest


# =========================================================================== #
# Point 4 — Phase-5 completeness firewall (exhaustive + disjoint)               #
# =========================================================================== #
def test_public_tuple_shape_and_names():
    assert isinstance(bootstrap.PHASE5_PUBLIC_MODELS, tuple)
    assert len(bootstrap.PHASE5_PUBLIC_MODELS) == 17
    assert len(set(bootstrap.PHASE5_PUBLIC_MODELS)) == 17
    names = {m.__name__ for m in bootstrap.PHASE5_PUBLIC_MODELS}
    assert names == EXPECTED_PUBLIC_NAMES
    for model in bootstrap.PHASE5_PUBLIC_MODELS:
        assert issubclass(model, ContractModel)


def test_public_tuple_consumes_task8_bootstrap_models():
    # obligation #1 / #3: BootstrapRuntimeProfile is registered (Option-4) and
    # RegimeGraderSpec is inherited from EXPERIENCE_PUBLIC_MODELS (never double-added).
    from guanlan_v2.orchestration.memory.experience import EXPERIENCE_PUBLIC_MODELS

    for model in bootstrap.BOOTSTRAP_PUBLIC_MODELS:
        assert model in bootstrap.PHASE5_PUBLIC_MODELS
    assert bootstrap.PHASE5_PUBLIC_MODELS.count(
        importlib.import_module("guanlan_v2.orchestration.memory.experience").RegimeGraderSpec
    ) == 1
    for model in EXPERIENCE_PUBLIC_MODELS:
        assert model in bootstrap.PHASE5_PUBLIC_MODELS


def test_internal_map_is_a_contract_model_reason_map():
    assert isinstance(bootstrap.PHASE5_INTERNAL_MODELS, dict)
    for model, reason in bootstrap.PHASE5_INTERNAL_MODELS.items():
        assert isinstance(model, type) and issubclass(model, ContractModel)
        assert isinstance(reason, str) and reason.strip()


def test_public_and_internal_partition_the_three_module_surface_exactly():
    discovered = _discover_phase5_contract_models()
    public = set(bootstrap.PHASE5_PUBLIC_MODELS)
    internal = set(bootstrap.PHASE5_INTERNAL_MODELS)
    classified = public | internal
    assert not (public & internal), "a Phase-5 contract cannot be both registered and internal"
    unclassified = discovered - classified
    assert not unclassified, (
        "unreviewed Phase-5 public contracts: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in unclassified))
    )
    phantom = classified - discovered
    assert not phantom, (
        "classified models not discovered in the three Phase-5 modules: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in phantom))
    )
    assert classified == discovered
    assert len(public) + len(internal) == len(discovered)


def test_every_public_member_has_a_closed_schema_version():
    for model in bootstrap.PHASE5_PUBLIC_MODELS:
        field = model.model_fields.get("schema_version")
        assert field is not None
        assert isinstance(field.default, str) and field.default, model.__name__


def test_internal_surface_documents_the_non_contract_axis_enums_and_ports():
    surface = bootstrap.PHASE5_INTERNAL_SURFACE
    assert isinstance(surface, dict)
    for name in ("TrendState", "RiskState", "HeatState", "ExperienceLog",
                 "ObservedTradeDateCalendar", "CaseMaturityPending"):
        assert name in surface and surface[name].strip()


def test_default_registry_does_not_register_any_phase5_public_model():
    from guanlan_v2.orchestration.schema_registry import default_registry
    registered = {e.schema_ref.name for e in default_registry().manifest()}
    for model in bootstrap.PHASE5_PUBLIC_MODELS:
        assert model.__name__ not in registered, model.__name__


# =========================================================================== #
# Point 5 — catalog: base digest guard, +4 finals, compat untouched, golden      #
# =========================================================================== #
def test_build_phase5_catalog_rejects_a_non_canonical_base():
    from guanlan_v2.orchestration.catalog import CatalogError

    wrong_base = trial.phase4_catalog_snapshot()  # its digest is the Phase-4 base…
    # …perturb by using the Phase-3 data-only catalog as an illegal base.
    from guanlan_v2.orchestration.data.catalog import phase3_data_catalog_snapshot

    lane0 = bootstrap.load_lane0_catalog()
    miner = bootstrap.factor_miner_placeholder()
    with pytest.raises(CatalogError):
        bootstrap.build_phase5_catalog_snapshot(
            phase3_data_catalog_snapshot(), lane0=lane0, factor_miner=miner
        )
    # the canonical base is accepted (sanity).
    ok = bootstrap.build_phase5_catalog_snapshot(wrong_base, lane0=lane0, factor_miner=miner)
    assert ok.catalog_digest == bootstrap.PHASE5_CATALOG_DIGEST


def test_phase5_catalog_matches_the_frozen_golden():
    assert CATALOG_GOLDEN.exists(), f"missing golden: {CATALOG_GOLDEN}"
    doc = _load_json(CATALOG_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION
    assert doc["base_catalog_digest"] == trial.PHASE4_CATALOG_DIGEST
    assert doc["base_catalog_digest"] == bootstrap.PHASE5_BASE_CATALOG_DIGEST
    assert doc["catalog_version"] == "phase5-full-v1"
    snap = bootstrap.phase5_catalog_snapshot()
    assert snap.catalog_digest == bootstrap.PHASE5_CATALOG_DIGEST
    assert snap.catalog_digest == doc["catalog_digest"]
    assert snap.catalog_digest != bootstrap.PHASE5_BASE_CATALOG_DIGEST


def test_catalog_adds_exactly_four_final_workers():
    base = trial.phase4_catalog_snapshot()
    snap = bootstrap.phase5_catalog_snapshot()
    assert count_final_workers(snap) == count_final_workers(base) + 4
    base_ids = {w.id for w in base.workers}
    added = sorted(w.id for w in snap.workers if w.id not in base_ids)
    assert added == [
        "market.factor", "market.factor_miner", "market.regime", "market.rotation"
    ]
    added_final = sorted(
        w.id for w in snap.workers
        if w.catalog_role == "final" and w.id not in base_ids
    )
    assert added_final == added  # all four additions are finals


def test_compat_workers_and_inherited_entries_pass_through_unchanged():
    base = trial.phase4_catalog_snapshot()
    snap = bootstrap.phase5_catalog_snapshot()
    base_workers = {w.id: w for w in base.workers}
    new_workers = {w.id: w for w in snap.workers}
    # every inherited worker (incl. compat.*) is byte-identical.
    for wid, w in base_workers.items():
        assert new_workers[wid] == w, f"inherited worker {wid} changed in phase5"
    compat = [w.id for w in snap.workers if w.id.startswith("compat.")]
    assert compat == ["compat.news_sentiment", "compat.report_writer"]
    # inherited content/skill/capability entries pass through byte-identical.
    base_content = {e.ref_key: e for e in base.content_manifest}
    new_content = {e.ref_key: e for e in snap.content_manifest}
    for key, e in base_content.items():
        assert new_content[key] == e


def test_factor_miner_placeholder_pins_the_r9_boundary():
    snap = bootstrap.phase5_catalog_snapshot()
    miner = next(w for w in snap.workers if w.id == "market.factor_miner")
    assert miner.catalog_role == "final"
    assert miner.can_emit_decision is False
    assert miner.decision_authority == "none"
    # draft-only primary output pinned to MarketFactorSetSpec@1.
    primary = next(o for o in miner.outputs if o.name == "primary")
    assert primary.schema_ref.name == "MarketFactorSetSpec"
    assert primary.schema_ref.version == "1"
    # no capability / tool-call authority (offline, draft-only).
    assert miner.capability_allowlist == ()
    assert miner.evidence_policy.tool_calls.value == "forbidden"
    # the miner carries no handler_ref (LLM execution with a prompt only), and the
    # Lane 0 trusted-factory registration (register_lane0_trusted_factories) never
    # binds a market.factor_miner handler — it can never execute, by construction.
    placeholder = bootstrap.factor_miner_placeholder()
    assert placeholder.worker.execution.handler_ref is None


def test_factor_miner_never_referenced_by_the_bootstrap_preset_grammar():
    # #25 is a catalog occupant only: the Lane 0 assembled workers (the ones a
    # preset graph binds) are exactly the three Lane 0 finals, never the miner.
    lane0 = bootstrap.load_lane0_catalog()
    assert [w.id for w in lane0.workers] == [
        "market.factor", "market.regime", "market.rotation"
    ]
    assert "market.factor_miner" not in {w.id for w in lane0.workers}


# =========================================================================== #
# Point 6 — guard flips: the five names exist + register in Phase 5 only         #
# =========================================================================== #
def test_flipped_deferred_names_exist_and_register_in_phase5_only():
    p5 = {
        e.schema_ref.name
        for e in bootstrap.build_phase5_registry(
            bootstrap.PHASE5_BASE_REGISTRY_DIGEST
        ).manifest()
    }
    # present in the Phase-5 registry …
    for name in FLIPPED_DEFERRED_NAMES:
        assert name in p5, f"{name} must register in the Phase-5 cumulative registry"
    # … and absent from every Phase-≤4 registry in the chain.
    from guanlan_v2.orchestration.schema_registry import default_registry
    from guanlan_v2.orchestration.runtime_contracts import (
        PHASE2_BASE_REGISTRY_DIGEST,
        phase2_runtime_registry,
    )
    from guanlan_v2.orchestration.data.schema_registry import build_phase3_registry
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_FULL_BASE_REGISTRY_DIGEST,
        build_phase3_full_registry,
    )

    p1 = {e.schema_ref.name for e in default_registry().manifest()}
    p2 = {e.schema_ref.name for e in phase2_runtime_registry(PHASE2_BASE_REGISTRY_DIGEST).manifest()}
    p3d = {e.schema_ref.name for e in build_phase3_registry(
        phase2_runtime_registry(PHASE2_BASE_REGISTRY_DIGEST).registry_digest).manifest()}
    p3f = {e.schema_ref.name for e in build_phase3_full_registry(
        PHASE3_FULL_BASE_REGISTRY_DIGEST).manifest()}
    p4 = {e.schema_ref.name for e in trial.build_phase4_registry(
        trial.PHASE4_BASE_REGISTRY_DIGEST).manifest()}
    for name in FLIPPED_DEFERRED_NAMES:
        for reg_names in (p1, p2, p3d, p3f, p4):
            assert name not in reg_names, f"{name} leaked into a Phase-<=4 registry"


def test_still_deferred_phase6_8_names_absent_everywhere():
    p5 = {
        e.schema_ref.name
        for e in bootstrap.build_phase5_registry(
            bootstrap.PHASE5_BASE_REGISTRY_DIGEST
        ).manifest()
    }
    for name in STILL_DEFERRED_NAMES:
        assert name not in p5, f"{name} is a Phase 6/8 deferral, absent from Phase 5"


# =========================================================================== #
# Point 7 — SchemaRegistryResolver resolves all six chain digests simultaneously #
# =========================================================================== #
def test_resolver_resolves_all_chain_digests_without_reinterpretation():
    from guanlan_v2.orchestration.eventstore import SchemaRegistryResolver
    from guanlan_v2.orchestration.schema_registry import default_registry
    from guanlan_v2.orchestration.runtime_contracts import (
        PHASE2_BASE_REGISTRY_DIGEST,
        phase2_runtime_registry,
    )
    from guanlan_v2.orchestration.data.schema_registry import build_phase3_registry
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_FULL_BASE_REGISTRY_DIGEST,
        build_phase3_full_registry,
    )

    p1 = default_registry()
    p2 = phase2_runtime_registry(PHASE2_BASE_REGISTRY_DIGEST)
    p3_data = build_phase3_registry(p2.registry_digest)
    p3_full = build_phase3_full_registry(PHASE3_FULL_BASE_REGISTRY_DIGEST)
    p4 = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)
    p5 = bootstrap.build_phase5_registry(bootstrap.PHASE5_BASE_REGISTRY_DIGEST)

    digests = {
        "p1": p1.registry_digest, "p2": p2.registry_digest,
        "p3_data": p3_data.registry_digest, "p3_full": p3_full.registry_digest,
        "p4": p4.registry_digest, "p5": p5.registry_digest,
    }
    # all six chain digests are distinct — no "latest" alias collapsed them.
    assert len(set(digests.values())) == 6

    resolver = SchemaRegistryResolver()
    for reg in (p1, p2, p3_data, p3_full, p4, p5):
        resolver.register(reg)
    # a Plan bound to any upstream digest resolves to that exact registry.
    assert resolver.resolve(digests["p1"]) is p1
    assert resolver.resolve(digests["p4"]) is p4
    assert resolver.resolve(digests["p5"]) is p5
    # a Phase-<=4 Plan never reinterprets to the Phase-5 registry.
    assert resolver.resolve(digests["p1"]) is not p5
    assert resolver.resolve(digests["p4"]) is not p5


def test_no_latest_style_alias_in_the_bootstrap_module_namespace():
    for name in vars(bootstrap):
        assert "latest" not in name.lower(), (
            f"a 'latest'-style alias leaked into bootstrap.py: {name}"
        )


# =========================================================================== #
# Point 8 — the two bootstrap payload models are schema-frozen (focused build)    #
# =========================================================================== #
def _typed_ref(name: str) -> TypedPayloadRef:
    return TypedPayloadRef(
        schema_ref=SchemaRef(name=name, version="1"),
        payload_ref=PayloadRef(namespace="main", object_id="obj-x", content_digest="a" * 64),
    )


def test_bootstrap_plan_builds_and_reseals():
    plan = bootstrap.BootstrapPlan.build(
        preset_version="1",
        factor_set_version="mfs-v1",
        factor_set_digest="b" * 64,
        grader_digest="c" * 64,
        experience_k=5,
        node_timeout_sec=300,
        budget_request_tokens=0,
        budget_request_llm_invocations=2,
    )
    assert plan.preset_id == "bootstrap.lane0"
    assert plan.content_digest == plan.semantic_digest()
    # experience_k is bounded (le=20).
    with pytest.raises(Exception):
        bootstrap.BootstrapPlan.build(
            preset_version="1", factor_set_version="mfs-v1", factor_set_digest="b" * 64,
            grader_digest="c" * 64, experience_k=21, node_timeout_sec=300,
            budget_request_tokens=0, budget_request_llm_invocations=2,
        )


def test_bootstrap_context_manifest_none_ref_requires_badge():
    mf = _typed_ref("MarketFactorReport")
    regime = _typed_ref("RegimeReport")
    rotation = _typed_ref("RotationReport")

    # all three present, no missing badge — accepted.
    ok = bootstrap.BootstrapContextManifest.build(
        context_snapshot_digest="d" * 64,
        bootstrap_plan_digest="e" * 64,
        bootstrap_run_id="run-1",
        market_factor_report_ref=mf,
        regime_report_ref=regime,
        rotation_report_ref=rotation,
    )
    assert ok.content_digest == ok.semantic_digest()

    # regime None without the badge — rejected.
    with pytest.raises(Exception):
        bootstrap.BootstrapContextManifest.build(
            context_snapshot_digest="d" * 64, bootstrap_plan_digest="e" * 64,
            bootstrap_run_id="run-1", market_factor_report_ref=mf,
            regime_report_ref=None, rotation_report_ref=rotation,
        )

    # regime None WITH the badge — accepted; rotation None WITH its badge too.
    honest = bootstrap.BootstrapContextManifest.build(
        context_snapshot_digest="d" * 64, bootstrap_plan_digest="e" * 64,
        bootstrap_run_id="run-1", market_factor_report_ref=mf,
        regime_report_ref=None, rotation_report_ref=None,
        degradation_badges=("regime_missing", "rotation_missing"),
    )
    assert honest.regime_report_ref is None
    assert honest.rotation_report_ref is None


def test_bootstrap_context_manifest_pins_ref_schemas_and_run_id_is_audit_only():
    mf = _typed_ref("MarketFactorReport")
    # a wrong schema on the market-factor ref is rejected.
    with pytest.raises(Exception):
        bootstrap.BootstrapContextManifest.build(
            context_snapshot_digest="d" * 64, bootstrap_plan_digest="e" * 64,
            bootstrap_run_id="run-1", market_factor_report_ref=_typed_ref("RegimeReport"),
            regime_report_ref=None, rotation_report_ref=None,
            degradation_badges=("regime_missing", "rotation_missing"),
        )
    # bootstrap_run_id is SEMANTIC_EXCLUDE: a different run id leaves the semantic
    # digest stable (audit-only identity).
    base = bootstrap.BootstrapContextManifest.build(
        context_snapshot_digest="d" * 64, bootstrap_plan_digest="e" * 64,
        bootstrap_run_id="run-1", market_factor_report_ref=mf,
        regime_report_ref=None, rotation_report_ref=None,
        degradation_badges=("regime_missing", "rotation_missing"),
    )
    other = bootstrap.BootstrapContextManifest.build(
        context_snapshot_digest="d" * 64, bootstrap_plan_digest="e" * 64,
        bootstrap_run_id="run-2", market_factor_report_ref=mf,
        regime_report_ref=None, rotation_report_ref=None,
        degradation_badges=("regime_missing", "rotation_missing"),
    )
    assert base.semantic_digest() == other.semantic_digest()
    assert "BootstrapContextManifest" in {m.__name__ for m in bootstrap.PHASE5_PUBLIC_MODELS}
