# -*- coding: utf-8 -*-
"""Phase 4 · Task 9 — cumulative Phase-4 registry / catalog chain + goldens.

Locks the linear registry/catalog chain that Phase 5 consumes as its sole base:

* ``build_phase4_registry(expected_phase3_full_digest)`` builds a *fresh sealed*
  cumulative registry over the exact Phase-3 FULL (data + memory) cumulative set
  plus the reviewed :data:`PHASE4_PUBLIC_MODELS` (16 registered Evaluator-Optimizer
  contracts); a wrong base digest is rejected before any registration; inherited
  entries stay byte-identical to the Phase-3 full golden; the digest is
  registration-order independent and matches the hand-reviewed golden;
* ``build_phase4_catalog_snapshot(...)`` extends *only* the canonical Phase-3 full
  catalog with exactly one ``gate_metric`` content material (``optimize.joint_gate``
  @1) sourced byte-for-byte from
  ``config/orchestration/materials/optimize/joint_gate_v1.md`` (UTF-8, no BOM);
  workers/capabilities are unchanged; a tampered material byte fails the digest;
* the Phase-4 public/internal partition over the six Phase-4 contract modules is
  exhaustive and disjoint (the Phase-1 completeness-firewall pattern, scoped to
  Phase 4);
* old Plans binding the Phase 1 / Phase 2 / Phase 3 data-only / Phase 3 full
  digests stay resolvable side-by-side with the Phase 4 digest through the
  ``SchemaRegistryResolver`` — no "latest" alias, no reinterpretation;
* the sealed startup state-cell union is exactly the reviewed Phase-3 seven plus
  Phase-4 four (lexicographic).

Goldens are NEVER auto-regenerated by tests: a changed manifest is a reviewed
contract change regenerated by hand and re-reviewed.

Run: ``pytest tests/orchestration/test_phase4_registry.py -v``
"""
from __future__ import annotations

import hashlib
import importlib
import inspect
import json
from pathlib import Path

import pytest

from guanlan_v2.orchestration import trial
from guanlan_v2.orchestration.digest import CJSON_VERSION, ContractModel, content_digest

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
SCHEMA_GOLDEN = GOLDEN_DIR / "phase4_schema_manifest_v1.json"
CATALOG_GOLDEN = GOLDEN_DIR / "phase4_catalog_manifest_v1.json"

#: sha256 pins of the upstream goldens — Phase 4 never regenerates any of them.
UPSTREAM_GOLDEN_SHA256 = {
    "schema_manifest_v1.json":
        "5de22e4727f874c4b1c53d1da6a82bb8666a2a85ae97a5b551280c687cae92d8",
    "data_schema_manifest_v1.json":
        "08228c7401ef39ede2ddc61284d51b4d042a943bed6af6895ce99e263f63e3ee",
    "phase3_full_schema_manifest_v1.json":
        "115f9dd2df76324a878211bb0f4609e9721fa062b0a100e4cecad99612837534",
    "phase3_full_catalog_manifest_v1.json":
        "41df6d9033b7951caa83d3ef257080f1d440f7572fc526b54a2e30205bf0d28b",
    "data_catalog_manifest_v1.json":
        "7dd514bff88e2c202a43332fe0a456ad3c284affd6959ec29d0c9a300178d151",
}

#: the six Phase-4 contract modules the completeness firewall governs.
PHASE4_CONTRACT_MODULES = (
    "guanlan_v2.orchestration.trial",
    "guanlan_v2.orchestration.governor",
    "guanlan_v2.orchestration.trial_ledger",
    "guanlan_v2.orchestration.sealed",
    "guanlan_v2.orchestration.evaluator",
    "guanlan_v2.orchestration.optimize",
)

#: the 16 reviewed names the registered Phase-4 surface must equal.
EXPECTED_PUBLIC_NAMES = frozenset({
    "StudySpec", "StudyFamily", "SplitSpec", "OptimizeCandidate", "ValidationMetrics",
    "GovernanceReport", "Feedback", "OptimizeRound", "HoldoutWindow", "TrialRecord",
    "OptimizeRunState", "OptimizeResult", "HoldoutReceipt", "HoldoutLease",
    "SealedEvaluationRecord", "SealedCapability",
})

JOINT_GATE_MATERIAL_PATH = (
    Path(__file__).resolve().parents[2]
    / "config" / "orchestration" / "materials" / "optimize" / "joint_gate_v1.md"
)


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _phase3_full_digest() -> str:
    from guanlan_v2.orchestration.memory import schema_registry as reg
    return reg.PHASE3_FULL_REGISTRY_DIGEST


def _phase3_full_catalog_digest() -> str:
    from guanlan_v2.orchestration.memory import catalog as cat
    return cat.PHASE3_FULL_CATALOG_DIGEST


def _discover_phase4_contract_models() -> set[type]:
    found: set[type] = set()
    for module_name in PHASE4_CONTRACT_MODULES:
        module = importlib.import_module(module_name)
        for obj in vars(module).values():
            if (
                inspect.isclass(obj)
                and issubclass(obj, ContractModel)
                and obj.__module__ == module_name
                and not obj.__name__.startswith("_")
            ):
                found.add(obj)
    return found


# =========================================================================== #
# Point 1 — build rejects a wrong base; the correct base seals the right digest #
# =========================================================================== #
def test_build_phase4_registry_rejects_a_wrong_expected_digest():
    with pytest.raises(trial.Phase4RegistryError):
        trial.build_phase4_registry("0" * 64)


def test_build_phase4_registry_seals_and_matches_the_frozen_digest():
    reg = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)
    assert reg.sealed is True
    assert reg.registry_digest == trial.PHASE4_REGISTRY_DIGEST
    # a fresh sealed instance per call (never a shared mutable singleton).
    other = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)
    assert other is not reg
    assert other.registry_digest == reg.registry_digest


def test_phase4_base_registry_digest_is_the_phase3_full_digest():
    assert trial.PHASE4_BASE_REGISTRY_DIGEST == _phase3_full_digest()
    assert trial.PHASE4_REGISTRY_DIGEST != trial.PHASE4_BASE_REGISTRY_DIGEST


# =========================================================================== #
# Point 2 — golden equality; inherited byte-identical; upstream goldens frozen   #
# =========================================================================== #
def test_registry_matches_the_frozen_golden_entry_for_entry():
    assert SCHEMA_GOLDEN.exists(), f"missing golden: {SCHEMA_GOLDEN}"
    doc = _load_json(SCHEMA_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION == "sha256+cjson-v1"
    assert doc["base_registry_digest"] == _phase3_full_digest()
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    reg = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    assert set(manifest) == set(golden), (
        "phase4 registry key set drifted from phase4_schema_manifest_v1.json; "
        "regenerate + re-review by hand if intended"
    )
    for key in sorted(golden):
        assert manifest[key] == golden[key], f"JSON-schema digest drift for {key}"
    assert reg.registry_digest == doc["registry_digest"]


def test_inherited_entries_are_byte_identical_to_the_phase3_full_golden():
    phase3_doc = _load_json(GOLDEN_DIR / "phase3_full_schema_manifest_v1.json")
    phase3 = {e["key"]: e["json_schema_digest"] for e in phase3_doc["entries"]}
    reg = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    # every Phase-3 full key is inherited byte-identical …
    for key, digest in phase3.items():
        assert manifest[key] == digest, f"inherited schema {key} drifted in phase4"
    # … and the only new keys are exactly the 16 Phase-4 public contracts.
    new_keys = set(manifest) - set(phase3)
    assert {k.split("@")[0] for k in new_keys} == EXPECTED_PUBLIC_NAMES


def test_new_public_contract_digests_are_recomputable_from_the_models():
    doc = _load_json(SCHEMA_GOLDEN)
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    for model in trial.PHASE4_PUBLIC_MODELS:
        key = f"{model.__name__}@{model.model_fields['schema_version'].default}"
        assert golden[key] == content_digest(model.model_json_schema())


def test_upstream_goldens_are_byte_unchanged():
    for name, sha in UPSTREAM_GOLDEN_SHA256.items():
        raw = (GOLDEN_DIR / name).read_bytes()
        assert hashlib.sha256(raw).hexdigest() == sha, (
            f"upstream golden {name} changed — Phase 4 must never regenerate it"
        )


# =========================================================================== #
# Point 3 — registration-order independence                                     #
# =========================================================================== #
def test_registration_order_independence():
    from guanlan_v2.orchestration.runtime_contracts import (
        Phase2RuntimeRegistry,
        phase2_public_models,
    )
    from guanlan_v2.orchestration.data.schema_registry import (
        PHASE3_PUBLIC_MODELS as DATA_PUBLIC,
    )
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_MEMORY_PUBLIC_MODELS as MEM_PUBLIC,
    )

    canonical = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)
    reversed_reg = Phase2RuntimeRegistry()
    for model in reversed(
        tuple(phase2_public_models())
        + tuple(DATA_PUBLIC)
        + tuple(MEM_PUBLIC)
        + tuple(trial.PHASE4_PUBLIC_MODELS)
    ):
        reversed_reg.register(model)
    reversed_reg.seal()
    assert reversed_reg.manifest() == canonical.manifest()
    assert reversed_reg.registry_digest == canonical.registry_digest


# =========================================================================== #
# Point 4 — Phase-4 completeness firewall (exhaustive + disjoint)               #
# =========================================================================== #
def test_public_tuple_shape_and_names():
    assert isinstance(trial.PHASE4_PUBLIC_MODELS, tuple)
    assert len(trial.PHASE4_PUBLIC_MODELS) == 16
    assert len(set(trial.PHASE4_PUBLIC_MODELS)) == 16
    names = {m.__name__ for m in trial.PHASE4_PUBLIC_MODELS}
    assert names == EXPECTED_PUBLIC_NAMES
    for model in trial.PHASE4_PUBLIC_MODELS:
        assert issubclass(model, ContractModel)


def test_internal_map_is_a_contract_model_reason_map():
    assert isinstance(trial.PHASE4_INTERNAL_MODELS, dict)
    for model, reason in trial.PHASE4_INTERNAL_MODELS.items():
        assert isinstance(model, type) and issubclass(model, ContractModel)
        assert isinstance(reason, str) and reason.strip()
    # the two nested evaluation components deliberately stay unregistered.
    names = {m.__name__ for m in trial.PHASE4_INTERNAL_MODELS}
    assert names == {"GateResult", "HonestyGateReport"}


def test_public_and_internal_partition_the_six_module_surface_exactly():
    discovered = _discover_phase4_contract_models()
    classified = set(trial.PHASE4_PUBLIC_MODELS) | set(trial.PHASE4_INTERNAL_MODELS)
    assert not (set(trial.PHASE4_PUBLIC_MODELS) & set(trial.PHASE4_INTERNAL_MODELS)), (
        "a Phase-4 contract cannot be both registered and internal"
    )
    unclassified = discovered - classified
    assert not unclassified, (
        "unreviewed Phase-4 public contracts: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in unclassified))
    )
    phantom = classified - discovered
    assert not phantom, (
        "classified models not discovered in the six Phase-4 modules: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in phantom))
    )
    assert classified == discovered
    assert len(trial.PHASE4_PUBLIC_MODELS) + len(trial.PHASE4_INTERNAL_MODELS) == len(
        discovered
    )


def test_every_public_member_has_a_closed_schema_version():
    for model in trial.PHASE4_PUBLIC_MODELS:
        field = model.model_fields.get("schema_version")
        assert field is not None
        assert isinstance(field.default, str) and field.default, model.__name__


def test_internal_surface_documents_the_non_contract_services():
    surface = trial.PHASE4_INTERNAL_SURFACE
    assert isinstance(surface, dict)
    for name in (
        "Governor", "TrialLedger", "SealedResultStore", "SealedEvaluatorGateway",
        "ExperimentStateStore", "AttributionPort", "OptimizeRoundStore", "MaturityPending",
    ):
        assert name in surface, f"internal surface must document {name}"
        assert surface[name].strip()


def test_default_registry_does_not_register_any_phase4_public_model():
    from guanlan_v2.orchestration.schema_registry import default_registry
    registered = {e.schema_ref.name for e in default_registry().manifest()}
    for model in trial.PHASE4_PUBLIC_MODELS:
        assert model.__name__ not in registered, model.__name__


# =========================================================================== #
# Point 5 — catalog: base digest guard, gate_metric material, tamper failure    #
# =========================================================================== #
def test_build_phase4_catalog_rejects_a_non_canonical_base():
    from guanlan_v2.orchestration.catalog import CatalogError
    from guanlan_v2.orchestration.data.catalog import phase3_data_catalog_snapshot

    wrong_base = phase3_data_catalog_snapshot()  # data-only, not the full base
    _ref, material = trial.joint_gate_material()
    with pytest.raises(CatalogError):
        trial.build_phase4_catalog_snapshot(
            wrong_base, joint_gate_material=material, resolved_materials=()
        )


def test_phase4_catalog_matches_the_frozen_golden():
    assert CATALOG_GOLDEN.exists(), f"missing golden: {CATALOG_GOLDEN}"
    doc = _load_json(CATALOG_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION
    assert doc["base_catalog_digest"] == _phase3_full_catalog_digest()
    assert doc["base_catalog_digest"] == trial.PHASE4_BASE_CATALOG_DIGEST
    assert doc["catalog_version"] == "phase4-full-v1"
    snap = trial.phase4_catalog_snapshot()
    assert snap.catalog_digest == trial.PHASE4_CATALOG_DIGEST
    assert snap.catalog_digest == doc["catalog_digest"]
    assert snap.catalog_digest != trial.PHASE4_BASE_CATALOG_DIGEST


def test_joint_gate_material_is_utf8_no_bom():
    raw = JOINT_GATE_MATERIAL_PATH.read_bytes()
    assert not raw.startswith(b"\xef\xbb\xbf"), "joint-gate material must have no BOM"
    raw.decode("utf-8")  # strict UTF-8 parse (raises on failure)
    _ref, material = trial.joint_gate_material()
    assert material.raw_utf8 == raw


def test_one_flipped_material_byte_fails_digest_verification():
    from guanlan_v2.orchestration.catalog import catalog_material_digest
    from guanlan_v2.orchestration.catalog_runtime import build_text_material

    ref, material = trial.joint_gate_material()
    # the honest material self-verifies.
    assert catalog_material_digest(material) == ref.content_digest
    tampered = bytearray(material.raw_utf8)
    tampered[-1] = tampered[-1] ^ 0x01
    _tref, tampered_material = build_text_material(
        id=ref.id, version=ref.version, kind="gate_metric", raw=bytes(tampered)
    )
    assert catalog_material_digest(tampered_material) != ref.content_digest
    assert tampered_material.ref.content_digest != ref.content_digest


# =========================================================================== #
# Point 6 — exactly one new gate_metric entry; workers/capabilities unchanged    #
# =========================================================================== #
def test_only_new_entry_is_the_gate_metric_and_manifests_are_otherwise_unchanged():
    from guanlan_v2.orchestration.memory.catalog import phase3_full_catalog_snapshot

    base = phase3_full_catalog_snapshot()
    snap = trial.phase4_catalog_snapshot()

    base_content = {(e.ref.id, e.ref.version): e for e in base.content_manifest}
    new_content = {(e.ref.id, e.ref.version): e for e in snap.content_manifest}
    added = set(new_content) - set(base_content)
    assert added == {("optimize.joint_gate", "1")}
    entry = new_content[("optimize.joint_gate", "1")]
    assert entry.kind == "gate_metric"
    assert entry.ref.id == "optimize.joint_gate"
    assert entry.ref.version == "1"
    # every inherited content entry is preserved byte-identically.
    for key, e in base_content.items():
        assert new_content[key] == e

    # workers + capabilities + skills are unchanged from the Phase-3 full snapshot.
    assert snap.workers == base.workers
    assert snap.capability_manifest == base.capability_manifest
    assert snap.skill_manifest == base.skill_manifest


def test_golden_gate_metric_matches_the_material():
    doc = _load_json(CATALOG_GOLDEN)
    ref, _material = trial.joint_gate_material()
    gm = doc["gate_metric"]
    assert gm["id"] == "optimize.joint_gate"
    assert gm["version"] == "1"
    assert gm["kind"] == "gate_metric"
    assert gm["content_digest"] == ref.content_digest


# =========================================================================== #
# Point 7 — SchemaRegistryResolver resolves all five digests simultaneously      #
# =========================================================================== #
def test_resolver_resolves_all_chain_digests_without_reinterpretation():
    from guanlan_v2.orchestration.eventstore import SchemaRegistryResolver
    from guanlan_v2.orchestration.schema_registry import default_registry
    from guanlan_v2.orchestration.runtime_contracts import (
        PHASE2_BASE_REGISTRY_DIGEST,
        phase2_runtime_registry,
    )
    from guanlan_v2.orchestration.data.schema_registry import build_phase3_registry
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_FULL_BASE_REGISTRY_DIGEST,
        build_phase3_full_registry,
    )

    p1 = default_registry()
    p2 = phase2_runtime_registry(PHASE2_BASE_REGISTRY_DIGEST)
    p3_data = build_phase3_registry(p2.registry_digest)
    p3_full = build_phase3_full_registry(PHASE3_FULL_BASE_REGISTRY_DIGEST)
    p4 = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)

    digests = {
        "p1": p1.registry_digest, "p2": p2.registry_digest,
        "p3_data": p3_data.registry_digest, "p3_full": p3_full.registry_digest,
        "p4": p4.registry_digest,
    }
    # all five chain digests are distinct — no "latest" alias collapsed them.
    assert len(set(digests.values())) == 5

    resolver = SchemaRegistryResolver()
    for reg in (p1, p2, p3_data, p3_full, p4):
        resolver.register(reg)
    # a Plan bound to any upstream digest resolves to that exact registry.
    assert resolver.resolve(digests["p1"]) is p1
    assert resolver.resolve(digests["p3_full"]) is p3_full
    assert resolver.resolve(digests["p4"]) is p4
    # the Phase-1 digest never reinterprets to the Phase-4 registry.
    assert resolver.resolve(digests["p1"]) is not p4


# =========================================================================== #
# Point 8 — sealed startup state-cell union; no "latest" alias                   #
# =========================================================================== #
def test_state_cell_union_is_the_reviewed_phase3_seven_plus_phase4_four():
    from guanlan_v2.orchestration.trial_ledger import (
        PHASE4_STATE_CELL_NAMESPACES,
        PHASE4_TRIAL_STATE_CELL_NAMESPACES,
    )
    from guanlan_v2.orchestration.memory.models import PHASE3_MEMORY_STATE_CELL_NAMESPACES

    assert len(PHASE3_MEMORY_STATE_CELL_NAMESPACES) == 7
    assert len(PHASE4_TRIAL_STATE_CELL_NAMESPACES) == 4
    expected = tuple(sorted(
        set(PHASE3_MEMORY_STATE_CELL_NAMESPACES) | set(PHASE4_TRIAL_STATE_CELL_NAMESPACES)
    ))
    assert PHASE4_STATE_CELL_NAMESPACES == expected
    assert list(PHASE4_STATE_CELL_NAMESPACES) == sorted(PHASE4_STATE_CELL_NAMESPACES)
    assert len(set(PHASE4_STATE_CELL_NAMESPACES)) == len(PHASE4_STATE_CELL_NAMESPACES)
    assert len(PHASE4_STATE_CELL_NAMESPACES) == 11


def test_no_latest_style_alias_in_the_trial_module_namespace():
    for name in vars(trial):
        low = name.lower()
        assert "latest" not in low, f"a 'latest'-style alias leaked into trial.py: {name}"
