# -*- coding: utf-8 -*-
"""Phase 10 · Task 11 — the cumulative registry/catalog chain node.

Locks the linear registry/catalog chain the product-pipeline phase seals, built
as a pure ADDITION over the sealed Phase-9 adapter chain (never a fork, never a
"latest" alias):

* ``build_phase10_registry(expected_phase9_digest)`` builds a *fresh sealed*
  cumulative registry over the exact Phase-9 cumulative set plus the reviewed
  six :data:`PHASE10_PUBLIC_MODELS` — five at ``@1`` under their own names plus
  ``PlanPresetRecordV2`` registered as **``PlanPresetRecord@2``** (Amendment 3);
  a wrong base digest is rejected before any registration; inherited entries
  stay byte-identical to their Phase-<=9 goldens; the digest matches the
  hand-reviewed golden.
* ``build_phase10_catalog_snapshot(...)`` seals the cumulative catalog: it
  inherits the reviewed Phase-9 catalog byte-identical and adds ONLY the three
  ``cand.*`` DETERMINISTIC candidate workers (tier READER,
  ``can_emit_decision=False``, ``selection_scope="dynamic_allowed"``, output
  ``CandidateSlate@1``), their three trusted handler materials and the ONE
  deep-decide preset-record reference guardrail. ``count_final_workers`` is
  proven == the Phase-8 count + 3 (base-relative, never a bare integer).
* the Phase-10 public/internal partition over the pipeline contract modules is
  exhaustive and disjoint; every ``PHASE10_MODULES`` name imports (the Task-1
  minor #10: a typo'd module name would be a silently inert firewall).
* EventType is UNCHANGED — Phase 10 adds no member and flips no absence guard.

Goldens are NEVER auto-regenerated by tests: a changed manifest is a reviewed
contract change regenerated by hand and re-reviewed.

Run: ``pytest tests/orchestration/test_phase10_chain.py -v``
"""
from __future__ import annotations

import hashlib
import importlib
import inspect
import json
import typing
from pathlib import Path

import pytest

from guanlan_v2.orchestration import bootstrap, phase7_registry as p7, shadow, trial
from guanlan_v2.orchestration import lane_catalog as p8
from guanlan_v2.orchestration.adapters import chain as p9
from guanlan_v2.orchestration.catalog import CatalogError, count_final_workers
from guanlan_v2.orchestration.digest import CJSON_VERSION, ContractModel, DigestModel
from guanlan_v2.orchestration.enums import (
    DataMode,
    ExecutionKind,
    Tier,
    ToolCallRequirement,
)
from guanlan_v2.orchestration.pipeline import chain as ch
from guanlan_v2.orchestration.pipeline.assembly import (
    PLAN_PRESET_RECORD_V2_SCHEMA_REF,
    PlanPresetRecordV2,
)

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
SCHEMA_GOLDEN = GOLDEN_DIR / "phase10_schema_manifest_v1.json"
CATALOG_GOLDEN = GOLDEN_DIR / "phase10_catalog_manifest_v1.json"

#: sha256 pins of the immediate upstream goldens — Phase 10 never regenerates them.
UPSTREAM_GOLDEN_SHA256 = {
    "phase9_schema_manifest_v1.json":
        "57c6ab0c1d7c09e2924f4ea602f2a984c100ecf55ac0211264072372e7077af2",
    "phase9_catalog_manifest_v1.json":
        "ae8d3a25a946b93cad80d36a6cc4c9397293787ac219331e39ce911c59a20124",
}

#: the Phase-10 contract modules whose public ContractModel subclasses the
#: completeness firewall governs. MUST equal
#: ``test_contract_completeness.PHASE10_MODULES`` (asserted below).
PHASE10_CONTRACT_MODULES = (
    "guanlan_v2.orchestration.pipeline.contracts",
    "guanlan_v2.orchestration.pipeline.assembly",
    "guanlan_v2.orchestration.pipeline.candidates",
    "guanlan_v2.orchestration.pipeline.screening",
    "guanlan_v2.orchestration.pipeline.escalation",
    "guanlan_v2.orchestration.pipeline.deep_decide",
    "guanlan_v2.orchestration.pipeline.live_decide",
    "guanlan_v2.orchestration.pipeline.api",
    "guanlan_v2.orchestration.pipeline.chain",
)

#: the six reviewed public names + their REGISTERED keys (Amendment 3: the v2
#: preset record registers under the Phase-7 family name at version 2).
EXPECTED_PUBLIC_NAMES = frozenset({
    "CandidateSlate", "RecommendationSlate", "EscalationReport",
    "TaSubmission", "RunSubject", "PlanPresetRecordV2",
})
EXPECTED_NEW_KEYS = frozenset({
    "CandidateSlate@1", "RecommendationSlate@1", "EscalationReport@1",
    "TaSubmission@1", "RunSubject@1", "PlanPresetRecord@2",
})

#: the nine reviewed INTERNAL ContractModel value carriers.
EXPECTED_INTERNAL_NAMES = frozenset({
    "CandidateEntry", "RecommendationEntry", "EscalationTrigger",
    "RankingArtifact", "RankingRow", "EscalationContext",
    "ScreeningBatch", "ScreeningLaneEntry", "ScreeningCostPreview",
})

#: the three new candidate worker ids (never a new EventType / method id).
EXPECTED_NEW_WORKER_IDS = frozenset({"cand.v4", "cand.lane0", "cand.model"})

#: the frozen Phase-8 EventType value set — Phase 10 must not touch it
#: (verbatim the Phase-9 chain pin).
EXPECTED_EVENTTYPE_VALUES = frozenset({
    "ArtifactRelated", "ArtifactStaged", "BudgetReleased", "BudgetReserved",
    "BudgetSettled", "CaseCreated", "CaseMatured", "CaseReviewed",
    "ContextSnapshotFrozen", "DebateMessagePublished", "ExperimentStateChanged",
    "LayerCommitted", "NodeStateChanged", "PlanApproved", "PlanDrafted", "PlanFrozen",
    "PlanRejected", "RunCancelled", "RunCompleted", "RunFailed", "RunRequested",
    "ShadowIntentIssued", "ShadowTargetApplied", "TrialExhausted", "TrialReserved",
    "TrialRevealed",
})


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _discover_phase10_contract_models() -> set[type]:
    found: set[type] = set()
    for module_name in PHASE10_CONTRACT_MODULES:
        module = importlib.import_module(module_name)
        for obj in vars(module).values():
            if (
                inspect.isclass(obj)
                and issubclass(obj, ContractModel)
                and obj not in (ContractModel, DigestModel)
                and obj.__module__ == module_name
                and not obj.__name__.startswith("_")
            ):
                found.add(obj)
    return found


# =========================================================================== #
# Point 1 — build rejects a wrong base; the correct base seals the right digest #
# =========================================================================== #
def test_build_phase10_registry_rejects_a_wrong_expected_digest():
    with pytest.raises(ch.Phase10RegistryError):
        ch.build_phase10_registry("0" * 64)
    # the Phase-8 digest is NOT the Phase-9 base either (no "latest" collapse).
    with pytest.raises(ch.Phase10RegistryError):
        ch.build_phase10_registry(p8.PHASE8_REGISTRY_DIGEST)
    # Phase 10's own digest is not its own base (wrong-base, other direction).
    with pytest.raises(ch.Phase10RegistryError):
        ch.build_phase10_registry(ch.PHASE10_REGISTRY_DIGEST)


def test_build_phase10_registry_seals_and_matches_the_frozen_digest():
    reg = ch.build_phase10_registry(ch.PHASE10_BASE_REGISTRY_DIGEST)
    assert reg.sealed is True
    assert reg.registry_digest == ch.PHASE10_REGISTRY_DIGEST
    # a fresh sealed instance per call (never a shared mutable singleton).
    other = ch.build_phase10_registry(ch.PHASE10_BASE_REGISTRY_DIGEST)
    assert other is not reg
    assert other.registry_digest == reg.registry_digest


def test_phase10_base_registry_digest_is_the_phase9_digest():
    assert ch.PHASE10_BASE_REGISTRY_DIGEST == p9.PHASE9_REGISTRY_DIGEST
    assert ch.PHASE10_REGISTRY_DIGEST != ch.PHASE10_BASE_REGISTRY_DIGEST


# =========================================================================== #
# Point 2 — golden equality; inherited byte-identical; upstream goldens frozen   #
# =========================================================================== #
def test_registry_matches_the_frozen_golden_entry_for_entry():
    assert SCHEMA_GOLDEN.exists(), f"missing golden: {SCHEMA_GOLDEN}"
    doc = _load_json(SCHEMA_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION == "sha256+cjson-v1"
    assert doc["base_registry_digest"] == p9.PHASE9_REGISTRY_DIGEST
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    reg = ch.build_phase10_registry(ch.PHASE10_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    assert set(manifest) == set(golden), (
        "phase10 registry key set drifted from phase10_schema_manifest_v1.json; "
        "regenerate + re-review by hand if intended"
    )
    for key in sorted(golden):
        assert manifest[key] == golden[key], f"JSON-schema digest drift for {key}"
    assert reg.registry_digest == doc["registry_digest"]


def test_inherited_entries_are_byte_identical_to_the_phase9_golden():
    phase9_doc = _load_json(GOLDEN_DIR / "phase9_schema_manifest_v1.json")
    phase9 = {e["key"]: e["json_schema_digest"] for e in phase9_doc["entries"]}
    reg = ch.build_phase10_registry(ch.PHASE10_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    # every Phase-9 (cumulative) key is inherited byte-identical …
    for key, digest in phase9.items():
        assert manifest[key] == digest, f"inherited schema {key} drifted in phase10"
    # … and the only new keys are exactly the six Phase-10 registered keys
    # (five own-name @1 plus PlanPresetRecord@2 — and NEVER PlanPresetRecordV2@2).
    new_keys = set(manifest) - set(phase9)
    assert new_keys == set(EXPECTED_NEW_KEYS)
    assert "PlanPresetRecordV2@2" not in manifest
    assert len(new_keys) == 6


def test_inherited_entries_are_byte_identical_across_every_upstream_manifest():
    """Walk ALL phase schema goldens — every inherited key stays byte-identical."""
    reg = ch.build_phase10_registry(ch.PHASE10_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    upstream_goldens = (
        "schema_manifest_v1.json",
        "runtime_schema_manifest_v1.json",
        "data_schema_manifest_v1.json",
        "phase3_full_schema_manifest_v1.json",
        "phase4_schema_manifest_v1.json",
        "phase5_schema_manifest_v1.json",
        "phase6_schema_manifest_v1.json",
        "phase7_schema_manifest_v1.json",
        "phase8_schema_manifest_v1.json",
        "phase9_schema_manifest_v1.json",
    )
    for fname in upstream_goldens:
        path = GOLDEN_DIR / fname
        if not path.exists():
            continue
        doc = _load_json(path)
        for e in doc.get("entries", []):
            key = e["key"]
            if key in manifest:
                assert manifest[key] == e["json_schema_digest"], (
                    f"inherited schema {key} drifted from {fname} in phase10"
                )


def test_new_public_contract_digests_are_recomputable_from_the_models():
    from guanlan_v2.orchestration.digest import content_digest

    doc = _load_json(SCHEMA_GOLDEN)
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    for model in ch.PHASE10_PUBLIC_MODELS:
        if model is PlanPresetRecordV2:
            continue  # registered through the renamed identity (next test)
        key = f"{model.__name__}@{model.model_fields['schema_version'].default}"
        assert golden[key] == content_digest(model.model_json_schema())


def test_plan_preset_record_v2_registers_as_the_reviewed_base_name_at_v2():
    """Amendment 3: the registered identity is ``PlanPresetRecord@2`` (the exact
    ``assembly.PLAN_PRESET_RECORD_V2_SCHEMA_REF``), served by a 1:1
    field-for-field registration subclass of the reviewed ``PlanPresetRecordV2``
    — same fields, deterministic schema, resolvable through the sealed registry.
    """
    from guanlan_v2.orchestration.digest import content_digest

    assert PLAN_PRESET_RECORD_V2_SCHEMA_REF.key == "PlanPresetRecord@2"
    reg = ch.build_phase10_registry(ch.PHASE10_BASE_REGISTRY_DIGEST)
    resolved = reg.resolve(PLAN_PRESET_RECORD_V2_SCHEMA_REF)
    assert issubclass(resolved, PlanPresetRecordV2)
    assert resolved.__name__ == "PlanPresetRecord"
    assert set(resolved.model_fields) == set(PlanPresetRecordV2.model_fields)
    # the registered identity's schema digest is deterministic + golden-frozen.
    doc = _load_json(SCHEMA_GOLDEN)
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    assert golden["PlanPresetRecord@2"] == content_digest(
        resolved.model_json_schema())
    # …and distinct from the inherited v1 family entry.
    assert "PlanPresetRecord@1" in golden
    assert golden["PlanPresetRecord@1"] != golden["PlanPresetRecord@2"]


def test_upstream_goldens_are_byte_unchanged():
    for fname, sha in UPSTREAM_GOLDEN_SHA256.items():
        raw = (GOLDEN_DIR / fname).read_bytes()
        assert hashlib.sha256(raw).hexdigest() == sha, (
            f"upstream golden {fname} changed — Phase 10 must never regenerate it"
        )


# =========================================================================== #
# Point 3 — registration-order independence                                     #
# =========================================================================== #
def test_registration_order_independence():
    from guanlan_v2.orchestration.data.schema_registry import (
        PHASE3_PUBLIC_MODELS as DATA_PUBLIC,
    )
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_MEMORY_PUBLIC_MODELS as MEM_PUBLIC,
    )
    from guanlan_v2.orchestration.runtime_contracts import (
        Phase2RuntimeRegistry,
        phase2_public_models,
    )

    canonical = ch.build_phase10_registry(ch.PHASE10_BASE_REGISTRY_DIGEST)
    phase10 = tuple(
        ch._registered_plan_preset_record_v2() if m is PlanPresetRecordV2 else m
        for m in ch.PHASE10_PUBLIC_MODELS
    )
    reversed_reg = Phase2RuntimeRegistry()
    for model in reversed(
        tuple(phase2_public_models())
        + tuple(DATA_PUBLIC)
        + tuple(MEM_PUBLIC)
        + tuple(trial.PHASE4_PUBLIC_MODELS)
        + tuple(bootstrap.PHASE5_PUBLIC_MODELS)
        + tuple(shadow.PHASE6_PUBLIC_MODELS)
        + tuple(p7.PHASE7_PUBLIC_MODELS)
        + tuple(p8.PHASE8_PUBLIC_MODELS)
        + tuple(p9.PHASE9_PUBLIC_MODELS)
        + phase10
    ):
        reversed_reg.register(model)
    reversed_reg.seal()
    assert reversed_reg.manifest() == canonical.manifest()
    assert reversed_reg.registry_digest == canonical.registry_digest


# =========================================================================== #
# Point 4 — Phase-10 completeness firewall (exhaustive + disjoint)              #
# =========================================================================== #
def test_public_tuple_shape_and_names():
    assert isinstance(ch.PHASE10_PUBLIC_MODELS, tuple)
    assert len(ch.PHASE10_PUBLIC_MODELS) == 6
    assert len(set(ch.PHASE10_PUBLIC_MODELS)) == 6
    names = {m.__name__ for m in ch.PHASE10_PUBLIC_MODELS}
    assert names == EXPECTED_PUBLIC_NAMES
    for model in ch.PHASE10_PUBLIC_MODELS:
        assert issubclass(model, ContractModel)


def test_internal_map_is_a_reviewed_reason_map():
    assert isinstance(ch.PHASE10_INTERNAL_MODELS, dict)
    names = {m.__name__ for m in ch.PHASE10_INTERNAL_MODELS}
    assert names == EXPECTED_INTERNAL_NAMES
    for model, reason in ch.PHASE10_INTERNAL_MODELS.items():
        assert isinstance(model, type) and issubclass(model, ContractModel)
        assert isinstance(reason, str) and reason.strip()


def test_phase10_contract_modules_stay_in_sync_with_the_discovery_firewall():
    """Close the "a public contract in a NEW Phase-10 module escapes both
    firewalls" hole (the Phase-9 chain precedent), and discharge the Task-1
    review minor #10: every pre-listed ``PHASE10_MODULES`` name must import — a
    typo'd name is a silently inert exclusion set."""
    tcc = importlib.import_module("tests.orchestration.test_contract_completeness")
    assert set(PHASE10_CONTRACT_MODULES) == set(tcc.PHASE10_MODULES), (
        "PHASE10_CONTRACT_MODULES has drifted from test_contract_completeness."
        "PHASE10_MODULES; a public contract in a module listed in only one of "
        "them escapes both the discovery and the classification firewall"
    )
    for module_name in tcc.PHASE10_MODULES:
        importlib.import_module(module_name)  # ModuleNotFoundError = typo'd name


def test_internal_map_partitions_the_contract_surface_exactly():
    discovered = _discover_phase10_contract_models()
    public = set(ch.PHASE10_PUBLIC_MODELS)
    internal = set(ch.PHASE10_INTERNAL_MODELS)
    classified = public | internal
    assert not (public & internal), (
        "a Phase-10 contract cannot be both registered and internal"
    )
    unclassified = discovered - classified
    assert not unclassified, (
        "unreviewed Phase-10 public contracts: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in unclassified))
    )
    phantom = classified - discovered
    assert not phantom, (
        "classified contract models not discovered in the Phase-10 modules: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in phantom))
    )
    assert classified == discovered


def test_every_public_member_has_a_closed_schema_version():
    for model in ch.PHASE10_PUBLIC_MODELS:
        field = model.model_fields.get("schema_version")
        assert field is not None
        assert isinstance(field.default, str) and field.default, model.__name__
        # FINAL-REVIEW minor 6: closedness must not rest on a non-empty string
        # DEFAULT alone — the annotation itself must be a ``Literal`` pinning
        # exactly that version, so a wrong schema_version cannot even construct.
        assert typing.get_origin(field.annotation) is typing.Literal, model.__name__
        assert typing.get_args(field.annotation) == (field.default,), model.__name__
    assert PlanPresetRecordV2.model_fields["schema_version"].default == "2"


def test_default_registry_does_not_register_any_phase10_public_model():
    from guanlan_v2.orchestration.schema_registry import default_registry

    registered = {e.schema_ref.name for e in default_registry().manifest()}
    for model in ch.PHASE10_PUBLIC_MODELS:
        assert model.__name__ not in registered, model.__name__
    # the sixth model registers under the REVIEWED identity "PlanPresetRecord",
    # not its class name — that is the name that could actually collide.
    assert PLAN_PRESET_RECORD_V2_SCHEMA_REF.name not in registered


# =========================================================================== #
# Point 5 — EventType is UNCHANGED (no new member, no absence-guard flip)        #
# =========================================================================== #
def test_eventtype_value_set_is_the_frozen_phase8_set():
    from guanlan_v2.orchestration.events import EventType

    values = {e.value for e in EventType}
    assert values == EXPECTED_EVENTTYPE_VALUES
    assert len(values) == len(EXPECTED_EVENTTYPE_VALUES)


def test_no_latest_style_alias_in_the_phase10_chain_namespace():
    for name in vars(ch):
        if name.startswith("PHASE10") or "phase10" in name.lower():
            assert "latest" not in name.lower(), (
                f"a 'latest'-style alias leaked into the phase10 chain: {name}"
            )
    offenders = [n for n in dir(ch) if "latest" in n.lower() and not n.startswith("_")]
    assert offenders == [], f"pipeline.chain exposes a 'latest' alias: {offenders}"


# =========================================================================== #
# Point 6 — the catalog seal: three cand.* workers + the preset reference        #
# =========================================================================== #
def test_phase10_catalog_base_digest_is_the_phase9_digest():
    assert ch.PHASE10_BASE_CATALOG_DIGEST == p9.PHASE9_CATALOG_DIGEST
    assert ch.PHASE10_CATALOG_DIGEST != ch.PHASE10_BASE_CATALOG_DIGEST


def test_build_phase10_catalog_rejects_a_non_canonical_base():
    _refs, materials = ch.build_phase10_materials()
    with pytest.raises(CatalogError):
        ch.build_phase10_catalog_snapshot(
            p8.phase8_catalog_snapshot(), resolved_materials=materials)


def test_phase10_catalog_matches_the_frozen_golden():
    assert CATALOG_GOLDEN.exists(), f"missing golden: {CATALOG_GOLDEN}"
    doc = _load_json(CATALOG_GOLDEN)
    snap = ch.phase10_catalog_snapshot()
    assert doc["algorithm"] == CJSON_VERSION
    assert doc["base_catalog_digest"] == p9.PHASE9_CATALOG_DIGEST
    assert doc["result_catalog_digest"] == snap.catalog_digest == ch.PHASE10_CATALOG_DIGEST
    assert doc["result_catalog_digest"] != doc["base_catalog_digest"]
    assert doc["catalog_version"] == snap.catalog_version == "phase10-full-v1"
    assert set(doc["new_worker_ids"]) == EXPECTED_NEW_WORKER_IDS
    base = p9.phase9_catalog_snapshot()
    base_worker_ids = {w.id for w in base.workers}
    new_workers = {w.id: w for w in snap.workers if w.id not in base_worker_ids}
    assert {wid: w.semantic_digest() for wid, w in new_workers.items()} == (
        doc["new_worker_semantic_digests"])
    base_keys = {e.ref_key for e in base.content_manifest}
    added = {
        f"{e.ref.id}@{e.ref.version}": e.ref.content_digest
        for e in snap.content_manifest if e.ref_key not in base_keys
    }
    assert added == doc["added_content_materials"]


def test_deep_decide_preset_reference_binds_the_committed_sealed_record():
    """The catalog's preset-record reference reproduces from the COMMITTED
    preset file (identity + semantic digest + registered schema key) and the
    golden pins it — a preset edit without a catalog re-freeze is loud."""
    from guanlan_v2.orchestration.pipeline.assembly import (
        PRODUCTION_PRESETS_DIR,
        load_phase10_preset_registry,
    )
    from guanlan_v2.orchestration.pipeline.deep_decide import (
        DEEP_DECIDE_PRESET_ID,
    )

    doc = _load_json(CATALOG_GOLDEN)["deep_decide_preset_record_ref"]
    record = load_phase10_preset_registry(PRODUCTION_PRESETS_DIR).get(
        DEEP_DECIDE_PRESET_ID)
    assert doc == {
        "kind": "plan_preset_record_ref",
        "preset_id": DEEP_DECIDE_PRESET_ID,
        "preset_version": "1",
        "record_digest": record.semantic_digest(),
        "schema_key": PLAN_PRESET_RECORD_V2_SCHEMA_REF.key,
    }
    # a drifted reference doc is refused at build (not just at golden compare).
    _refs, materials = ch.build_phase10_materials()
    from guanlan_v2.orchestration.catalog_runtime import build_text_material

    tampered = []
    for m in materials:
        if m.ref.id == ch.DEEP_DECIDE_PRESET_REF_MATERIAL_ID:
            bad = dict(json.loads(m.raw_utf8.decode("utf-8")))
            bad["record_digest"] = "0" * 64
            _r, mat = build_text_material(
                id=m.ref.id, version="1", kind="guardrail",
                raw=json.dumps(bad, sort_keys=True, ensure_ascii=False,
                               separators=(",", ":")).encode("utf-8"))
            tampered.append(mat)
        else:
            tampered.append(m)
    with pytest.raises(CatalogError, match="preset reference does not match"):
        ch.build_phase10_catalog_snapshot(
            p9.phase9_catalog_snapshot(), resolved_materials=tuple(tampered))


def test_inherited_catalog_manifests_are_byte_identical_to_phase9():
    base = p9.phase9_catalog_snapshot()
    snap = ch.phase10_catalog_snapshot()
    # skills and capabilities pass through byte-identical; workers grow by
    # exactly the three cand.* finals; only the content manifest gains the four
    # Phase-10 materials.
    assert snap.skill_manifest == base.skill_manifest
    assert snap.capability_manifest == base.capability_manifest
    base_workers = {w.id: w for w in base.workers}
    for w in snap.workers:
        if w.id in base_workers:
            assert w == base_workers[w.id], f"inherited worker {w.id} drifted"
    assert {w.id for w in snap.workers} - set(base_workers) == EXPECTED_NEW_WORKER_IDS
    base_content = {e.ref_key: e for e in base.content_manifest}
    for e in snap.content_manifest:
        if e.ref_key in base_content:
            assert e == base_content[e.ref_key], (
                f"inherited content material {e.ref_key} drifted in phase10"
            )
    added = [e for e in snap.content_manifest if e.ref_key not in base_content]
    assert len(added) == 4  # three handlers + one preset-reference guardrail
    for e in added:
        assert e.source_identity == ch.PHASE10_SOURCE_IDENTITY


def test_count_final_workers_is_the_phase8_count_plus_three():
    # base-relative (the 枚举钉旧 vaccine): the +3 is the pinned reviewed
    # addition; the base count comes from the inherited catalog, never a bare
    # integer. Phase 9 added no worker, so Phase-8 count == Phase-9 count.
    snap = ch.phase10_catalog_snapshot()
    assert count_final_workers(snap) == count_final_workers(
        p8.phase8_catalog_snapshot()) + 3
    assert count_final_workers(snap) == count_final_workers(
        p9.phase9_catalog_snapshot()) + 3


def test_cand_worker_specs_carry_the_reviewed_shape():
    snap = ch.phase10_catalog_snapshot()
    by_id = {w.id: w for w in snap.workers}
    for wid in EXPECTED_NEW_WORKER_IDS:
        w = by_id[wid]
        assert w.catalog_role == "final"
        assert w.selection_scope == "dynamic_allowed"
        assert w.tier is Tier.READER
        assert w.lane == "quant"
        assert w.execution.kind is ExecutionKind.DETERMINISTIC
        assert w.execution.handler_ref is not None
        assert w.execution.handler_ref.id == ch.CAND_HANDLER_IDS[wid]
        assert w.system_prompt_ref is None
        assert w.skills == () and w.guardrail_refs == ()
        assert w.capability_allowlist == ()
        assert w.evidence_policy.tool_calls is ToolCallRequirement.FORBIDDEN
        assert w.read_categories == ("market_data",)
        # the Task-2 params dual-path ruling: FACTORY-BOUND (no node params).
        assert w.params_schema_ref is None
        assert w.inputs == ()
        assert len(w.outputs) == 1
        out = w.outputs[0]
        assert out.name == "primary"
        assert out.schema_ref.name == "CandidateSlate"
        assert out.schema_ref.version == "1"
        assert w.can_emit_decision is False
        assert w.decision_authority == "none"
        assert w.supported_modes == (DataMode.ONLINE,)


def test_cand_handler_ids_match_the_reviewed_worker_ids():
    from guanlan_v2.orchestration.pipeline.candidates import (
        CAND_LANE0_WORKER_ID,
        CAND_MODEL_WORKER_ID,
        CAND_V4_WORKER_ID,
    )

    assert set(ch.CAND_WORKER_IDS) == {
        CAND_V4_WORKER_ID, CAND_LANE0_WORKER_ID, CAND_MODEL_WORKER_ID}
    assert set(ch.CAND_HANDLER_IDS) == set(ch.CAND_WORKER_IDS)


def test_compat_workers_stay_static_legacy_only():
    base = {w.id: w for w in p9.phase9_catalog_snapshot().workers}
    snap = ch.phase10_catalog_snapshot()
    compat = [w for w in snap.workers if w.id.startswith("compat.")]
    assert compat, "the compat.* mirror must still be present"
    for w in compat:
        assert w == base[w.id], f"compat worker {w.id} drifted in phase10"
        assert w.capability_allowlist == (), f"compat worker {w.id} gained a capability"


def test_no_write_shaped_capability_and_no_new_capability_id():
    base = p9.phase9_catalog_snapshot()
    snap = ch.phase10_catalog_snapshot()
    assert {e.ref_key for e in snap.capability_manifest} == {
        e.ref_key for e in base.capability_manifest
    }
    write_markers = ("order", "trade", "write", "submit", "execute", "place")
    for entry in snap.capability_manifest:
        low = entry.ref.id.lower()
        assert not any(m in low for m in write_markers), (
            f"a write-shaped capability leaked into the phase10 catalog: {entry.ref.id}"
        )
