# -*- coding: utf-8 -*-
"""Phase 7 · Task 9 — cumulative Phase-7 registry / catalog chain + planner materials.

Locks the linear registry/catalog chain the dynamic-Planner phase contributes,
built as a pure ADDITION over the sealed Phase-6 chain (never a fork, never a
"latest" alias):

* ``build_phase7_registry(expected_phase6_digest)`` builds a *fresh sealed*
  cumulative registry over the exact Phase-6 cumulative set plus the reviewed
  :data:`PHASE7_PUBLIC_MODELS` (the eight dynamic-Planner payloads); a wrong base
  digest is rejected before any registration; inherited entries stay
  byte-identical to their Phase-<=6 goldens; the digest is registration-order
  independent and matches the hand-reviewed golden;
* ``build_phase7_catalog_snapshot(phase6_snapshot, *, planner_materials)`` adds
  ONLY the catalog-owned planner content/skill/guardrail manifest entries and
  **zero WorkerSpec** — the Planner is deliberately not a selectable worker, so
  ``count_final_workers`` is unchanged from Phase 6 while three new materials
  resolve with matching kind + digest;
* the Phase-7 public/internal partition over the five Phase-7 contract modules
  (``orchestrator`` / ``plan_presets`` / ``plan_diff`` / ``approval`` /
  ``planner_gateway``) is exhaustive and disjoint;
* ``build_phase7_planner_spec(catalog)`` derives its refs from the Phase-7 catalog
  manifests by exact id/version/digest and freezes as ``planner_spec_digest``;
* no ``EventType`` member was added (stays 25) and no Phase-1 absence/
  deferred-payload guard was touched (nothing pins a Phase-7 model).

Goldens are NEVER auto-regenerated by tests: a changed manifest is a reviewed
contract change regenerated by hand and re-reviewed.

Run: ``pytest tests/orchestration/test_phase7_registry.py -v``
"""
from __future__ import annotations

import hashlib
import importlib
import inspect
import json
from pathlib import Path

import pytest

from guanlan_v2.orchestration import bootstrap, shadow, trial
from guanlan_v2.orchestration import phase7_registry as p7
from guanlan_v2.orchestration.catalog import (
    ResolvedTextMaterial,
    catalog_material_digest,
    count_final_workers,
    parse_skill_v1,
)
from guanlan_v2.orchestration.digest import (
    CJSON_VERSION,
    ContractModel,
    DigestModel,
    content_digest,
)

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
SCHEMA_GOLDEN = GOLDEN_DIR / "phase7_schema_manifest_v1.json"
CATALOG_GOLDEN = GOLDEN_DIR / "phase7_catalog_manifest_v1.json"

#: sha256 pins of the immediate upstream goldens — Phase 7 never regenerates them.
UPSTREAM_GOLDEN_SHA256 = {
    "phase6_schema_manifest_v1.json":
        "3f6e3116007d62897f31e6646a12a3c1afe8845d866f1e9482aa15ec47ea9eb9",
    "phase6_catalog_manifest_v1.json":
        "dc68bb50b00943cd616ad8a9a659e5311eacf976f17f70ff31c19ca030a27507",
}

#: the five Phase-7 contract modules the completeness firewall governs.
PHASE7_CONTRACT_MODULES = (
    "guanlan_v2.orchestration.orchestrator",
    "guanlan_v2.orchestration.plan_presets",
    "guanlan_v2.orchestration.plan_diff",
    "guanlan_v2.orchestration.approval",
    "guanlan_v2.orchestration.planner_gateway",
)

#: the eight reviewed names the registered Phase-7 surface must equal.
EXPECTED_PUBLIC_NAMES = frozenset({
    "PlannerSpec", "PlannerAttemptRecord", "PlannerRunRecord", "PlanPresetRecord",
    "PlanDiffEntry", "PlanDiff", "PendingPlanApproval", "ApprovalLease",
})

#: the six reviewed INTERNAL Phase-7 contract names the partition must equal.
EXPECTED_INTERNAL_NAMES = frozenset({
    "PlannerDependencyEnvelope", "PlannerNodeEnvelope", "PlannerDraftEnvelope",
    "PlanPresetManifestEntry", "ApprovalJournalRow", "LeaseRevocation",
})

#: the three catalog-owned planner material ids (@1).
EXPECTED_CONTENT_MATERIAL_KEYS = ("orchestrator.planner.guardrail@1", "orchestrator.planner.prompt@1")
EXPECTED_SKILL_MATERIAL_KEYS = ("orchestrator.planner.skill@1",)

#: still-deferred Phase-8 payloads — absent from every registry in the chain.
STILL_DEFERRED_NAMES = ("DebateMessage",)


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _discover_phase7_contract_models() -> set[type]:
    found: set[type] = set()
    for module_name in PHASE7_CONTRACT_MODULES:
        module = importlib.import_module(module_name)
        for obj in vars(module).values():
            if (
                inspect.isclass(obj)
                and issubclass(obj, ContractModel)
                and obj not in (ContractModel, DigestModel)
                and obj.__module__ == module_name
                and not obj.__name__.startswith("_")
            ):
                found.add(obj)
    return found


# =========================================================================== #
# Point 1 — build rejects a wrong base; the correct base seals the right digest #
# =========================================================================== #
def test_build_phase7_registry_rejects_a_wrong_expected_digest():
    with pytest.raises(p7.Phase7RegistryError):
        p7.build_phase7_registry("0" * 64)
    # the Phase-5 digest is NOT the Phase-6 base either (no "latest" collapse).
    with pytest.raises(p7.Phase7RegistryError):
        p7.build_phase7_registry(bootstrap.PHASE5_REGISTRY_DIGEST)


def test_build_phase7_registry_seals_and_matches_the_frozen_digest():
    reg = p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST)
    assert reg.sealed is True
    assert reg.registry_digest == p7.PHASE7_REGISTRY_DIGEST
    # a fresh sealed instance per call (never a shared mutable singleton).
    other = p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST)
    assert other is not reg
    assert other.registry_digest == reg.registry_digest


def test_phase7_base_registry_digest_is_the_phase6_digest():
    assert p7.PHASE7_BASE_REGISTRY_DIGEST == shadow.PHASE6_REGISTRY_DIGEST
    assert p7.PHASE7_REGISTRY_DIGEST != p7.PHASE7_BASE_REGISTRY_DIGEST


# =========================================================================== #
# Point 2 — golden equality; inherited byte-identical; upstream goldens frozen   #
# =========================================================================== #
def test_registry_matches_the_frozen_golden_entry_for_entry():
    assert SCHEMA_GOLDEN.exists(), f"missing golden: {SCHEMA_GOLDEN}"
    doc = _load_json(SCHEMA_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION == "sha256+cjson-v1"
    assert doc["base_registry_digest"] == shadow.PHASE6_REGISTRY_DIGEST
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    reg = p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    assert set(manifest) == set(golden), (
        "phase7 registry key set drifted from phase7_schema_manifest_v1.json; "
        "regenerate + re-review by hand if intended"
    )
    for key in sorted(golden):
        assert manifest[key] == golden[key], f"JSON-schema digest drift for {key}"
    assert reg.registry_digest == doc["registry_digest"]


def test_inherited_entries_are_byte_identical_to_the_phase6_golden():
    phase6_doc = _load_json(GOLDEN_DIR / "phase6_schema_manifest_v1.json")
    phase6 = {e["key"]: e["json_schema_digest"] for e in phase6_doc["entries"]}
    reg = p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    # every Phase-6 (cumulative) key is inherited byte-identical …
    for key, digest in phase6.items():
        assert manifest[key] == digest, f"inherited schema {key} drifted in phase7"
    # … and the only new keys are exactly the eight Phase-7 public contracts.
    new_keys = set(manifest) - set(phase6)
    assert {k.split("@")[0] for k in new_keys} == EXPECTED_PUBLIC_NAMES
    assert len(new_keys) == 8


def test_inherited_entries_are_byte_identical_across_every_upstream_manifest():
    """Walk ALL phase schema goldens — every inherited key stays byte-identical."""
    reg = p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    upstream_goldens = (
        "schema_manifest_v1.json",
        "runtime_schema_manifest_v1.json",
        "data_schema_manifest_v1.json",
        "phase3_full_schema_manifest_v1.json",
        "phase4_schema_manifest_v1.json",
        "phase5_schema_manifest_v1.json",
        "phase6_schema_manifest_v1.json",
    )
    for fname in upstream_goldens:
        path = GOLDEN_DIR / fname
        if not path.exists():
            continue
        doc = _load_json(path)
        for e in doc.get("entries", []):
            key = e["key"]
            if key in manifest:
                assert manifest[key] == e["json_schema_digest"], (
                    f"inherited schema {key} drifted from {fname} in phase7"
                )


def test_new_public_contract_digests_are_recomputable_from_the_models():
    doc = _load_json(SCHEMA_GOLDEN)
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    for model in p7.PHASE7_PUBLIC_MODELS:
        key = f"{model.__name__}@{model.model_fields['schema_version'].default}"
        assert golden[key] == content_digest(model.model_json_schema())


def test_upstream_goldens_are_byte_unchanged():
    for fname, sha in UPSTREAM_GOLDEN_SHA256.items():
        raw = (GOLDEN_DIR / fname).read_bytes()
        assert hashlib.sha256(raw).hexdigest() == sha, (
            f"upstream golden {fname} changed — Phase 7 must never regenerate it"
        )


# =========================================================================== #
# Point 3 — registration-order independence                                     #
# =========================================================================== #
def test_registration_order_independence():
    from guanlan_v2.orchestration.data.schema_registry import (
        PHASE3_PUBLIC_MODELS as DATA_PUBLIC,
    )
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_MEMORY_PUBLIC_MODELS as MEM_PUBLIC,
    )
    from guanlan_v2.orchestration.runtime_contracts import (
        Phase2RuntimeRegistry,
        phase2_public_models,
    )

    canonical = p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST)
    reversed_reg = Phase2RuntimeRegistry()
    for model in reversed(
        tuple(phase2_public_models())
        + tuple(DATA_PUBLIC)
        + tuple(MEM_PUBLIC)
        + tuple(trial.PHASE4_PUBLIC_MODELS)
        + tuple(bootstrap.PHASE5_PUBLIC_MODELS)
        + tuple(shadow.PHASE6_PUBLIC_MODELS)
        + tuple(p7.PHASE7_PUBLIC_MODELS)
    ):
        reversed_reg.register(model)
    reversed_reg.seal()
    assert reversed_reg.manifest() == canonical.manifest()
    assert reversed_reg.registry_digest == canonical.registry_digest


# =========================================================================== #
# Point 4 — Phase-7 completeness firewall (exhaustive + disjoint)               #
# =========================================================================== #
def test_public_tuple_shape_and_names():
    assert isinstance(p7.PHASE7_PUBLIC_MODELS, tuple)
    assert len(p7.PHASE7_PUBLIC_MODELS) == 8
    assert len(set(p7.PHASE7_PUBLIC_MODELS)) == 8
    names = {m.__name__ for m in p7.PHASE7_PUBLIC_MODELS}
    assert names == EXPECTED_PUBLIC_NAMES
    for model in p7.PHASE7_PUBLIC_MODELS:
        assert issubclass(model, ContractModel)


def test_internal_map_is_a_contract_model_reason_map():
    assert isinstance(p7.PHASE7_INTERNAL_MODELS, dict)
    names = {m.__name__ for m in p7.PHASE7_INTERNAL_MODELS}
    assert names == EXPECTED_INTERNAL_NAMES
    for model, reason in p7.PHASE7_INTERNAL_MODELS.items():
        assert isinstance(model, type) and issubclass(model, ContractModel)
        assert isinstance(reason, str) and reason.strip()


def test_public_and_internal_partition_the_module_surface_exactly():
    discovered = _discover_phase7_contract_models()
    public = set(p7.PHASE7_PUBLIC_MODELS)
    internal = set(p7.PHASE7_INTERNAL_MODELS)
    classified = public | internal
    assert not (public & internal), "a Phase-7 contract cannot be both registered and internal"
    unclassified = discovered - classified
    assert not unclassified, (
        "unreviewed Phase-7 public contracts: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in unclassified))
    )
    phantom = classified - discovered
    assert not phantom, (
        "classified models not discovered in the five Phase-7 modules: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in phantom))
    )
    assert classified == discovered
    assert len(public) + len(internal) == len(discovered)


def test_every_public_member_has_a_closed_schema_version():
    for model in p7.PHASE7_PUBLIC_MODELS:
        field = model.model_fields.get("schema_version")
        assert field is not None
        assert isinstance(field.default, str) and field.default, model.__name__


def test_default_registry_does_not_register_any_phase7_public_model():
    from guanlan_v2.orchestration.schema_registry import default_registry
    registered = {e.schema_ref.name for e in default_registry().manifest()}
    for model in p7.PHASE7_PUBLIC_MODELS:
        assert model.__name__ not in registered, model.__name__


# =========================================================================== #
# Point 5 — catalog: planner materials, no new worker, count unchanged           #
# =========================================================================== #
def test_build_phase7_catalog_rejects_a_non_canonical_base():
    from guanlan_v2.orchestration.catalog import CatalogError

    materials = p7.load_planner_materials()
    # a Phase-4 catalog (a genuinely different digest) is not the legal Phase-6
    # base. NB: the Phase-5/6 catalogs share a digest (Phase 6 is an identity node),
    # so the Phase-5 snapshot IS a legal base — only a truly different one is refused.
    with pytest.raises(CatalogError):
        p7.build_phase7_catalog_snapshot(
            trial.phase4_catalog_snapshot(), planner_materials=materials
        )


def test_phase7_catalog_adds_only_planner_materials_no_worker():
    base = shadow.phase6_catalog_snapshot()
    snap = p7.phase7_catalog_snapshot()
    assert snap.catalog_digest == p7.PHASE7_CATALOG_DIGEST
    # ZERO new workers / capabilities: the Planner is not a selectable worker.
    assert count_final_workers(snap) == count_final_workers(base)
    assert snap.workers == base.workers
    assert snap.capability_manifest == base.capability_manifest
    # exactly three new materials (two content + one skill).
    base_content = {e.ref_key for e in base.content_manifest}
    base_skill = {e.ref_key for e in base.skill_manifest}
    new_content = {e.ref_key for e in snap.content_manifest} - base_content
    new_skill = {e.ref_key for e in snap.skill_manifest} - base_skill
    assert {f"{i}@{v}" for i, v in new_content} == set(EXPECTED_CONTENT_MATERIAL_KEYS)
    assert {f"{i}@{v}" for i, v in new_skill} == set(EXPECTED_SKILL_MATERIAL_KEYS)


def test_planner_materials_resolve_with_matching_kind_and_digest():
    snap = p7.phase7_catalog_snapshot()
    materials = {m.ref_key: m for m in p7.load_planner_materials()}
    content_by_key = {e.ref_key: e for e in snap.content_manifest}
    skill_by_key = {e.ref_key: e for e in snap.skill_manifest}
    # every planner material resolves into its manifest entry with kind + digest.
    for key, mat in materials.items():
        assert isinstance(mat, ResolvedTextMaterial)
        recomputed = catalog_material_digest(mat)
        assert mat.ref.content_digest == recomputed
        if mat.kind == "skill":
            entry = skill_by_key[key]
            assert entry.ref.content_digest == recomputed
        else:
            entry = content_by_key[key]
            assert entry.kind == mat.kind
            assert entry.ref.content_digest == recomputed
        assert entry.source_identity == "orchestrator.planner"


def test_phase7_catalog_matches_the_frozen_golden():
    assert CATALOG_GOLDEN.exists(), f"missing golden: {CATALOG_GOLDEN}"
    doc = _load_json(CATALOG_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION
    assert doc["base_catalog_digest"] == shadow.PHASE6_CATALOG_DIGEST
    assert doc["result_catalog_digest"] == p7.PHASE7_CATALOG_DIGEST
    assert doc["result_catalog_digest"] != doc["base_catalog_digest"]
    assert doc["final_worker_delta"] == 0
    assert doc["workers_added"] == 0
    assert doc["capabilities_added"] == 0
    assert tuple(doc["added_content_materials"]) == EXPECTED_CONTENT_MATERIAL_KEYS
    assert tuple(doc["added_skill_materials"]) == EXPECTED_SKILL_MATERIAL_KEYS
    assert doc["planner_spec_digest"] == p7.build_phase7_planner_spec(
        p7.phase7_catalog_snapshot()
    ).semantic_digest()


def test_phase7_catalog_base_digest_is_the_phase6_digest():
    assert p7.PHASE7_BASE_CATALOG_DIGEST == shadow.PHASE6_CATALOG_DIGEST
    assert p7.PHASE7_CATALOG_DIGEST != p7.PHASE7_BASE_CATALOG_DIGEST


# =========================================================================== #
# Point 6 — the planner SKILL.md parses byte-for-byte under skill-v1 grammar      #
# =========================================================================== #
def test_planner_skill_md_parses_byte_for_byte():
    materials = {m.ref_key: m for m in p7.load_planner_materials()}
    skill_mat = materials[("orchestrator.planner.skill", "1")]
    raw = skill_mat.raw_utf8
    # UTF-8, no BOM.
    assert raw[:3] != b"\xef\xbb\xbf"
    parsed = parse_skill_v1(raw.decode("utf-8"))
    assert parsed.name
    assert parsed.summary
    assert parsed.perfect_for
    assert parsed.not_ideal_for
    assert parsed.critical_data_source_heading == "⚠️ CRITICAL: Data Source Priority"
    assert parsed.source_priority


# =========================================================================== #
# Point 7 — planner-spec derivation determinism + frozen digest                  #
# =========================================================================== #
def test_planner_spec_derivation_is_deterministic_and_by_ref():
    catalog = p7.phase7_catalog_snapshot()
    spec_a = p7.build_phase7_planner_spec(catalog)
    spec_b = p7.build_phase7_planner_spec(catalog)
    assert spec_a.semantic_digest() == spec_b.semantic_digest()
    assert spec_a.model_tier == "reasoner_deep"
    assert spec_a.max_generation_attempts == 2
    assert spec_a.output_contract == "planner-output-v1"
    assert spec_a.skills, "planner spec skills must be non-empty"
    # refs are derived from the catalog manifests by exact id/version/digest.
    content_by_key = {e.ref_key: e for e in catalog.content_manifest}
    skill_by_key = {e.ref_key: e for e in catalog.skill_manifest}
    prompt_entry = content_by_key[("orchestrator.planner.prompt", "1")]
    assert spec_a.system_prompt_ref == prompt_entry.ref
    guardrail_entry = content_by_key[("orchestrator.planner.guardrail", "1")]
    assert guardrail_entry.ref in spec_a.guardrail_refs
    skill_entry = skill_by_key[("orchestrator.planner.skill", "1")]
    assert any(sb.skill_ref == skill_entry.ref for sb in spec_a.skills)


def test_planner_spec_digest_is_frozen_in_the_catalog_golden():
    doc = _load_json(CATALOG_GOLDEN)
    spec = p7.build_phase7_planner_spec(p7.phase7_catalog_snapshot())
    assert doc["planner_spec_digest"] == spec.semantic_digest()


# =========================================================================== #
# Point 8 — EventType frozen (25); no Phase-7 model pins a deferred guard         #
# =========================================================================== #
def test_event_type_membership_is_frozen_at_25():
    from guanlan_v2.orchestration.events import EventType
    assert len(list(EventType)) == 25


def test_deferred_payload_guard_untouched_by_phase7():
    from tests.orchestration import test_contract_completeness as tcc
    # no Phase-7 public model name leaked into the deferred-payload absence guard.
    for model in p7.PHASE7_PUBLIC_MODELS:
        assert model.__name__ not in tcc.DEFERRED_PHASE_PAYLOADS, model.__name__
    # the DecisionSchedule guard belongs to Phase 6; still-deferred Phase-8 name stays.
    for name in STILL_DEFERRED_NAMES:
        assert name in tcc.DEFERRED_PHASE_PAYLOADS


def test_no_latest_style_alias_in_the_phase7_module_namespace():
    for name in vars(p7):
        assert "latest" not in name.lower(), (
            f"a 'latest'-style alias leaked into phase7_registry.py: {name}"
        )


# =========================================================================== #
# Point 9 — resolver resolves all chain digests without reinterpretation         #
# =========================================================================== #
def test_resolver_resolves_all_chain_digests_without_reinterpretation():
    from guanlan_v2.orchestration.eventstore import SchemaRegistryResolver
    from guanlan_v2.orchestration.schema_registry import default_registry
    from guanlan_v2.orchestration.runtime_contracts import (
        PHASE2_BASE_REGISTRY_DIGEST,
        phase2_runtime_registry,
    )
    from guanlan_v2.orchestration.data.schema_registry import build_phase3_registry
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_FULL_BASE_REGISTRY_DIGEST,
        build_phase3_full_registry,
    )

    p1 = default_registry()
    p2 = phase2_runtime_registry(PHASE2_BASE_REGISTRY_DIGEST)
    p3_data = build_phase3_registry(p2.registry_digest)
    p3_full = build_phase3_full_registry(PHASE3_FULL_BASE_REGISTRY_DIGEST)
    p4 = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)
    p5 = bootstrap.build_phase5_registry(bootstrap.PHASE5_BASE_REGISTRY_DIGEST)
    p6 = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    p7reg = p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST)

    regs = (p1, p2, p3_data, p3_full, p4, p5, p6, p7reg)
    digests = [r.registry_digest for r in regs]
    # all eight chain digests are distinct — no "latest" alias collapsed them.
    assert len(set(digests)) == 8

    resolver = SchemaRegistryResolver()
    for reg in regs:
        resolver.register(reg)
    # a Plan bound to any upstream digest resolves to that exact registry.
    assert resolver.resolve(p6.registry_digest) is p6
    assert resolver.resolve(p7reg.registry_digest) is p7reg
    # a Phase-<=6 Plan never reinterprets to the Phase-7 registry.
    assert resolver.resolve(p1.registry_digest) is not p7reg
    assert resolver.resolve(p6.registry_digest) is not p7reg


def test_phase7_payloads_register_at_v1_only():
    reg = p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST)
    keys = {e.key for e in reg.manifest()}
    for name in EXPECTED_PUBLIC_NAMES:
        assert f"{name}@1" in keys, f"{name} must register at @1"


def test_still_deferred_phase8_names_absent_everywhere():
    p7keys = {
        e.schema_ref.name
        for e in p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST).manifest()
    }
    for name in STILL_DEFERRED_NAMES:
        assert name not in p7keys, f"{name} is a Phase 8 deferral, absent from Phase 7"
