# -*- coding: utf-8 -*-
"""Phase 9 · Task 9 — the cumulative registry/catalog chain node (the LAST node).

Locks the linear registry/catalog chain the 完整落子/帷幄 adapter phase seals, built
as a pure ADDITION over the sealed Phase-8 四车道 chain (never a fork, never a
"latest" alias):

* ``build_phase9_registry(expected_phase8_digest)`` builds a *fresh sealed*
  cumulative registry over the exact Phase-8 cumulative set plus the reviewed nine
  :data:`PHASE9_PUBLIC_MODELS`; a wrong base digest is rejected before any
  registration; inherited entries stay byte-identical to their Phase-<=8 goldens;
  the digest is registration-order independent and matches the hand-reviewed golden.
* ``build_phase9_catalog_snapshot(...)`` seals the FULL catalog: it inherits the
  reviewed Phase-8 27-worker catalog byte-identical and adds ONLY the two adapter
  source materials (the ``PIT_REPLAY`` PitReader source + the ``ONLINE`` live_client
  source) — each a trusted handler material + a serialized source-descriptor
  material — behind the EXISTING Phase-3 method/capability ids. No new method id, no
  new capability id, no worker-allowlist edit, no new worker id, no order/signal
  write capability, and NO integer assertion on the worker count (the 枚举钉旧
  vaccine): the count is proven UNCHANGED from the inherited base.
* the Phase-9 public/internal partition over the Phase-9 contract modules is
  exhaustive and disjoint for the ContractModel surface; the non-ContractModel
  carriers/service-ports are documented with reviewed reasons.
* EventType is UNCHANGED — Phase 9 adds no member and flips no absence guard.

Goldens are NEVER auto-regenerated by tests: a changed manifest is a reviewed
contract change regenerated by hand and re-reviewed.

Run: ``pytest tests/orchestration/test_phase9_registry_chain.py -v``
"""
from __future__ import annotations

import hashlib
import importlib
import inspect
import json
from pathlib import Path

import pytest

from guanlan_v2.orchestration import bootstrap, phase7_registry as p7, shadow, trial
from guanlan_v2.orchestration import lane_catalog as p8
from guanlan_v2.orchestration.adapters import chain as ch
from guanlan_v2.orchestration.catalog import CatalogError, count_final_workers
from guanlan_v2.orchestration.digest import CJSON_VERSION, ContractModel, DigestModel

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"
SCHEMA_GOLDEN = GOLDEN_DIR / "phase9_schema_manifest_v1.json"
CATALOG_GOLDEN = GOLDEN_DIR / "phase9_catalog_manifest_v1.json"

#: sha256 pins of the immediate upstream goldens — Phase 9 never regenerates them.
UPSTREAM_GOLDEN_SHA256 = {
    "phase8_schema_manifest_v1.json":
        "e2c02006efe58c4fbccbce6a2a0be70edb6ed3923b132330f4046e7ea437d92f",
    "phase8_catalog_manifest_v1.json":
        "0211611674174b1848858023648cb85e8a4eed7a1ef3bc7ec996a16998ae9615",
}

#: the Phase-9 contract modules whose public ContractModel subclasses the completeness
#: firewall governs. This tuple MUST equal ``test_contract_completeness.PHASE9_MODULES``
#: (asserted by ``test_phase9_contract_modules_stay_in_sync_with_the_discovery_firewall``
#: below) — otherwise a public contract in a NEW Phase-9 module would escape BOTH the
#: Phase-1 discovery firewall and this classification firewall. ``adapters.luozi`` is in
#: neither list: it is a Phase-6 module (``PHASE6_MODULES``) extended additively by
#: Phase 9. Modules pre-listed ahead of a later task's creation are tolerated (they
#: simply contribute no models yet).
PHASE9_CONTRACT_MODULES = (
    "guanlan_v2.orchestration.adapters.contracts",
    "guanlan_v2.orchestration.adapters.replay_data",
    "guanlan_v2.orchestration.adapters.live_data",
    "guanlan_v2.orchestration.adapters.weiwo",
    "guanlan_v2.orchestration.adapters.retirement",
    "guanlan_v2.orchestration.adapters.chain",
    "guanlan_v2.orchestration.adapters.api",
    "guanlan_v2.orchestration.adapters.durable",
)

#: the nine reviewed public names the registered Phase-9 surface must equal.
EXPECTED_PUBLIC_NAMES = frozenset({
    "ReplayDecisionPoint", "ShadowExecutionConfig", "ShadowCurveSeries",
    "DualCurveReport", "ShadowReplayRunState", "ReplayWakeupReceipt",
    "MirrorHarnessReport", "EntryPointRetirementGate", "RetirementReadinessReport",
})

#: the four reviewed INTERNAL nested ContractModel value-object names.
EXPECTED_INTERNAL_CONTRACT_NAMES = frozenset({
    "ShadowCurvePoint", "MirrorHarnessCaseResult", "RetirementCriterion",
    "RetirementCriterionResult",
})

#: the six reviewed INTERNAL non-ContractModel carriers / service ports.
EXPECTED_INTERNAL_NONCONTRACT_NAMES = frozenset({
    "ReplayRuntimeBindings", "WeiwoRuntimeBindings", "WeiwoRunReceipt",
    "ReplayPointClock", "PitReaderRawSource", "LiveClientSource",
})

#: the two new adapter source ids Phase 9 seals into the catalog (never a new worker).
EXPECTED_NEW_SOURCE_IDS = frozenset({"guanlan.pit_replay", "guanlan.online_live"})

#: the frozen Phase-8 EventType value set — Phase 9 must not touch it.
EXPECTED_EVENTTYPE_VALUES = frozenset({
    "ArtifactRelated", "ArtifactStaged", "BudgetReleased", "BudgetReserved",
    "BudgetSettled", "CaseCreated", "CaseMatured", "CaseReviewed",
    "ContextSnapshotFrozen", "DebateMessagePublished", "ExperimentStateChanged",
    "LayerCommitted", "NodeStateChanged", "PlanApproved", "PlanDrafted", "PlanFrozen",
    "PlanRejected", "RunCancelled", "RunCompleted", "RunFailed", "RunRequested",
    "ShadowIntentIssued", "ShadowTargetApplied", "TrialExhausted", "TrialReserved",
    "TrialRevealed",
})


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _discover_phase9_contract_models() -> set[type]:
    found: set[type] = set()
    for module_name in PHASE9_CONTRACT_MODULES:
        try:
            module = importlib.import_module(module_name)
        except ModuleNotFoundError:
            continue  # a later task creates it; inert until then
        for obj in vars(module).values():
            if (
                inspect.isclass(obj)
                and issubclass(obj, ContractModel)
                and obj not in (ContractModel, DigestModel)
                and obj.__module__ == module_name
                and not obj.__name__.startswith("_")
            ):
                found.add(obj)
    return found


# =========================================================================== #
# Point 1 — build rejects a wrong base; the correct base seals the right digest #
# =========================================================================== #
def test_build_phase9_registry_rejects_a_wrong_expected_digest():
    with pytest.raises(ch.Phase9RegistryError):
        ch.build_phase9_registry("0" * 64)
    # the Phase-7 digest is NOT the Phase-8 base either (no "latest" collapse).
    with pytest.raises(ch.Phase9RegistryError):
        ch.build_phase9_registry(p7.PHASE7_REGISTRY_DIGEST)
    # Phase 9's own digest is not its own base (wrong-base rejection, other direction).
    with pytest.raises(ch.Phase9RegistryError):
        ch.build_phase9_registry(ch.PHASE9_REGISTRY_DIGEST)


def test_build_phase9_registry_seals_and_matches_the_frozen_digest():
    reg = ch.build_phase9_registry(ch.PHASE9_BASE_REGISTRY_DIGEST)
    assert reg.sealed is True
    assert reg.registry_digest == ch.PHASE9_REGISTRY_DIGEST
    # a fresh sealed instance per call (never a shared mutable singleton).
    other = ch.build_phase9_registry(ch.PHASE9_BASE_REGISTRY_DIGEST)
    assert other is not reg
    assert other.registry_digest == reg.registry_digest


def test_phase9_base_registry_digest_is_the_phase8_digest():
    assert ch.PHASE9_BASE_REGISTRY_DIGEST == p8.PHASE8_REGISTRY_DIGEST
    assert ch.PHASE9_REGISTRY_DIGEST != ch.PHASE9_BASE_REGISTRY_DIGEST


# =========================================================================== #
# Point 2 — golden equality; inherited byte-identical; upstream goldens frozen   #
# =========================================================================== #
def test_registry_matches_the_frozen_golden_entry_for_entry():
    assert SCHEMA_GOLDEN.exists(), f"missing golden: {SCHEMA_GOLDEN}"
    doc = _load_json(SCHEMA_GOLDEN)
    assert doc["algorithm"] == CJSON_VERSION == "sha256+cjson-v1"
    assert doc["base_registry_digest"] == p8.PHASE8_REGISTRY_DIGEST
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    reg = ch.build_phase9_registry(ch.PHASE9_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    assert set(manifest) == set(golden), (
        "phase9 registry key set drifted from phase9_schema_manifest_v1.json; "
        "regenerate + re-review by hand if intended"
    )
    for key in sorted(golden):
        assert manifest[key] == golden[key], f"JSON-schema digest drift for {key}"
    assert reg.registry_digest == doc["registry_digest"]


def test_inherited_entries_are_byte_identical_to_the_phase8_golden():
    phase8_doc = _load_json(GOLDEN_DIR / "phase8_schema_manifest_v1.json")
    phase8 = {e["key"]: e["json_schema_digest"] for e in phase8_doc["entries"]}
    reg = ch.build_phase9_registry(ch.PHASE9_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    # every Phase-8 (cumulative) key is inherited byte-identical …
    for key, digest in phase8.items():
        assert manifest[key] == digest, f"inherited schema {key} drifted in phase9"
    # … and the only new keys are exactly the nine Phase-9 public contracts.
    new_keys = set(manifest) - set(phase8)
    assert {k.split("@")[0] for k in new_keys} == EXPECTED_PUBLIC_NAMES
    assert len(new_keys) == 9


def test_inherited_entries_are_byte_identical_across_every_upstream_manifest():
    """Walk ALL phase schema goldens — every inherited key stays byte-identical."""
    reg = ch.build_phase9_registry(ch.PHASE9_BASE_REGISTRY_DIGEST)
    manifest = {e.key: e.json_schema_digest for e in reg.manifest()}
    upstream_goldens = (
        "schema_manifest_v1.json",
        "runtime_schema_manifest_v1.json",
        "data_schema_manifest_v1.json",
        "phase3_full_schema_manifest_v1.json",
        "phase4_schema_manifest_v1.json",
        "phase5_schema_manifest_v1.json",
        "phase6_schema_manifest_v1.json",
        "phase7_schema_manifest_v1.json",
        "phase8_schema_manifest_v1.json",
    )
    for fname in upstream_goldens:
        path = GOLDEN_DIR / fname
        if not path.exists():
            continue
        doc = _load_json(path)
        for e in doc.get("entries", []):
            key = e["key"]
            if key in manifest:
                assert manifest[key] == e["json_schema_digest"], (
                    f"inherited schema {key} drifted from {fname} in phase9"
                )


def test_new_public_contract_digests_are_recomputable_from_the_models():
    from guanlan_v2.orchestration.digest import content_digest

    doc = _load_json(SCHEMA_GOLDEN)
    golden = {e["key"]: e["json_schema_digest"] for e in doc["entries"]}
    for model in ch.PHASE9_PUBLIC_MODELS:
        key = f"{model.__name__}@{model.model_fields['schema_version'].default}"
        assert golden[key] == content_digest(model.model_json_schema())


def test_upstream_goldens_are_byte_unchanged():
    for fname, sha in UPSTREAM_GOLDEN_SHA256.items():
        raw = (GOLDEN_DIR / fname).read_bytes()
        assert hashlib.sha256(raw).hexdigest() == sha, (
            f"upstream golden {fname} changed — Phase 9 must never regenerate it"
        )


# =========================================================================== #
# Point 3 — registration-order independence                                     #
# =========================================================================== #
def test_registration_order_independence():
    from guanlan_v2.orchestration.data.schema_registry import (
        PHASE3_PUBLIC_MODELS as DATA_PUBLIC,
    )
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_MEMORY_PUBLIC_MODELS as MEM_PUBLIC,
    )
    from guanlan_v2.orchestration.runtime_contracts import (
        Phase2RuntimeRegistry,
        phase2_public_models,
    )

    canonical = ch.build_phase9_registry(ch.PHASE9_BASE_REGISTRY_DIGEST)
    reversed_reg = Phase2RuntimeRegistry()
    for model in reversed(
        tuple(phase2_public_models())
        + tuple(DATA_PUBLIC)
        + tuple(MEM_PUBLIC)
        + tuple(trial.PHASE4_PUBLIC_MODELS)
        + tuple(bootstrap.PHASE5_PUBLIC_MODELS)
        + tuple(shadow.PHASE6_PUBLIC_MODELS)
        + tuple(p7.PHASE7_PUBLIC_MODELS)
        + tuple(p8.PHASE8_PUBLIC_MODELS)
        + tuple(ch.PHASE9_PUBLIC_MODELS)
    ):
        reversed_reg.register(model)
    reversed_reg.seal()
    assert reversed_reg.manifest() == canonical.manifest()
    assert reversed_reg.registry_digest == canonical.registry_digest


# =========================================================================== #
# Point 4 — Phase-9 completeness firewall (exhaustive + disjoint)               #
# =========================================================================== #
def test_public_tuple_shape_and_names():
    assert isinstance(ch.PHASE9_PUBLIC_MODELS, tuple)
    assert len(ch.PHASE9_PUBLIC_MODELS) == 9
    assert len(set(ch.PHASE9_PUBLIC_MODELS)) == 9
    names = {m.__name__ for m in ch.PHASE9_PUBLIC_MODELS}
    assert names == EXPECTED_PUBLIC_NAMES
    for model in ch.PHASE9_PUBLIC_MODELS:
        assert issubclass(model, ContractModel)


def test_internal_map_is_a_reviewed_reason_map():
    assert isinstance(ch.PHASE9_INTERNAL_MODELS, dict)
    names = {m.__name__ for m in ch.PHASE9_INTERNAL_MODELS}
    assert names == (EXPECTED_INTERNAL_CONTRACT_NAMES | EXPECTED_INTERNAL_NONCONTRACT_NAMES)
    for model, reason in ch.PHASE9_INTERNAL_MODELS.items():
        assert isinstance(model, type)
        assert isinstance(reason, str) and reason.strip()


def test_phase9_contract_modules_stay_in_sync_with_the_discovery_firewall():
    """Close the "a public contract in a NEW Phase-9 module escapes both firewalls" hole.

    ``PHASE9_CONTRACT_MODULES`` (this file, the classification firewall's walk) and
    ``test_contract_completeness.PHASE9_MODULES`` (the Phase-1 discovery firewall's
    exclusion set) are two hand-maintained lists of the same surface. If a later task
    adds a Phase-9 module to the discovery firewall's exclusion set but not here, its
    public contracts would be excluded from the Phase-1 review AND never classified into
    ``PHASE9_PUBLIC_MODELS`` / ``PHASE9_INTERNAL_MODELS`` — registered by nobody, caught
    by nobody. Tying the two lists together is what makes the partition test above a
    real firewall rather than a firewall over a hand-picked subset.
    """
    tcc = importlib.import_module("tests.orchestration.test_contract_completeness")
    assert set(PHASE9_CONTRACT_MODULES) == set(tcc.PHASE9_MODULES), (
        "PHASE9_CONTRACT_MODULES has drifted from test_contract_completeness."
        "PHASE9_MODULES; a public contract in a module listed in only one of them "
        "escapes both the discovery and the classification firewall"
    )
    # neither list may claim adapters.luozi — it is a Phase-6-owned module.
    assert "guanlan_v2.orchestration.adapters.luozi" not in set(PHASE9_CONTRACT_MODULES)
    assert "guanlan_v2.orchestration.adapters.luozi" in set(tcc.PHASE6_MODULES)


def test_internal_map_partitions_the_contract_surface_exactly():
    discovered = _discover_phase9_contract_models()
    public = set(ch.PHASE9_PUBLIC_MODELS)
    internal_contract = {
        m for m in ch.PHASE9_INTERNAL_MODELS
        if isinstance(m, type) and issubclass(m, ContractModel)
    }
    classified = public | internal_contract
    assert not (public & internal_contract), (
        "a Phase-9 contract cannot be both registered and internal"
    )
    unclassified = discovered - classified
    assert not unclassified, (
        "unreviewed Phase-9 public contracts: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in unclassified))
    )
    phantom = classified - discovered
    assert not phantom, (
        "classified contract models not discovered in the Phase-9 modules: "
        + ", ".join(sorted(f"{m.__module__}.{m.__name__}" for m in phantom))
    )
    assert classified == discovered


def test_internal_noncontract_carriers_are_genuinely_not_contract_models():
    # the six reviewed carriers / service ports are NOT ContractModel subclasses at
    # all (they can never be registered): they are documented with a reviewed reason
    # so the partition is honest about every unregistered Phase-9 identity.
    non_contract = {
        m for m in ch.PHASE9_INTERNAL_MODELS
        if not (isinstance(m, type) and issubclass(m, ContractModel))
    }
    assert {m.__name__ for m in non_contract} == EXPECTED_INTERNAL_NONCONTRACT_NAMES


def test_every_public_member_has_a_closed_schema_version():
    for model in ch.PHASE9_PUBLIC_MODELS:
        field = model.model_fields.get("schema_version")
        assert field is not None
        assert isinstance(field.default, str) and field.default, model.__name__


def test_default_registry_does_not_register_any_phase9_public_model():
    from guanlan_v2.orchestration.schema_registry import default_registry

    registered = {e.schema_ref.name for e in default_registry().manifest()}
    for model in ch.PHASE9_PUBLIC_MODELS:
        assert model.__name__ not in registered, model.__name__


def test_phase9_payloads_register_at_v1_only():
    reg = ch.build_phase9_registry(ch.PHASE9_BASE_REGISTRY_DIGEST)
    keys = {e.key for e in reg.manifest()}
    for name in EXPECTED_PUBLIC_NAMES:
        assert f"{name}@1" in keys, f"{name} must register at @1"


# =========================================================================== #
# Point 5 — EventType is UNCHANGED (no new member, no absence-guard flip)        #
# =========================================================================== #
def test_eventtype_value_set_is_the_frozen_phase8_set():
    from guanlan_v2.orchestration.events import EventType

    values = {e.value for e in EventType}
    assert values == EXPECTED_EVENTTYPE_VALUES
    assert len(values) == len(EXPECTED_EVENTTYPE_VALUES)


# =========================================================================== #
# Point 6 — resolver resolves all chain digests without reinterpretation         #
# =========================================================================== #
def test_resolver_resolves_all_chain_digests_without_reinterpretation():
    from guanlan_v2.orchestration.eventstore import SchemaRegistryResolver
    from guanlan_v2.orchestration.schema_registry import default_registry
    from guanlan_v2.orchestration.runtime_contracts import (
        PHASE2_BASE_REGISTRY_DIGEST,
        phase2_runtime_registry,
    )
    from guanlan_v2.orchestration.data.schema_registry import build_phase3_registry
    from guanlan_v2.orchestration.memory.schema_registry import (
        PHASE3_FULL_BASE_REGISTRY_DIGEST,
        build_phase3_full_registry,
    )

    p1 = default_registry()
    p2 = phase2_runtime_registry(PHASE2_BASE_REGISTRY_DIGEST)
    p3_data = build_phase3_registry(p2.registry_digest)
    p3_full = build_phase3_full_registry(PHASE3_FULL_BASE_REGISTRY_DIGEST)
    p4 = trial.build_phase4_registry(trial.PHASE4_BASE_REGISTRY_DIGEST)
    p5 = bootstrap.build_phase5_registry(bootstrap.PHASE5_BASE_REGISTRY_DIGEST)
    p6 = shadow.build_phase6_registry(shadow.PHASE6_BASE_REGISTRY_DIGEST)
    p7reg = p7.build_phase7_registry(p7.PHASE7_BASE_REGISTRY_DIGEST)
    p8reg = p8.build_phase8_registry(p8.PHASE8_BASE_REGISTRY_DIGEST)
    p9reg = ch.build_phase9_registry(ch.PHASE9_BASE_REGISTRY_DIGEST)

    regs = (p1, p2, p3_data, p3_full, p4, p5, p6, p7reg, p8reg, p9reg)
    digests = [r.registry_digest for r in regs]
    # all ten chain digests are distinct — no "latest" alias collapsed them.
    assert len(set(digests)) == 10

    resolver = SchemaRegistryResolver()
    for reg in regs:
        resolver.register(reg)
    assert resolver.resolve(p8reg.registry_digest) is p8reg
    assert resolver.resolve(p9reg.registry_digest) is p9reg
    # a Phase-<=8 Plan never reinterprets to the Phase-9 registry.
    assert resolver.resolve(p1.registry_digest) is not p9reg
    assert resolver.resolve(p8reg.registry_digest) is not p9reg


def test_no_latest_style_alias_in_the_phase9_chain_namespace():
    for name in vars(ch):
        if name.startswith("PHASE9") or "phase9" in name.lower():
            assert "latest" not in name.lower(), (
                f"a 'latest'-style alias leaked into the phase9 chain: {name}"
            )
    offenders = [n for n in dir(ch) if "latest" in n.lower() and not n.startswith("_")]
    assert offenders == [], f"adapters.chain exposes a 'latest' alias: {offenders}"


# =========================================================================== #
# Point 7 — the catalog seal: two adapter sources added over the inherited P8    #
# =========================================================================== #
def test_phase9_catalog_base_digest_is_the_phase8_digest():
    assert ch.PHASE9_BASE_CATALOG_DIGEST == p8.PHASE8_CATALOG_DIGEST
    assert ch.PHASE9_CATALOG_DIGEST != ch.PHASE9_BASE_CATALOG_DIGEST


def test_build_phase9_catalog_rejects_a_non_canonical_base():
    replay_desc, live_desc, materials = ch.build_phase9_source_materials()
    with pytest.raises(CatalogError):
        ch.build_phase9_catalog_snapshot(
            p7.phase7_catalog_snapshot(),
            replay_source_descriptor=replay_desc,
            live_source_descriptor=live_desc,
            resolved_materials=materials,
        )


def test_phase9_catalog_matches_the_frozen_golden():
    assert CATALOG_GOLDEN.exists(), f"missing golden: {CATALOG_GOLDEN}"
    doc = _load_json(CATALOG_GOLDEN)
    snap = ch.phase9_catalog_snapshot()
    assert doc["algorithm"] == CJSON_VERSION
    assert doc["base_catalog_digest"] == p8.PHASE8_CATALOG_DIGEST
    assert doc["result_catalog_digest"] == snap.catalog_digest == ch.PHASE9_CATALOG_DIGEST
    assert doc["result_catalog_digest"] != doc["base_catalog_digest"]
    assert doc["catalog_version"] == snap.catalog_version
    assert set(doc["new_source_ids"]) == EXPECTED_NEW_SOURCE_IDS
    # the two frozen source-descriptor digests reproduce.
    replay_desc, live_desc, _mats = ch.build_phase9_source_materials()
    got_source_digests = {
        replay_desc.source_id: replay_desc.descriptor_digest,
        live_desc.source_id: live_desc.descriptor_digest,
    }
    assert got_source_digests == doc["source_descriptor_digests"]
    # the four added content materials reproduce (id@version -> content digest).
    base = p8.phase8_catalog_snapshot()
    base_keys = {e.ref_key for e in base.content_manifest}
    added = {
        f"{e.ref.id}@{e.ref.version}": e.ref.content_digest
        for e in snap.content_manifest if e.ref_key not in base_keys
    }
    assert added == doc["added_content_materials"]


def test_inherited_catalog_manifests_are_byte_identical_to_phase8():
    base = p8.phase8_catalog_snapshot()
    snap = ch.phase9_catalog_snapshot()
    # workers, skills and capabilities pass through byte-identical (no new worker, no
    # allowlist edit, no new capability); only the content manifest grows.
    assert snap.workers == base.workers
    assert snap.skill_manifest == base.skill_manifest
    assert snap.capability_manifest == base.capability_manifest
    base_content = {e.ref_key: e for e in base.content_manifest}
    for e in snap.content_manifest:
        if e.ref_key in base_content:
            assert e == base_content[e.ref_key], (
                f"inherited content material {e.ref_key} drifted in phase9"
            )
    added = [e for e in snap.content_manifest if e.ref_key not in base_content]
    assert len(added) == 4  # two handlers + two serialized descriptors


def test_phase9_adds_no_worker_and_no_capability_the_count_is_unchanged():
    # 枚举钉旧 vaccine: NO integer literal for the worker count — the count is proven
    # UNCHANGED from the inherited Phase-8 base, and every worker id is identical.
    base = p8.phase8_catalog_snapshot()
    snap = ch.phase9_catalog_snapshot()
    assert count_final_workers(snap) == count_final_workers(base)
    assert {w.id for w in snap.workers} == {w.id for w in base.workers}
    # no capability id was added (the descriptors reach the inherited data caps).
    assert {e.ref_key for e in snap.capability_manifest} == {
        e.ref_key for e in base.capability_manifest
    }


def test_compat_workers_stay_static_legacy_only():
    base = {w.id: w for w in p8.phase8_catalog_snapshot().workers}
    snap = ch.phase9_catalog_snapshot()
    compat = [w for w in snap.workers if w.id.startswith("compat.")]
    assert compat, "the compat.* mirror must still be present"
    for w in compat:
        assert w == base[w.id], f"compat worker {w.id} drifted in phase9"
        assert w.capability_allowlist == (), f"compat worker {w.id} gained a capability"


# =========================================================================== #
# Point 8 — the descriptors bind EXISTING method/capability ids, no write cap    #
# =========================================================================== #
def test_descriptors_bind_only_existing_method_and_capability_ids():
    from guanlan_v2.orchestration.data.catalog import (
        data_capability_refs,
        phase3_data_surface,
    )

    surface = phase3_data_surface()
    known_method_refs = {
        (s.method_id, s.method_version, s.spec_digest) for s in surface.method_specs
    }
    known_caps = set(data_capability_refs().values())
    replay_desc, live_desc, _mats = ch.build_phase9_source_materials()
    for desc in (replay_desc, live_desc):
        for mref in desc.method_refs:
            assert (mref.id, mref.version, mref.content_digest) in known_method_refs, (
                f"source {desc.source_id} mints a NEW method id {mref.id}@{mref.version}"
            )
        for cref in desc.method_capability_refs:
            assert cref in known_caps, (
                f"source {desc.source_id} mints a NEW capability {cref.id}@{cref.version}"
            )


def test_descriptors_are_mode_exclusive_and_read_only_no_write_capability():
    from guanlan_v2.orchestration.enums import DataMode
    from guanlan_v2.orchestration.data.catalog import phase3_data_surface

    surface = phase3_data_surface()
    spec_by_ref = {
        (s.method_id, s.method_version, s.spec_digest): s for s in surface.method_specs
    }
    replay_desc, live_desc, _mats = ch.build_phase9_source_materials()
    # the structural mode exclusion — a PIT_REPLAY read can never resolve the ONLINE
    # source and vice versa.
    assert replay_desc.supported_modes == (DataMode.PIT_REPLAY,)
    assert live_desc.supported_modes == (DataMode.ONLINE,)
    # every bound method spec is read-only — the snapshot carries NO order/signal write.
    write_markers = ("order", "trade", "write", "submit", "execute", "place")
    for desc in (replay_desc, live_desc):
        for mref in desc.method_refs:
            spec = spec_by_ref[(mref.id, mref.version, mref.content_digest)]
            assert spec.read_only is True, f"{desc.source_id} binds a non-read method"
            assert not any(m in mref.id.lower() for m in write_markers)
    # sweep the whole catalog's capabilities: none is an order/signal write capability.
    snap = ch.phase9_catalog_snapshot()
    for entry in snap.capability_manifest:
        low = entry.ref.id.lower()
        assert not any(m in low for m in write_markers), (
            f"a write-shaped capability leaked into the phase9 catalog: {entry.ref.id}"
        )


def test_source_materials_are_the_two_handlers_and_two_descriptors():
    replay_desc, live_desc, materials = ch.build_phase9_source_materials()
    from guanlan_v2.orchestration.catalog import ResolvedTextMaterial

    assert all(isinstance(m, ResolvedTextMaterial) for m in materials)
    kinds = sorted(m.kind for m in materials)
    assert kinds == ["guardrail", "guardrail", "handler", "handler"]
    # each descriptor's handler_ref resolves to a handler material in the set.
    handler_keys = {m.ref_key for m in materials if m.kind == "handler"}
    assert (replay_desc.handler_ref.id, replay_desc.handler_ref.version) in handler_keys
    assert (live_desc.handler_ref.id, live_desc.handler_ref.version) in handler_keys
